# Swahili (Kenya) translations for cinder.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the cinder project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Cinder\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-08-08 06:10+0000\n"
"PO-Revision-Date: 2013-05-29 08:13+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Swahili (Kenya) "
"(http://www.transifex.com/projects/p/openstack/language/sw_KE/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: cinder/context.py:61
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: cinder/context.py:93
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: cinder/exception.py:65
msgid "Unexpected error while running command."
msgstr ""

#: cinder/exception.py:68
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: cinder/exception.py:92
msgid "An unknown exception occurred."
msgstr ""

#: cinder/exception.py:114 cinder/openstack/common/rpc/common.py:86
msgid "Exception in string format operation"
msgstr ""

#: cinder/exception.py:126
msgid "Connection to glance failed"
msgstr ""

#: cinder/exception.py:130
msgid "Not authorized."
msgstr ""

#: cinder/exception.py:135
msgid "User does not have admin privileges"
msgstr ""

#: cinder/exception.py:139
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: cinder/exception.py:143
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: cinder/exception.py:147
msgid "Unacceptable parameters."
msgstr ""

#: cinder/exception.py:152
msgid "Invalid snapshot"
msgstr ""

#: cinder/exception.py:156
#, python-format
msgid "Invalid source volume %(reason)s."
msgstr ""

#: cinder/exception.py:160
#, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr ""

#: cinder/exception.py:164
msgid "Failed to load data into json format"
msgstr ""

#: cinder/exception.py:168
msgid "The request is invalid."
msgstr ""

#: cinder/exception.py:172
msgid "The results are invalid."
msgstr ""

#: cinder/exception.py:176
msgid "Invalid input received"
msgstr ""

#: cinder/exception.py:180
msgid "Invalid volume type"
msgstr ""

#: cinder/exception.py:184
msgid "Invalid volume"
msgstr ""

#: cinder/exception.py:188
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: cinder/exception.py:192
msgid "Invalid host"
msgstr ""

#: cinder/exception.py:198
#, python-format
msgid "%(err)s"
msgstr ""

#: cinder/exception.py:202
msgid "Invalid auth key"
msgstr ""

#: cinder/exception.py:206
msgid "Service is unavailable at this time."
msgstr ""

#: cinder/exception.py:210
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: cinder/exception.py:214
#, python-format
msgid "The device in the path %(path)s is unavailable: %(reason)s"
msgstr ""

#: cinder/exception.py:218
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: cinder/exception.py:222
msgid "Resource could not be found."
msgstr ""

#: cinder/exception.py:228
#, python-format
msgid "Volume %(volume_id)s persistence file could not be found."
msgstr ""

#: cinder/exception.py:232
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: cinder/exception.py:236
#, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr ""

#: cinder/exception.py:241
#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr ""

#: cinder/exception.py:245
#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: cinder/exception.py:250 cinder/exception.py:263
msgid "Invalid metadata"
msgstr ""

#: cinder/exception.py:254 cinder/exception.py:267
msgid "Invalid metadata size"
msgstr ""

#: cinder/exception.py:258
#, python-format
msgid "Snapshot %(snapshot_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: cinder/exception.py:271
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr ""

#: cinder/exception.py:275
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr ""

#: cinder/exception.py:280
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: cinder/exception.py:285
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: cinder/exception.py:289
#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr ""

#: cinder/exception.py:293
#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr ""

#: cinder/exception.py:298 cinder/exception.py:314
#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:302
#, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:306
#, python-format
msgid "Failed to attach iSCSI target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:310
#, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:318
#, python-format
msgid "Failed to create iser target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:322
#, python-format
msgid "Failed to attach iser target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:326
#, python-format
msgid "Failed to remove iser target for volume %(volume_id)s."
msgstr ""

#: cinder/exception.py:330
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: cinder/exception.py:334
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: cinder/exception.py:338
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: cinder/exception.py:342
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: cinder/exception.py:346
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: cinder/exception.py:350
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: cinder/exception.py:354
#, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr ""

#: cinder/exception.py:358
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: cinder/exception.py:362
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: cinder/exception.py:366
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: cinder/exception.py:371
msgid "Quota could not be found"
msgstr ""

#: cinder/exception.py:375
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: cinder/exception.py:379
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: cinder/exception.py:383
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: cinder/exception.py:387
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: cinder/exception.py:391
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: cinder/exception.py:395
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: cinder/exception.py:399
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: cinder/exception.py:403
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: cinder/exception.py:408
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: cinder/exception.py:412
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: cinder/exception.py:416
msgid "Action not allowed."
msgstr ""

#: cinder/exception.py:425
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr ""

#: cinder/exception.py:429
#, python-format
msgid "Volume Type %(id)s already exists."
msgstr ""

#: cinder/exception.py:433
msgid "Migration error"
msgstr ""

#: cinder/exception.py:437
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: cinder/exception.py:441
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: cinder/exception.py:445
#, python-format
msgid "Could not find parameter %(param)s"
msgstr ""

#: cinder/exception.py:449
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: cinder/exception.py:453
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: cinder/exception.py:457
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: cinder/exception.py:461
msgid "Quota exceeded"
msgstr ""

#: cinder/exception.py:468
msgid "Requested volume or snapshot exceeds allowed Gigabytes quota"
msgstr ""

#: cinder/exception.py:473
msgid "Maximum volume/snapshot size exceeded"
msgstr ""

#: cinder/exception.py:477
#, python-format
msgid "Maximum number of volumes allowed (%(allowed)d) exceeded"
msgstr ""

#: cinder/exception.py:481
#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded"
msgstr ""

#: cinder/exception.py:485
#, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr ""

#: cinder/exception.py:489
#, python-format
msgid "3PAR Host already exists: %(err)s.  %(info)s"
msgstr ""

#: cinder/exception.py:493
#, python-format
msgid "Invalid 3PAR Domain: %(err)s"
msgstr ""

#: cinder/exception.py:497
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr ""

#: cinder/exception.py:502
msgid "Bad response from SolidFire API"
msgstr ""

#: cinder/exception.py:506
#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr ""

#: cinder/exception.py:510
#, python-format
msgid "Unknown or unsupported command %(cmd)s"
msgstr ""

#: cinder/exception.py:514
#, python-format
msgid "Malformed response to command %(cmd)s: %(reason)s"
msgstr ""

#: cinder/exception.py:518
#, python-format
msgid "Bad HTTP response status %(status)s"
msgstr ""

#: cinder/exception.py:522
#, python-format
msgid "Operation failed with status=%(status)s. Full dump: %(data)s"
msgstr ""

#: cinder/exception.py:526
#, python-format
msgid "Unable to create server object for initiator %(name)s"
msgstr ""

#: cinder/exception.py:530
#, python-format
msgid "Unable to find server object for initiator %(name)s"
msgstr ""

#: cinder/exception.py:534
msgid "Unable to find any active VPSA controller"
msgstr ""

#: cinder/exception.py:538
#, python-format
msgid "Failed to retrieve attachments for volume %(name)s"
msgstr ""

#: cinder/exception.py:542
#, python-format
msgid "Invalid attachment info for volume %(name)s: %(reason)s"
msgstr ""

#: cinder/exception.py:546
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: cinder/exception.py:550
#, python-format
msgid "Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr ""

#: cinder/exception.py:555
msgid "Unknown NFS exception"
msgstr ""

#: cinder/exception.py:559
msgid "No mounted NFS shares found"
msgstr ""

#: cinder/exception.py:563 cinder/exception.py:575
#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr ""

#: cinder/exception.py:567
msgid "Unknown Gluster exception"
msgstr ""

#: cinder/exception.py:571
msgid "No mounted Gluster shares found"
msgstr ""

#: cinder/exception.py:579
#, python-format
msgid ""
"Glance metadata cannot be updated, key %(key)s exists for volume id "
"%(volume_id)s"
msgstr ""

#: cinder/exception.py:584
#, python-format
msgid "Failed to copy image to volume: %(reason)s"
msgstr ""

#: cinder/exception.py:588
msgid "Invalid Ceph args provided for backup rbd operation"
msgstr ""

#: cinder/exception.py:592
msgid "An error has occurred during backup operation"
msgstr ""

#: cinder/exception.py:596
msgid "Backup RBD operation failed"
msgstr ""

#: cinder/exception.py:600
#, python-format
msgid "Backup volume %(volume_id)s type not recognised."
msgstr ""

#: cinder/exception.py:604
#, python-format
msgid "Backup %(backup_id)s could not be found."
msgstr ""

#: cinder/exception.py:608
#, python-format
msgid "Invalid backup: %(reason)s"
msgstr ""

#: cinder/exception.py:612
msgid "Connection to swift failed"
msgstr ""

#: cinder/exception.py:616
#, python-format
msgid "Transfer %(transfer_id)s could not be found."
msgstr ""

#: cinder/exception.py:620
msgid "Volume migration failed"
msgstr ""

#: cinder/exception.py:624
#, python-format
msgid "Connect to volume via protocol %(protocol)s not supported."
msgstr ""

#: cinder/exception.py:628
msgid "SSH command injection detected"
msgstr ""

#: cinder/manager.py:135
msgid "Notifying Schedulers of capabilities ..."
msgstr ""

#: cinder/policy.py:31
msgid "JSON file representing policy"
msgstr ""

#: cinder/policy.py:34
msgid "Rule checked when requested rule is not found"
msgstr ""

#: cinder/quota.py:105
#, python-format
msgid ""
"Default quota for resource: %(res)s is set by the default quota flag: "
"quota_%(res)s, it is now deprecated. Please use the the default quota "
"class for default quota."
msgstr ""

#: cinder/quota.py:801
#, python-format
msgid "Created reservations %s"
msgstr ""

#: cinder/quota.py:823
#, python-format
msgid "Failed to commit reservations %s"
msgstr ""

#: cinder/quota.py:843
#, python-format
msgid "Failed to roll back reservations %s"
msgstr ""

#: cinder/quota.py:930
msgid "Cannot register resource"
msgstr ""

#: cinder/quota.py:933
msgid "Cannot register resources"
msgstr ""

#: cinder/service.py:125
msgid "SIGTERM received"
msgstr ""

#: cinder/service.py:175 cinder/openstack/common/service.py:165
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: cinder/service.py:214 cinder/openstack/common/service.py:201
msgid "Forking too fast, sleeping"
msgstr ""

#: cinder/service.py:232 cinder/openstack/common/service.py:122
#: cinder/openstack/common/service.py:219
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: cinder/service.py:237 cinder/openstack/common/service.py:224
msgid "Unhandled exception"
msgstr ""

#: cinder/service.py:244 cinder/openstack/common/service.py:231
#, python-format
msgid "Started child %d"
msgstr ""

#: cinder/service.py:254 cinder/openstack/common/service.py:241
#, python-format
msgid "Starting %d workers"
msgstr ""

#: cinder/service.py:273 cinder/openstack/common/service.py:258
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: cinder/service.py:277
#, python-format
msgid "Child %(pid)d exited with status %(code)d"
msgstr ""

#: cinder/service.py:281 cinder/openstack/common/service.py:266
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: cinder/service.py:289
#, python-format
msgid "_wait_child %d"
msgstr ""

#: cinder/service.py:305
#, python-format
msgid "wait wrap.failed %s"
msgstr ""

#: cinder/service.py:313 cinder/openstack/common/service.py:294
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: cinder/service.py:324 cinder/openstack/common/service.py:305
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: cinder/service.py:357
#, python-format
msgid "Starting %(topic)s node (version %(version_string)s)"
msgstr ""

#: cinder/service.py:371 cinder/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: cinder/service.py:462
msgid "Service killed that has no database entry"
msgstr ""

#: cinder/service.py:499
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: cinder/service.py:514
msgid "Recovered model server connection!"
msgstr ""

#: cinder/service.py:520
msgid "model server went away"
msgstr ""

#: cinder/service.py:612 cinder/openstack/common/service.py:113
#: cinder/openstack/common/service.py:276
msgid "Full set of CONF:"
msgstr ""

#: cinder/service.py:619
#, python-format
msgid "%s : FLAG SET "
msgstr ""

#: cinder/utils.py:90
#, python-format
msgid "Fetching %s"
msgstr ""

#: cinder/utils.py:158 cinder/openstack/common/processutils.py:218
#: cinder/volume/drivers/san/hp/hp_3par_common.py:303
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: cinder/utils.py:160 cinder/openstack/common/processutils.py:220
msgid "Environment not supported over SSH"
msgstr ""

#: cinder/utils.py:164 cinder/openstack/common/processutils.py:224
msgid "process_input not supported over SSH"
msgstr ""

#: cinder/utils.py:184 cinder/openstack/common/processutils.py:167
#: cinder/openstack/common/processutils.py:239
#: cinder/volume/drivers/san/hp/hp_3par_common.py:330
#, python-format
msgid "Result was %s"
msgstr ""

#: cinder/utils.py:233 cinder/volume/drivers/huawei/huawei_iscsi.py:95
msgid "Specify a password or private_key"
msgstr ""

#: cinder/utils.py:249 cinder/volume/drivers/huawei/huawei_iscsi.py:103
#, python-format
msgid "Error connecting via ssh: %s"
msgstr ""

#: cinder/utils.py:284
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: cinder/utils.py:444
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: cinder/utils.py:447
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: cinder/utils.py:482
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: cinder/utils.py:493
#, python-format
msgid "backend %s"
msgstr ""

#: cinder/utils.py:543
msgid "in looping call"
msgstr ""

#: cinder/utils.py:713
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: cinder/utils.py:804
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr ""

#: cinder/utils.py:982
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: cinder/wsgi.py:121
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: cinder/wsgi.py:124
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: cinder/wsgi.py:127
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: cinder/wsgi.py:130
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: cinder/wsgi.py:163
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: cinder/wsgi.py:207
#, python-format
msgid "Started %(name)s on %(_host)s:%(_port)s"
msgstr ""

#: cinder/wsgi.py:226
msgid "Stopping WSGI server."
msgstr ""

#: cinder/wsgi.py:240
msgid "WSGI server has stopped."
msgstr ""

#: cinder/wsgi.py:309
msgid "You must implement __call__"
msgstr ""

#: cinder/api/auth.py:26
msgid ""
"cinder.api.auth:CinderKeystoneContext is deprecated. Please use "
"cinder.api.middleware.auth:CinderKeystoneContext instead."
msgstr ""

#: cinder/api/auth.py:34
msgid ""
"cinder.api.auth:pipeline_factory is deprecated. Please use "
"cinder.api.middleware.auth:pipeline_factory instead."
msgstr ""

#: cinder/api/common.py:78 cinder/api/common.py:112 cinder/volume/api.py:435
msgid "limit param must be an integer"
msgstr ""

#: cinder/api/common.py:81 cinder/api/common.py:116 cinder/volume/api.py:432
msgid "limit param must be positive"
msgstr ""

#: cinder/api/common.py:106
msgid "offset param must be an integer"
msgstr ""

#: cinder/api/common.py:120
msgid "offset param must be positive"
msgstr ""

#: cinder/api/common.py:148
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: cinder/api/common.py:175
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: cinder/api/extensions.py:184
msgid "Initializing extension manager."
msgstr ""

#: cinder/api/extensions.py:199
#, python-format
msgid "Loaded extension: %s"
msgstr ""

#: cinder/api/extensions.py:237
#, python-format
msgid "Ext name: %s"
msgstr ""

#: cinder/api/extensions.py:238
#, python-format
msgid "Ext alias: %s"
msgstr ""

#: cinder/api/extensions.py:239
#, python-format
msgid "Ext description: %s"
msgstr ""

#: cinder/api/extensions.py:241
#, python-format
msgid "Ext namespace: %s"
msgstr ""

#: cinder/api/extensions.py:242
#, python-format
msgid "Ext updated: %s"
msgstr ""

#: cinder/api/extensions.py:244
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: cinder/api/extensions.py:258
#, python-format
msgid "Loading extension %s"
msgstr ""

#: cinder/api/extensions.py:264
#, python-format
msgid "Calling extension factory %s"
msgstr ""

#: cinder/api/extensions.py:278
#, python-format
msgid "osapi_volume_extension is set to deprecated path: %s"
msgstr ""

#: cinder/api/extensions.py:280
#, python-format
msgid ""
"Please set your flag or cinder.conf settings for osapi_volume_extension "
"to: %s"
msgstr ""

#: cinder/api/extensions.py:289
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:358
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:383
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/sizelimit.py:25
msgid ""
"cinder.api.sizelimit:RequestBodySizeLimiter is deprecated. Please use "
"cinder.api.middleware.sizelimit:RequestBodySizeLimiter instead"
msgstr ""

#: cinder/api/xmlutil.py:268
msgid "element is not a child"
msgstr ""

#: cinder/api/xmlutil.py:417
msgid "root element selecting a list"
msgstr ""

#: cinder/api/xmlutil.py:740
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: cinder/api/xmlutil.py:861
msgid "subclasses must implement construct()!"
msgstr ""

#: cinder/api/contrib/admin_actions.py:80
#, python-format
msgid "Updating %(resource)s '%(id)s' with '%(update)r'"
msgstr ""

#: cinder/api/contrib/backups.py:128
#, python-format
msgid "show called for member %s"
msgstr ""

#: cinder/api/contrib/backups.py:140
#, python-format
msgid "delete called for member %s"
msgstr ""

#: cinder/api/contrib/backups.py:143
#, python-format
msgid "Delete backup with id: %s"
msgstr ""

#: cinder/api/contrib/backups.py:185
#, python-format
msgid "Creating new backup %s"
msgstr ""

#: cinder/api/contrib/backups.py:195 cinder/api/contrib/backups.py:234
#: cinder/api/contrib/volume_transfer.py:159
#: cinder/api/contrib/volume_transfer.py:195
msgid "Incorrect request body format"
msgstr ""

#: cinder/api/contrib/backups.py:201
#, python-format
msgid "Creating backup of volume %(volume_id)s in container %(container)s"
msgstr ""

#: cinder/api/contrib/backups.py:224
#, python-format
msgid "Restoring backup %(backup_id)s (%(body)s)"
msgstr ""

#: cinder/api/contrib/backups.py:238
#, python-format
msgid "Restoring backup %(backup_id)s to volume %(volume_id)s"
msgstr ""

#: cinder/api/contrib/extended_snapshot_attributes.py:60
msgid "Snapshot not found."
msgstr ""

#: cinder/api/contrib/hosts.py:86 cinder/api/openstack/wsgi.py:158
msgid "cannot understand XML"
msgstr ""

#: cinder/api/contrib/hosts.py:136
#, python-format
msgid "Host '%s' could not be found."
msgstr ""

#: cinder/api/contrib/hosts.py:165
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: cinder/api/contrib/hosts.py:168
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: cinder/api/contrib/hosts.py:180
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr ""

#: cinder/api/contrib/hosts.py:206
msgid "Describe-resource is admin only functionality"
msgstr ""

#: cinder/api/contrib/hosts.py:214
msgid "Host not found"
msgstr ""

#: cinder/api/contrib/quotas.py:63
msgid "Quota limit must be -1 or greater."
msgstr ""

#: cinder/api/contrib/scheduler_hints.py:38
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: cinder/api/contrib/services.py:85
msgid ""
"Query by service parameter is deprecated. Please use binary parameter "
"instead."
msgstr ""

#: cinder/api/contrib/types_extra_specs.py:102
msgid "Request body empty"
msgstr ""

#: cinder/api/contrib/types_extra_specs.py:106
#: cinder/api/v1/snapshot_metadata.py:77 cinder/api/v1/volume_metadata.py:77
#: cinder/api/v2/snapshot_metadata.py:77
msgid "Request body and URI mismatch"
msgstr ""

#: cinder/api/contrib/types_extra_specs.py:109
#: cinder/api/v1/snapshot_metadata.py:81 cinder/api/v1/volume_metadata.py:81
#: cinder/api/v2/snapshot_metadata.py:81
msgid "Request body contains too many items"
msgstr ""

#: cinder/api/contrib/volume_actions.py:90
#, python-format
msgid ""
"Invalid request to attach volume to an instance %(instance_uuid)s and a "
"host %(host_name)s simultaneously"
msgstr ""

#: cinder/api/contrib/volume_actions.py:98
msgid "Invalid request to attach volume to an invalid target"
msgstr ""

#: cinder/api/contrib/volume_actions.py:175
msgid "Invalid request body"
msgstr ""

#: cinder/api/contrib/volume_actions.py:179
msgid "No image_name was specified in request."
msgstr ""

#: cinder/api/contrib/volume_actions.py:215
msgid "New volume size must be specified as an integer."
msgstr ""

#: cinder/api/contrib/volume_transfer.py:133
msgid "Listing volume transfers"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:149
#, python-format
msgid "Creating new volume transfer %s"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:164
#, python-format
msgid "Creating transfer of volume %s"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:185
#, python-format
msgid "Accepting volume transfer %s"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:198
#, python-format
msgid "Accepting transfer %s"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:219
#, python-format
msgid "Delete transfer with id: %s"
msgstr ""

#: cinder/api/middleware/fault.py:45
#, python-format
msgid "Caught error: %s"
msgstr ""

#: cinder/api/middleware/fault.py:54 cinder/api/openstack/wsgi.py:895
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: cinder/api/middleware/sizelimit.py:56 cinder/api/middleware/sizelimit.py:65
#: cinder/api/middleware/sizelimit.py:79
msgid "Request is too large."
msgstr ""

#: cinder/api/openstack/__init__.py:73
msgid "Must specify an ExtensionManager class"
msgstr ""

#: cinder/api/openstack/__init__.py:84
#, python-format
msgid "Extended resource: %s"
msgstr ""

#: cinder/api/openstack/__init__.py:108
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr ""

#: cinder/api/openstack/__init__.py:130
msgid ""
"cinder.api.openstack:FaultWrapper is deprecated. Please use "
"cinder.api.middleware.fault:FaultWrapper instead."
msgstr ""

#: cinder/api/openstack/urlmap.py:25
msgid ""
"cinder.api.openstack.urlmap:urlmap_factory is deprecated. Please use "
"cinder.api.urlmap:urlmap_factory instead."
msgstr ""

#: cinder/api/openstack/wsgi.py:134 cinder/api/openstack/wsgi.py:546
msgid "cannot understand JSON"
msgstr ""

#: cinder/api/openstack/wsgi.py:551
msgid "too many body keys"
msgstr ""

#: cinder/api/openstack/wsgi.py:590
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:595
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:598
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:706
msgid "Unrecognized Content-Type provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:710
msgid "No Content-Type provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:714
msgid "Empty body provided in request"
msgstr ""

#: cinder/api/openstack/wsgi.py:825
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: cinder/api/openstack/wsgi.py:828 cinder/api/openstack/wsgi.py:841
#: cinder/api/v1/snapshot_metadata.py:55 cinder/api/v1/snapshot_metadata.py:73
#: cinder/api/v1/snapshot_metadata.py:98 cinder/api/v1/snapshot_metadata.py:123
#: cinder/api/v1/volume_metadata.py:55 cinder/api/v1/volume_metadata.py:73
#: cinder/api/v1/volume_metadata.py:98 cinder/api/v1/volume_metadata.py:123
#: cinder/api/v2/snapshot_metadata.py:55 cinder/api/v2/snapshot_metadata.py:73
#: cinder/api/v2/snapshot_metadata.py:98 cinder/api/v2/snapshot_metadata.py:123
msgid "Malformed request body"
msgstr ""

#: cinder/api/openstack/wsgi.py:838
msgid "Unsupported Content-Type"
msgstr ""

#: cinder/api/openstack/wsgi.py:850
msgid "Malformed request url"
msgstr ""

#: cinder/api/openstack/wsgi.py:898
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: cinder/api/openstack/volume/__init__.py:25
msgid ""
"cinder.api.openstack.volume:APIRouter is deprecated. Please use "
"cinder.api.v1.router:APIRouter instead."
msgstr ""

#: cinder/api/openstack/volume/versions.py:26
msgid ""
"cinder.api.openstack.volume.versions.Versions is deprecated. Please use "
"cinder.api.versions.Versions instead."
msgstr ""

#: cinder/api/v1/limits.py:144 cinder/api/v2/limits.py:144
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: cinder/api/v1/limits.py:270 cinder/api/v2/limits.py:270
msgid "This request was rate-limited."
msgstr ""

#: cinder/api/v1/snapshot_metadata.py:39 cinder/api/v1/snapshot_metadata.py:119
#: cinder/api/v1/snapshot_metadata.py:158 cinder/api/v2/snapshot_metadata.py:39
#: cinder/api/v2/snapshot_metadata.py:119
#: cinder/api/v2/snapshot_metadata.py:158
msgid "snapshot does not exist"
msgstr ""

#: cinder/api/v1/snapshot_metadata.py:141
#: cinder/api/v1/snapshot_metadata.py:151 cinder/api/v1/volume_metadata.py:141
#: cinder/api/v1/volume_metadata.py:151 cinder/api/v2/snapshot_metadata.py:141
#: cinder/api/v2/snapshot_metadata.py:151
msgid "Metadata item was not found"
msgstr ""

#: cinder/api/v1/snapshots.py:119 cinder/api/v2/snapshots.py:119
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: cinder/api/v1/snapshots.py:173 cinder/api/v2/snapshots.py:179
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: cinder/api/v1/snapshots.py:177 cinder/api/v2/snapshots.py:188
#, python-format
msgid "Invalid value '%s' for force. "
msgstr ""

#: cinder/api/v1/volume_metadata.py:39 cinder/api/v1/volume_metadata.py:119
#: cinder/api/v1/volume_metadata.py:158
msgid "volume does not exist"
msgstr ""

#: cinder/api/v1/volumes.py:105
#, python-format
msgid "vol=%s"
msgstr ""

#: cinder/api/v1/volumes.py:233 cinder/api/v2/volumes.py:176
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: cinder/api/v1/volumes.py:280 cinder/api/v1/volumes.py:284
#: cinder/api/v2/volumes.py:238 cinder/api/v2/volumes.py:242
msgid "Invalid imageRef provided."
msgstr ""

#: cinder/api/v1/volumes.py:342 cinder/api/v2/volumes.py:302
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: cinder/api/v1/volumes.py:422
#, python-format
msgid "Removing options '%(bad_options)s' from query"
msgstr ""

#: cinder/api/v2/volumes.py:390
#, python-format
msgid "Removing options '%s' from query"
msgstr ""

#: cinder/backup/api.py:68
msgid "Backup status must be available or error"
msgstr ""

#: cinder/backup/api.py:109
msgid "Volume to be backed up must be available"
msgstr ""

#: cinder/backup/api.py:146
msgid "Backup status must be available"
msgstr ""

#: cinder/backup/api.py:151
msgid "Backup to be restored has invalid size"
msgstr ""

#: cinder/backup/api.py:160
#, python-format
msgid "Creating volume of %(size)s GB for restore of backup %(backup_id)s"
msgstr ""

#: cinder/backup/api.py:176
#, python-format
msgid ""
"volume size %(volume_size)d is too small to restore backup of size "
"%(size)d."
msgstr ""

#: cinder/backup/api.py:182
msgid "Volume to be restored to must be available"
msgstr ""

#: cinder/backup/api.py:188
msgid "Volume to be restored to is smaller than the backup to be restored"
msgstr ""

#: cinder/backup/api.py:192
#, python-format
msgid "Overwriting volume %(volume_id)s with restore of backup %(backup_id)s"
msgstr ""

#: cinder/backup/manager.py:101
msgid "Cleaning up incomplete backup operations"
msgstr ""

#: cinder/backup/manager.py:105
#, python-format
msgid "Resetting volume %s to available (was backing-up)"
msgstr ""

#: cinder/backup/manager.py:109
#, python-format
msgid "Resetting volume %s to error_restoring (was restoring-backup)"
msgstr ""

#: cinder/backup/manager.py:120
#, python-format
msgid "Resetting backup %s to error (was creating)"
msgstr ""

#: cinder/backup/manager.py:126
#, python-format
msgid "Resetting backup %s to available (was restoring)"
msgstr ""

#: cinder/backup/manager.py:131
#, python-format
msgid "Resuming delete on backup: %s"
msgstr ""

#: cinder/backup/manager.py:141
#, python-format
msgid "create_backup started, backup: %(backup_id)s for volume: %(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:151
#, python-format
msgid ""
"create_backup aborted, expected volume status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:163
#, python-format
msgid ""
"create_backup aborted, expected backup status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:189
#, python-format
msgid "create_backup finished. backup: %s"
msgstr ""

#: cinder/backup/manager.py:195
#, python-format
msgid ""
"restore_backup started, restoring backup: %(backup_id)s to volume: "
"%(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:205
#, python-format
msgid ""
"restore_backup aborted, expected volume status %(expected_status)s but "
"got %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:216
#, python-format
msgid ""
"restore_backup aborted, expected backup status %(expected_status)s but "
"got %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:235
#, python-format
msgid ""
"restore_backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to "
"create this backup [%(backup_service)s]"
msgstr ""

#: cinder/backup/manager.py:259
#, python-format
msgid ""
"restore_backup finished, backup: %(backup_id)s restored to volume: "
"%(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:268
#, python-format
msgid "delete_backup started, backup: %s"
msgstr ""

#: cinder/backup/manager.py:274
#, python-format
msgid ""
"delete_backup aborted, expected backup status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:287
#, python-format
msgid ""
"delete_backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to "
"create this backup [%(backup_service)s]"
msgstr ""

#: cinder/backup/manager.py:310
#, python-format
msgid "delete_backup finished, backup %s deleted"
msgstr ""

#: cinder/backup/drivers/ceph.py:110
msgid ""
"rbd striping not supported - ignoring configuration settings for rbd "
"striping"
msgstr ""

#: cinder/backup/drivers/ceph.py:141
#, python-format
msgid "invalid user '%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:207
msgid "backup_id required"
msgstr ""

#: cinder/backup/drivers/ceph.py:213
#, python-format
msgid "transferring data between '%(src)s' and '%(dest)s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:217
#, python-format
msgid "%(chunks)s chunks of %(bytes)s bytes to be transferred"
msgstr ""

#: cinder/backup/drivers/ceph.py:227
#, python-format
msgid "transferred chunk %(chunk)s of %(chunks)s (%(rate)dK/s)"
msgstr ""

#: cinder/backup/drivers/ceph.py:237
#, python-format
msgid "transferring remaining %s bytes"
msgstr ""

#: cinder/backup/drivers/ceph.py:249
#, python-format
msgid "creating base image '%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:274 cinder/backup/drivers/ceph.py:517
#, python-format
msgid "deleting backup snapshot='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:277
msgid "no backup snapshot to delete"
msgstr ""

#: cinder/backup/drivers/ceph.py:314
#, python-format
msgid "trying diff format name format basename='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:322
#, python-format
msgid "image %s not found"
msgstr ""

#: cinder/backup/drivers/ceph.py:330
#, python-format
msgid "base image still has %s snapshots so not deleting base image"
msgstr ""

#: cinder/backup/drivers/ceph.py:335
#, python-format
msgid "deleting base image='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:342
#, python-format
msgid "image busy, retrying %(retries)s more time(s) in %(delay)ss"
msgstr ""

#: cinder/backup/drivers/ceph.py:347
msgid "max retries reached - raising error"
msgstr ""

#: cinder/backup/drivers/ceph.py:350
#, python-format
msgid "base backup image='%s' deleted)"
msgstr ""

#: cinder/backup/drivers/ceph.py:365
#, python-format
msgid "performing differential transfer from '%(src)s' to '%(dest)s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:387
#, python-format
msgid "rbd export-diff failed - %s"
msgstr ""

#: cinder/backup/drivers/ceph.py:395
#, python-format
msgid "rbd import-diff failed - %s"
msgstr ""

#: cinder/backup/drivers/ceph.py:403
#, python-format
msgid "image '%s' not found - trying diff format name"
msgstr ""

#: cinder/backup/drivers/ceph.py:408
#, python-format
msgid "diff format image '%s' not found"
msgstr ""

#: cinder/backup/drivers/ceph.py:443
#, python-format
msgid "using --from-snap '%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:470
#, python-format
msgid ""
"snap='%(snap)s' does not exist in base image='%(base)s' - aborting "
"incremental backup"
msgstr ""

#: cinder/backup/drivers/ceph.py:480
#, python-format
msgid "creating backup snapshot='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:500
#, python-format
msgid "differential backup transfer completed in %.4fs"
msgstr ""

#: cinder/backup/drivers/ceph.py:509
msgid "differential backup transfer failed"
msgstr ""

#: cinder/backup/drivers/ceph.py:539
#, python-format
msgid "creating base image='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:548
msgid "copying data"
msgstr ""

#: cinder/backup/drivers/ceph.py:608
#, python-format
msgid "looking for snapshot of backup base '%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:611
#, python-format
msgid "backup base '%s' has no snapshots"
msgstr ""

#: cinder/backup/drivers/ceph.py:618
#, python-format
msgid "backup '%s' has no snapshot"
msgstr ""

#: cinder/backup/drivers/ceph.py:622
#, python-format
msgid "backup should only have one snapshot but instead has %s"
msgstr ""

#: cinder/backup/drivers/ceph.py:627
#, python-format
msgid "found snapshot '%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:664
#, python-format
msgid "Starting backup of volume='%s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:677
msgid "forcing full backup"
msgstr ""

#: cinder/backup/drivers/ceph.py:689
#, python-format
msgid "backup '%s' finished."
msgstr ""

#: cinder/backup/drivers/ceph.py:727
#, python-format
msgid "trying incremental restore from base='%(base)s' snap='%(snap)s'"
msgstr ""

#: cinder/backup/drivers/ceph.py:739
msgid "differential restore failed, trying full restore"
msgstr ""

#: cinder/backup/drivers/ceph.py:743
#, python-format
msgid "restore transfer completed in %.4fs"
msgstr ""

#: cinder/backup/drivers/ceph.py:837
#, python-format
msgid "no restore point found for backup='%s', forcing full copy"
msgstr ""

#: cinder/backup/drivers/ceph.py:863
msgid "forcing full restore"
msgstr ""

#: cinder/backup/drivers/ceph.py:876
#, python-format
msgid "starting restore from Ceph backup=%(src)s to volume=%(dest)s"
msgstr ""

#: cinder/backup/drivers/ceph.py:890
msgid "volume_file does not support fileno() so skipping fsync()"
msgstr ""

#: cinder/backup/drivers/ceph.py:895
msgid "restore finished."
msgstr ""

#: cinder/backup/drivers/ceph.py:897
#, python-format
msgid "restore finished with error - %s"
msgstr ""

#: cinder/backup/drivers/ceph.py:903
#, python-format
msgid "delete started for backup=%s"
msgstr ""

#: cinder/backup/drivers/ceph.py:908
msgid "rbd image not found but continuing anyway so that db entry can be removed"
msgstr ""

#: cinder/backup/drivers/ceph.py:911
#, python-format
msgid "delete '%s' finished with warning"
msgstr ""

#: cinder/backup/drivers/ceph.py:913
#, python-format
msgid "delete '%s' finished"
msgstr ""

#: cinder/backup/drivers/swift.py:105
#, python-format
msgid "unsupported compression algorithm: %s"
msgstr ""

#: cinder/backup/drivers/swift.py:122
#, python-format
msgid "single_user auth mode enabled, but %(param)s not set"
msgstr ""

#: cinder/backup/drivers/swift.py:140
#, python-format
msgid "_check_container_exists: container: %s"
msgstr ""

#: cinder/backup/drivers/swift.py:145
#, python-format
msgid "container %s does not exist"
msgstr ""

#: cinder/backup/drivers/swift.py:150
#, python-format
msgid "container %s exists"
msgstr ""

#: cinder/backup/drivers/swift.py:156
#, python-format
msgid "_create_container started, container: %(container)s,backup: %(backup_id)s"
msgstr ""

#: cinder/backup/drivers/swift.py:172
#, python-format
msgid "_generate_swift_object_name_prefix: %s"
msgstr ""

#: cinder/backup/drivers/swift.py:181
#, python-format
msgid "generated object list: %s"
msgstr ""

#: cinder/backup/drivers/swift.py:191
#, python-format
msgid ""
"_write_metadata started, container name: %(container)s, metadata "
"filename: %(filename)s"
msgstr ""

#: cinder/backup/drivers/swift.py:208
#, python-format
msgid ""
"error writing metadata file to swift, MD5 of metadata file in swift "
"[%(etag)s] is not the same as MD5 of metadata file sent to swift "
"[%(md5)s]"
msgstr ""

#: cinder/backup/drivers/swift.py:213
msgid "_write_metadata finished"
msgstr ""

#: cinder/backup/drivers/swift.py:218
#, python-format
msgid ""
"_read_metadata started, container name: %(container)s, metadata filename:"
" %(filename)s"
msgstr ""

#: cinder/backup/drivers/swift.py:223
#, python-format
msgid "_read_metadata finished (%s)"
msgstr ""

#: cinder/backup/drivers/swift.py:233
#, python-format
msgid "volume size %d is invalid."
msgstr ""

#: cinder/backup/drivers/swift.py:247
#, python-format
msgid ""
"starting backup of volume: %(volume_id)s to swift, volume size: "
"%(volume_size_bytes)d, swift object names prefix %(object_prefix)s, "
"availability zone: %(availability_zone)s"
msgstr ""

#: cinder/backup/drivers/swift.py:270
msgid "reading chunk of data from volume"
msgstr ""

#: cinder/backup/drivers/swift.py:277
#, python-format
msgid ""
"compressed %(data_size_bytes)d bytes of data to %(comp_size_bytes)d bytes"
" using %(algorithm)s"
msgstr ""

#: cinder/backup/drivers/swift.py:286
msgid "not compressing data"
msgstr ""

#: cinder/backup/drivers/swift.py:290
msgid "About to put_object"
msgstr ""

#: cinder/backup/drivers/swift.py:296
#, python-format
msgid "swift MD5 for %(object_name)s: %(etag)s"
msgstr ""

#: cinder/backup/drivers/swift.py:300
#, python-format
msgid "backup MD5 for %(object_name)s: %(md5)s"
msgstr ""

#: cinder/backup/drivers/swift.py:303
#, python-format
msgid ""
"error writing object to swift, MD5 of object in swift %(etag)s is not the"
" same as MD5 of object sent to swift %(md5)s"
msgstr ""

#: cinder/backup/drivers/swift.py:311
msgid "Calling eventlet.sleep(0)"
msgstr ""

#: cinder/backup/drivers/swift.py:327
#, python-format
msgid "backup %s finished."
msgstr ""

#: cinder/backup/drivers/swift.py:344
#, python-format
msgid "v1 swift volume backup restore of %s started"
msgstr ""

#: cinder/backup/drivers/swift.py:349
#, python-format
msgid "metadata_object_names = %s"
msgstr ""

#: cinder/backup/drivers/swift.py:355
msgid ""
"restore_backup aborted, actual swift object list in swift does not match "
"object list stored in metadata"
msgstr ""

#: cinder/backup/drivers/swift.py:361
#, python-format
msgid ""
"restoring object from swift. backup: %(backup_id)s, container: "
"%(container)s, swift object name: %(object_name)s, volume: %(volume_id)s"
msgstr ""

#: cinder/backup/drivers/swift.py:377
#, python-format
msgid "decompressing data using %s algorithm"
msgstr ""

#: cinder/backup/drivers/swift.py:400
#, python-format
msgid "v1 swift volume backup restore of %s finished"
msgstr ""

#: cinder/backup/drivers/swift.py:408
#, python-format
msgid ""
"starting restore of backup %(object_prefix)s from swift container: "
"%(container)s, to volume %(volume_id)s, backup: %(backup_id)s"
msgstr ""

#: cinder/backup/drivers/swift.py:422
#, python-format
msgid "Restoring swift backup version %s"
msgstr ""

#: cinder/backup/drivers/swift.py:427
#, python-format
msgid "No support to restore swift backup version %s"
msgstr ""

#: cinder/backup/drivers/swift.py:431
#, python-format
msgid "restore %(backup_id)s to %(volume_id)s finished."
msgstr ""

#: cinder/backup/drivers/swift.py:445
msgid "swift error while listing objects, continuing with delete"
msgstr ""

#: cinder/backup/drivers/swift.py:454
#, python-format
msgid "swift error while deleting object %s, continuing with delete"
msgstr ""

#: cinder/backup/drivers/swift.py:457
#, python-format
msgid "deleted swift object: %(swift_object_name)s in container: %(container)s"
msgstr ""

#: cinder/backup/drivers/swift.py:467
#, python-format
msgid "delete %s finished"
msgstr ""

#: cinder/brick/exceptions.py:22 cinder/brick/initiator/connector.py:515
msgid "We are unable to locate any Fibre Channel devices"
msgstr ""

#: cinder/brick/exceptions.py:28
msgid "Unable to find a Fibre Channel volume device"
msgstr ""

#: cinder/brick/exceptions.py:34
#, python-format
msgid "Volume device not found at %s"
msgstr ""

#: cinder/brick/initiator/connector.py:91
#, python-format
msgid "Invalid InitiatorConnector protocol specified %(protocol)s"
msgstr ""

#: cinder/brick/initiator/connector.py:104
#, python-format
msgid "Failed to access the device on the path %(path)s: %(error)s %(info)s."
msgstr ""

#: cinder/brick/initiator/connector.py:182
#, python-format
msgid ""
"ISCSI volume not yet found at: %(host_device)s. Will rescan & retry.  Try"
" number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:195
#, python-format
msgid "Found iSCSI node %(host_device)s (after %(tries)s rescans)"
msgstr ""

#: cinder/brick/initiator/connector.py:262
#, python-format
msgid "Could not find the iSCSI Initiator File %s"
msgstr ""

#: cinder/brick/initiator/connector.py:525
#, python-format
msgid "Looking for Fibre Channel dev %(device)s"
msgstr ""

#: cinder/brick/initiator/connector.py:535
msgid "Fibre Channel volume device not found."
msgstr ""

#: cinder/brick/initiator/connector.py:539
#, python-format
msgid "Fibre volume not yet found. Will rescan & retry.  Try number: %(tries)s"
msgstr ""

#: cinder/brick/initiator/connector.py:555
#, python-format
msgid "Found Fibre Channel volume %(name)s (after %(tries)s rescans)"
msgstr ""

#: cinder/brick/initiator/connector.py:564
#, python-format
msgid "Multipath device discovered %(device)s"
msgstr ""

#: cinder/brick/initiator/linuxfc.py:53 cinder/brick/initiator/linuxfc.py:59
msgid "systool is not installed"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:103
#: cinder/brick/initiator/linuxscsi.py:111
#: cinder/brick/initiator/linuxscsi.py:128
#, python-format
msgid "multipath call failed exit (%(code)s)"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:149
#, python-format
msgid "Couldn't find multipath device %(line)s"
msgstr ""

#: cinder/brick/initiator/linuxscsi.py:153
#, python-format
msgid "Found multipath device = %(mdev)s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:155
#, python-format
msgid "Creating iscsi_target for: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:174 cinder/brick/iscsi/iscsi.py:296
#, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:185
#, python-format
msgid ""
"Failed to create iscsi target for volume id:%(vol_id)s. Please ensure "
"your tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:199
#, python-format
msgid "Removing iscsi_target for: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:216
#, python-format
msgid "Failed to remove iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:226 cinder/brick/iscsi/iscsi.py:467
#: cinder/brick/iser/iser.py:208
msgid "valid iqn needed for show_target"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:303
#, python-format
msgid "Removing iscsi_target for volume: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:389
msgid "rtstool is not installed correctly"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:409
#, python-format
msgid "Creating iscsi_target for volume: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:433 cinder/brick/iscsi/iscsi.py:442
#, python-format
msgid "Failed to create iscsi target for volume id:%s."
msgstr ""

#: cinder/brick/iscsi/iscsi.py:449
#, python-format
msgid "Removing iscsi_target: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:459
#, python-format
msgid "Failed to remove iscsi target for volume id:%s."
msgstr ""

#: cinder/brick/iscsi/iscsi.py:488
#, python-format
msgid "Failed to add initiator iqn %s to target"
msgstr ""

#: cinder/brick/iser/iser.py:139
#, python-format
msgid "Creating iser_target for: %s"
msgstr ""

#: cinder/brick/iser/iser.py:158
#, python-format
msgid "Failed to create iser target for volume id:%(vol_id)s: %(e)s"
msgstr ""

#: cinder/brick/iser/iser.py:169
#, python-format
msgid ""
"Failed to create iser target for volume id:%(vol_id)s. Please ensure your"
" tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""

#: cinder/brick/iser/iser.py:181
#, python-format
msgid "Removing iser_target for: %s"
msgstr ""

#: cinder/brick/iser/iser.py:198
#, python-format
msgid "Failed to remove iser target for volume id:%(vol_id)s: %(e)s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:36
#, python-format
msgid "Unable to find Volume Group: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:42
#, python-format
msgid "Failed to create Volume Group: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:83
msgid "Error creating Volume Group"
msgstr ""

#: cinder/brick/local_dev/lvm.py:84 cinder/brick/local_dev/lvm.py:376
#: cinder/brick/local_dev/lvm.py:405
#, python-format
msgid "Cmd     :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:85 cinder/brick/local_dev/lvm.py:377
#: cinder/brick/local_dev/lvm.py:406
#, python-format
msgid "StdOut  :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:86 cinder/brick/local_dev/lvm.py:378
#: cinder/brick/local_dev/lvm.py:407
#, python-format
msgid "StdErr  :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:90
#, python-format
msgid "Unable to locate Volume Group %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:296
#, python-format
msgid "Unable to find VG: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:322
msgid ""
"Requested to setup thin provisioning, however current LVM version does "
"not support it."
msgstr ""

#: cinder/brick/local_dev/lvm.py:375
msgid "Error creating Volume"
msgstr ""

#: cinder/brick/local_dev/lvm.py:391
#, python-format
msgid "Unable to find LV: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:404
msgid "Error creating snapshot"
msgstr ""

#: cinder/common/config.py:126
msgid "Deploy v1 of the Cinder API. "
msgstr ""

#: cinder/common/config.py:129
msgid "Deploy v2 of the Cinder API. "
msgstr ""

#: cinder/common/sqlalchemyutils.py:68
#: cinder/openstack/common/db/sqlalchemy/utils.py:72
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/common/sqlalchemyutils.py:116
#: cinder/openstack/common/db/sqlalchemy/utils.py:120
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: cinder/db/sqlalchemy/api.py:67
msgid "Use of empty request context is deprecated"
msgstr ""

#: cinder/db/sqlalchemy/api.py:194
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: cinder/db/sqlalchemy/api.py:849
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:1963
#, python-format
msgid "No backup with id %s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2049
msgid "Volume must be available"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2073
#, python-format
msgid "Volume in unexpected state %s, expected awaiting-transfer"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2096
#, python-format
msgid ""
"Transfer %(transfer_id)s: Volume id %(volume_id)s in unexpected state "
"%(status)s, expected awaiting-transfer"
msgstr ""

#: cinder/db/sqlalchemy/migration.py:72
msgid "version should be an integer"
msgstr ""

#: cinder/db/sqlalchemy/migration.py:99
msgid "Upgrade DB using Essex release first."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/001_cinder_init.py:242
msgid "Exception while creating table."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/001_cinder_init.py:271
msgid "Downgrade from initial Cinder install is unsupported."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:50
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:75
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:106
#: cinder/db/sqlalchemy/migrate_repo/versions/008_add_backup.py:58
#: cinder/db/sqlalchemy/migrate_repo/versions/009_add_snapshot_metadata_table.py:47
#: cinder/db/sqlalchemy/migrate_repo/versions/010_add_transfers_table.py:49
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:118
msgid "quota_classes table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:125
msgid "quota_usages table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:132
msgid "reservations table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/003_glance_metadata.py:62
msgid "Exception while creating table 'volume_glance_metadata'"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/003_glance_metadata.py:77
msgid "volume_glance_metadata table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/008_add_backup.py:70
msgid "backups table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/009_add_snapshot_metadata_table.py:60
msgid "snapshot_metadata table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/010_add_transfers_table.py:62
msgid "transfers table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:33
msgid "migrations table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/015_drop_migrations_table.py:62
#, python-format
msgid "Table |%s| not created"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/016_drop_sm_tables.py:39
#, python-format
msgid "Exception while dropping table %s."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/016_drop_sm_tables.py:99
#, python-format
msgid "Exception while creating table %s."
msgstr ""

#: cinder/image/glance.py:153 cinder/image/glance.py:162
#, python-format
msgid "Error contacting glance server '%(netloc)s' for '%(method)s', %(extra)s."
msgstr ""

#: cinder/image/image_utils.py:120
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: cinder/image/image_utils.py:224 cinder/image/image_utils.py:256
#: cinder/volume/drivers/gpfs.py:511
msgid "'qemu-img info' parsing failed."
msgstr ""

#: cinder/image/image_utils.py:231
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: cinder/image/image_utils.py:263
#, python-format
msgid "fmt=%(fmt)s backed by:%(backing_file)s"
msgstr ""

#: cinder/image/image_utils.py:283
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: cinder/image/image_utils.py:312
#, python-format
msgid "Converted to %(f1)s, but format is now %(f2)s"
msgstr ""

#: cinder/openstack/common/excutils.py:48
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: cinder/openstack/common/fileutils.py:64
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: cinder/openstack/common/lockutils.py:102
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: cinder/openstack/common/lockutils.py:189
#, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/openstack/common/lockutils.py:200
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr ""

#: cinder/openstack/common/lockutils.py:227
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""

#: cinder/openstack/common/lockutils.py:235
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr ""

#: cinder/openstack/common/log.py:244
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: cinder/openstack/common/log.py:336
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: cinder/openstack/common/log.py:386
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: cinder/openstack/common/log.py:556
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: cinder/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: cinder/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: cinder/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: cinder/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: cinder/openstack/common/periodic_task.py:42
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: cinder/openstack/common/periodic_task.py:133
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr ""

#: cinder/openstack/common/periodic_task.py:138
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr ""

#: cinder/openstack/common/periodic_task.py:176
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: cinder/openstack/common/periodic_task.py:184
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: cinder/openstack/common/policy.py:149
#, python-format
msgid ""
"Inheritance-based rules are deprecated; use the default brain instead of "
"%s."
msgstr ""

#: cinder/openstack/common/policy.py:163
#, python-format
msgid "Failed to understand rule %(match)r"
msgstr ""

#: cinder/openstack/common/policy.py:173
#, python-format
msgid "Inheritance-based rules are deprecated; update _check_%s"
msgstr ""

#: cinder/openstack/common/policy.py:180
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: cinder/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: cinder/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: cinder/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: cinder/openstack/common/service.py:262
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: cinder/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: cinder/openstack/common/strutils.py:182
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: cinder/openstack/common/strutils.py:189
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: cinder/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/session.py:487
msgid "DB exception wrapped."
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/session.py:538
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/session.py:610
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/utils.py:33
msgid "Sort key supplied was not valid."
msgstr ""

#: cinder/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: cinder/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: cinder/openstack/common/notifier/api.py:171
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: cinder/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: cinder/openstack/common/notifier/rpc_notifier.py:45
#: cinder/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: cinder/openstack/common/rpc/__init__.py:106
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:200
#, python-format
msgid "no calling threads waiting for msg_id : %s, message : %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:208
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:291
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:337
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:406
#, python-format
msgid "received %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:414
#, python-format
msgid "no method for message: %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:415
#, python-format
msgid "No method for message: %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:443
#: cinder/openstack/common/rpc/impl_zmq.py:286
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:451
#: cinder/openstack/common/rpc/impl_zmq.py:292
msgid "Exception during message handling"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:586
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:589
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:623
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:632
msgid "Making asynchronous fanout cast..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:660
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: cinder/openstack/common/rpc/common.py:74
msgid "An unknown RPC related exception occurred."
msgstr ""

#: cinder/openstack/common/rpc/common.py:104
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: cinder/openstack/common/rpc/common.py:121
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: cinder/openstack/common/rpc/common.py:137
#: cinder/openstack/common/rpc/common.py:138
#: cinder/openstack/common/rpc/common.py:139
msgid "<unknown>"
msgstr ""

#: cinder/openstack/common/rpc/common.py:143
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: cinder/openstack/common/rpc/common.py:147
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: cinder/openstack/common/rpc/common.py:151
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: cinder/openstack/common/rpc/common.py:156
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: cinder/openstack/common/rpc/common.py:280
#, python-format
msgid "Failed to sanitize %(item)s. Key error %(err)s"
msgstr ""

#: cinder/openstack/common/rpc/common.py:302
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:169
#: cinder/openstack/common/rpc/impl_qpid.py:133
msgid "Failed to process message... skipping it."
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:480
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:502
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:539
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:555
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:609
#: cinder/openstack/common/rpc/impl_qpid.py:403
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:627
#: cinder/openstack/common/rpc/impl_qpid.py:418
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:631
#: cinder/openstack/common/rpc/impl_qpid.py:422
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:670
#: cinder/openstack/common/rpc/impl_qpid.py:457
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:351
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:357
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:370
msgid "Re-established AMQP queues"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:430
msgid "Error processing message.  Skipping it."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:97
msgid "JSON serialization failed."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:104
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:140
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:141
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:142
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:150
msgid "Could not open socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:162
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:204
msgid "You cannot recv on this socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:209
msgid "You cannot send on this socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:273
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:311
msgid "Sending reply"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:345
msgid "RPC message did not include method."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:380
msgid "Registering reactor"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:392
msgid "In reactor registered"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:407
msgid "Out reactor registered"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:411
msgid "Consuming socket"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:453
#, python-format
msgid "CONSUMER GOT %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:465
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:471
msgid "Topic contained dangerous characters."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:496
#, python-format
msgid "ROUTER RELAY-OUT SUCCEEDED %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:505
msgid "Topic socket file creation failed."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:510
#, python-format
msgid "ROUTER RELAY-OUT QUEUED %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:513
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:532
#, python-format
msgid "Could not create IPC directory %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:542
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:576
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:578
#, python-format
msgid "ROUTER RELAY-OUT %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:600
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:628
msgid "Skipping topic registration. Already registered."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:635
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:687
msgid "Creating payload"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:700
msgid "Creating queue socket for reply waiter"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:713
msgid "Sending cast"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:716
msgid "Cast sent; Waiting reply"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:719
#, python-format
msgid "Received message: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:720
msgid "Unpacking response"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:729
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:736
msgid "RPC Message Invalid."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:760
#, python-format
msgid "%(msg)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:763
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:767
msgid "No matchmaker results. Not casting."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:770
msgid "No match from matchmaker."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:53
msgid "Match not found by MatchMaker."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:89
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:239
#, python-format
msgid "Matchmaker unregistered: %s, %s"
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:250
msgid "Register before starting heartbeat."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:343
#: cinder/openstack/common/rpc/matchmaker.py:361
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: cinder/scheduler/chance.py:54 cinder/scheduler/simple.py:90
msgid "Is the appropriate service running?"
msgstr ""

#: cinder/scheduler/chance.py:64
msgid "Could not find another host"
msgstr ""

#: cinder/scheduler/chance.py:98 cinder/scheduler/filter_scheduler.py:98
#, python-format
msgid "cannot place volume %(id)s on %(host)s"
msgstr ""

#: cinder/scheduler/driver.py:89
msgid "Must implement host_passes_filters"
msgstr ""

#: cinder/scheduler/driver.py:93
msgid "Must implement a fallback schedule"
msgstr ""

#: cinder/scheduler/driver.py:97
msgid "Must implement schedule_create_volume"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:124
msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:142
#, python-format
msgid ""
"Error scheduling %(volume_id)s from last vol-service: %(last_host)s : "
"%(exc)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:175
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for volume %(volume_id)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:227
#, python-format
msgid "Filtered %s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:240
#, python-format
msgid "Choosing %s"
msgstr ""

#: cinder/scheduler/host_manager.py:240
#, python-format
msgid "Ignoring %(service_name)s service update from %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:245
#, python-format
msgid "Received %(service_name)s service update from %(host)s."
msgstr ""

#: cinder/scheduler/host_manager.py:270
#, python-format
msgid "volume service is down or disabled. (host: %s)"
msgstr ""

#: cinder/scheduler/manager.py:119
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: cinder/scheduler/scheduler_options.py:70
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: cinder/scheduler/scheduler_options.py:80
#, python-format
msgid "Could not decode scheduler options: '%s'"
msgstr ""

#: cinder/scheduler/simple.py:79
msgid "Not enough allocatable volume gigabytes remaining"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:37
msgid "Free capacity not set: volume node info collection broken."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:51
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail): "
"%(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/retry_filter.py:41
#, python-format
msgid "Host %(host)s %(pass_msg)s.  Previously tried hosts: %(hosts)s"
msgstr ""

#: cinder/tests/fake_driver.py:45 cinder/volume/driver.py:636
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: cinder/tests/fake_driver.py:64 cinder/volume/driver.py:911
#, python-format
msgid "FAKE ISER: %s"
msgstr ""

#: cinder/tests/fake_driver.py:112 cinder/tests/fake_driver.py:117
#, python-format
msgid "LoggingVolumeDriver: %s"
msgstr ""

#: cinder/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: cinder/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: cinder/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: cinder/tests/fake_utils.py:99
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: cinder/tests/test_misc.py:59
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:244
#, python-format
msgid "unrecognized argument %s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1241
#, python-format
msgid "Run CLI command: %s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1244
#, python-format
msgid ""
"CLI output:\n"
" stdout: %(stdout)s\n"
" stderr: %(stderr)s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1249
#, python-format
msgid ""
"CLI Exception output:\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/tests/test_volume_types.py:59
#, python-format
msgid "Given data: %s"
msgstr ""

#: cinder/tests/test_volume_types.py:60
#, python-format
msgid "Result data: %s"
msgstr ""

#: cinder/tests/api/contrib/test_backups.py:744
msgid "Invalid input"
msgstr ""

#: cinder/tests/integrated/test_login.py:31
#, python-format
msgid "volume: %s"
msgstr ""

#: cinder/tests/integrated/api/client.py:34
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:44
msgid "Authentication error"
msgstr ""

#: cinder/tests/integrated/api/client.py:52
msgid "Authorization error"
msgstr ""

#: cinder/tests/integrated/api/client.py:60
msgid "Item not found"
msgstr ""

#: cinder/tests/integrated/api/client.py:102
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:105
#, python-format
msgid "Body: %s"
msgstr ""

#: cinder/tests/integrated/api/client.py:123
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:150
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:161
msgid "Unexpected status code"
msgstr ""

#: cinder/tests/integrated/api/client.py:168
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: cinder/transfer/api.py:70
msgid "Volume in unexpected state"
msgstr ""

#: cinder/transfer/api.py:104 cinder/volume/api.py:114 cinder/volume/api.py:535
#: cinder/volume/api.py:863 cinder/volume/manager.py:619
msgid "status must be available"
msgstr ""

#: cinder/transfer/api.py:121
#, python-format
msgid "Failed to create transfer record for %s"
msgstr ""

#: cinder/transfer/api.py:138
#, python-format
msgid "Attempt to transfer %s with invalid auth key."
msgstr ""

#: cinder/transfer/api.py:158 cinder/volume/api.py:213
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/transfer/api.py:167
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/transfer/api.py:181
#, python-format
msgid "Failed to update quota donating volumetransfer id %s"
msgstr ""

#: cinder/transfer/api.py:195
#, python-format
msgid "Volume %s has been transferred."
msgstr ""

#: cinder/volume/api.py:107
msgid "May specify only one of snapshot, imageRef or source volume"
msgstr ""

#: cinder/volume/api.py:119
msgid "Volume size cannot be lesser than the Snapshot size"
msgstr ""

#: cinder/volume/api.py:128
msgid "Unable to clone volumes that are in an error state"
msgstr ""

#: cinder/volume/api.py:134
msgid "Clones currently must be >= original volume size."
msgstr ""

#: cinder/volume/api.py:151
#, python-format
msgid "Volume size '%s' must be an integer and greater than 0"
msgstr ""

#: cinder/volume/api.py:161
msgid "Size of specified image is larger than volume size."
msgstr ""

#: cinder/volume/api.py:165
msgid "Image minDisk size is larger than the volume size."
msgstr ""

#: cinder/volume/api.py:182
msgid "Volume must be in the same availability zone as the snapshot"
msgstr ""

#: cinder/volume/api.py:187
msgid "Volume must be in the same availability zone as the source volume"
msgstr ""

#: cinder/volume/api.py:222
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumesalready consumed)"
msgstr ""

#: cinder/volume/api.py:337
msgid "Availability zone is invalid"
msgstr ""

#: cinder/volume/api.py:382
msgid "Failed to update quota for deleting volume"
msgstr ""

#: cinder/volume/api.py:390
#, python-format
msgid "Volume status must be available or error, but current status is: %s"
msgstr ""

#: cinder/volume/api.py:400
msgid "Volume cannot be deleted while migrating"
msgstr ""

#: cinder/volume/api.py:405
#, python-format
msgid "Volume still has %d dependent snapshots"
msgstr ""

#: cinder/volume/api.py:454 cinder/volume/api.py:518
#: cinder/volume/volume_types.py:69
#, python-format
msgid "Searching by: %s"
msgstr ""

#: cinder/volume/api.py:538
msgid "already attached"
msgstr ""

#: cinder/volume/api.py:545
msgid "status must be in-use to detach"
msgstr ""

#: cinder/volume/api.py:556
msgid "Volume status must be available to reserve"
msgstr ""

#: cinder/volume/api.py:611
msgid "must be available"
msgstr ""

#: cinder/volume/api.py:633
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:642
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)"
msgstr ""

#: cinder/volume/api.py:691
msgid "Volume Snapshot status must be available or error"
msgstr ""

#: cinder/volume/api.py:719
msgid "Metadata property key blank"
msgstr ""

#: cinder/volume/api.py:723
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: cinder/volume/api.py:727
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: cinder/volume/api.py:812
msgid "Volume status must be available/in-use."
msgstr ""

#: cinder/volume/api.py:815
msgid "Volume status is in-use."
msgstr ""

#: cinder/volume/api.py:844
msgid "Volume status must be available to extend."
msgstr ""

#: cinder/volume/api.py:849
#, python-format
msgid ""
"New size for extend must be greater than current size. (current: "
"%(size)s, extended: %(new_size)s)"
msgstr ""

#: cinder/volume/api.py:870
msgid "volume must not have snapshots"
msgstr ""

#: cinder/volume/api.py:883
#, python-format
msgid "No available service named %s"
msgstr ""

#: cinder/volume/api.py:889
msgid "Destination host must be different than current host"
msgstr ""

#: cinder/volume/driver.py:140 cinder/volume/drivers/netapp/nfs.py:154
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: cinder/volume/driver.py:233
#, python-format
msgid "copy_data_between_volumes %(src)s -> %(dest)s."
msgstr ""

#: cinder/volume/driver.py:246 cinder/volume/driver.py:260
#, python-format
msgid "Failed to attach volume %(vol)s"
msgstr ""

#: cinder/volume/driver.py:275
#, python-format
msgid "Failed to copy volume %(src)s to %(dest)d"
msgstr ""

#: cinder/volume/driver.py:288
#, python-format
msgid "copy_image_to_volume %s."
msgstr ""

#: cinder/volume/driver.py:304
#, python-format
msgid "copy_volume_to_image %s."
msgstr ""

#: cinder/volume/driver.py:337 cinder/volume/driver.py:871
#, python-format
msgid "Unable to access the backend storage via the path %(path)s."
msgstr ""

#: cinder/volume/driver.py:376
msgid "Extend volume not implemented"
msgstr ""

#: cinder/volume/driver.py:418 cinder/volume/drivers/emc/emc_smis_iscsi.py:113
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/driver.py:466
#, python-format
msgid "Could not find iSCSI export for volume %s"
msgstr ""

#: cinder/volume/driver.py:470 cinder/volume/drivers/emc/emc_smis_iscsi.py:156
#, python-format
msgid "ISCSI Discovery: Found %s"
msgstr ""

#: cinder/volume/driver.py:563
msgid "The volume driver requires the iSCSI initiator name in the connector."
msgstr ""

#: cinder/volume/driver.py:593 cinder/volume/drivers/lvm.py:584
#: cinder/volume/drivers/lvm.py:904 cinder/volume/drivers/storwize_svc.py:1362
#: cinder/volume/drivers/emc/emc_smis_common.py:857
#: cinder/volume/drivers/emc/emc_smis_iscsi.py:235
#: cinder/volume/drivers/huawei/huawei_iscsi.py:1507
#: cinder/volume/drivers/netapp/iscsi.py:835
#: cinder/volume/drivers/netapp/iscsi.py:1118
#: cinder/volume/drivers/nexenta/volume.py:321
msgid "Updating volume stats"
msgstr ""

#: cinder/volume/driver.py:660
msgid "ISER provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/driver.py:708
#, python-format
msgid "Could not find iSER export for volume %s"
msgstr ""

#: cinder/volume/driver.py:712
#, python-format
msgid "ISER Discovery: Found %s"
msgstr ""

#: cinder/volume/driver.py:774
#, python-format
msgid "Failed to access the device on the path %(path)s: %(error)s."
msgstr ""

#: cinder/volume/driver.py:847
#, python-format
msgid "iSER device not found at %s"
msgstr ""

#: cinder/volume/driver.py:851
#, python-format
msgid ""
"ISER volume not yet found at: %(host_device)s. Will rescan & retry.  Try "
"number: %(tries)s."
msgstr ""

#: cinder/volume/driver.py:864
#, python-format
msgid "Found iSER node %(host_device)s (after %(tries)s rescans)."
msgstr ""

#: cinder/volume/driver.py:881 cinder/volume/manager.py:907
#: cinder/volume/drivers/lvm.py:777
msgid "Updating volume status"
msgstr ""

#: cinder/volume/driver.py:949
msgid "Driver must implement initialize_connection"
msgstr ""

#: cinder/volume/manager.py:126
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:149
#, python-format
msgid "Re-exporting %s volumes"
msgstr ""

#: cinder/volume/manager.py:154
#, python-format
msgid "volume %s stuck in a downloading state"
msgstr ""

#: cinder/volume/manager.py:159
#, python-format
msgid "volume %s: skipping export"
msgstr ""

#: cinder/volume/manager.py:161
msgid "Resuming any in progress delete operations"
msgstr ""

#: cinder/volume/manager.py:164
#, python-format
msgid "Resuming delete on volume: %s"
msgstr ""

#: cinder/volume/manager.py:245
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr ""

#: cinder/volume/manager.py:256
#, python-format
msgid "volume %s: creating from snapshot"
msgstr ""

#: cinder/volume/manager.py:260
#, python-format
msgid "volume %s: creating from existing volume"
msgstr ""

#: cinder/volume/manager.py:264
#, python-format
msgid "volume %s: creating from image"
msgstr ""

#: cinder/volume/manager.py:273
#, python-format
msgid "volume %s: creating"
msgstr ""

#: cinder/volume/manager.py:284
#, python-format
msgid "Setting volume: %s status to error after failed image copy."
msgstr ""

#: cinder/volume/manager.py:309
msgid "Unexpected Error: "
msgstr ""

#: cinder/volume/manager.py:310
#, python-format
msgid ""
"Creating %(volume_id)s %(snapshot_id)s %(image_id)s was rescheduled due "
"to %(reason)s"
msgstr ""

#: cinder/volume/manager.py:331
#, python-format
msgid "volume %s: creating export"
msgstr ""

#: cinder/volume/manager.py:341
#, python-format
msgid "volume %s: create failed"
msgstr ""

#: cinder/volume/manager.py:384
#, python-format
msgid "volume %s: created successfully"
msgstr ""

#: cinder/volume/manager.py:406
#, python-format
msgid "volume %s: Error trying to reschedule create"
msgstr ""

#: cinder/volume/manager.py:419
msgid "Retry info not present, will not reschedule"
msgstr ""

#: cinder/volume/manager.py:423
msgid "No request spec, will not reschedule"
msgstr ""

#: cinder/volume/manager.py:428
#, python-format
msgid "volume %(volume_id)s: re-scheduling %(method)s attempt %(num)d"
msgstr ""

#: cinder/volume/manager.py:457 cinder/volume/manager.py:470
#, python-format
msgid "volume %s: deleting"
msgstr ""

#: cinder/volume/manager.py:463
msgid "volume is not local to this node"
msgstr ""

#: cinder/volume/manager.py:468
#, python-format
msgid "volume %s: removing export"
msgstr ""

#: cinder/volume/manager.py:473
#, python-format
msgid "Cannot delete volume %s: volume is busy"
msgstr ""

#: cinder/volume/manager.py:501
msgid "Failed to update usages deleting volume"
msgstr ""

#: cinder/volume/manager.py:505
#, python-format
msgid "volume %s: deleted successfully"
msgstr ""

#: cinder/volume/manager.py:520
#, python-format
msgid "snapshot %s: creating"
msgstr ""

#: cinder/volume/manager.py:525
#, python-format
msgid "snapshot %(snap_name)s: creating"
msgstr ""

#: cinder/volume/manager.py:544
#, python-format
msgid "snapshot %s: created successfully"
msgstr ""

#: cinder/volume/manager.py:553 cinder/volume/manager.py:558
#, python-format
msgid "snapshot %s: deleting"
msgstr ""

#: cinder/volume/manager.py:561
#, python-format
msgid "Cannot delete snapshot %s: snapshot is busy"
msgstr ""

#: cinder/volume/manager.py:591
msgid "Failed to update usages deleting snapshot"
msgstr ""

#: cinder/volume/manager.py:594
#, python-format
msgid "snapshot %s: deleted successfully"
msgstr ""

#: cinder/volume/manager.py:612
msgid "being attached by another instance"
msgstr ""

#: cinder/volume/manager.py:616
msgid "being attached by another host"
msgstr ""

#: cinder/volume/manager.py:691 cinder/volume/manager.py:696
#, python-format
msgid "Failed to copy image to volume: %(volume_id)s, error: %(error)s"
msgstr ""

#: cinder/volume/manager.py:701
#, python-format
msgid "Downloaded image %(image_id)s to %(volume_id)s successfully."
msgstr ""

#: cinder/volume/manager.py:720
#, python-format
msgid "Uploaded volume %(volume_id)s to image (%(image_id)s) successfully"
msgstr ""

#: cinder/volume/manager.py:811
msgid "failed to create new_volume on destination host"
msgstr ""

#: cinder/volume/manager.py:814
msgid "timeout creating new_volume on destination host"
msgstr ""

#: cinder/volume/manager.py:826
#, python-format
msgid "Failed to copy volume %(vol1)s to %(vol2)s"
msgstr ""

#: cinder/volume/manager.py:835
#, python-format
msgid "Failed to delete migration source vol %(vol)s: %(err)s"
msgstr ""

#: cinder/volume/manager.py:847
#, python-format
msgid "Failed to rename migration destination volume %(vol)s to %(name)s"
msgstr ""

#: cinder/volume/manager.py:860
#, python-format
msgid "volume %s: calling driver migrate_volume"
msgstr ""

#: cinder/volume/manager.py:920
msgid "Clear capabilities"
msgstr ""

#: cinder/volume/manager.py:924
#, python-format
msgid "Notification {%s} received"
msgstr ""

#: cinder/volume/manager.py:962
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to extend volume by %(s_size)sG, "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/manager.py:973
#, python-format
msgid "volume %s: extending"
msgstr ""

#: cinder/volume/manager.py:975
#, python-format
msgid "volume %s: extended successfully"
msgstr ""

#: cinder/volume/manager.py:977
#, python-format
msgid "volume %s: Error trying to extend volume"
msgstr ""

#: cinder/volume/utils.py:155
#, python-format
msgid ""
"Incorrect value error: %(blocksize)s, it may indicate that "
"'volume_dd_blocksize' was configured incorrectly. Fall back to default."
msgstr ""

#: cinder/volume/volume_types.py:45
#, python-format
msgid "DB error: %s"
msgstr ""

#: cinder/volume/volume_types.py:54 cinder/volume/volume_types.py:101
msgid "id cannot be None"
msgstr ""

#: cinder/volume/volume_types.py:113
msgid "name cannot be None"
msgstr ""

#: cinder/volume/volume_types.py:132
#, python-format
msgid ""
"Default volume type is not found, please check default_volume_type "
"config: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:131
#: cinder/volume/drivers/block_device.py:142 cinder/volume/drivers/lvm.py:497
#: cinder/volume/drivers/lvm.py:511
#, python-format
msgid "Skipping remove_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:156 cinder/volume/drivers/lvm.py:529
#, python-format
msgid ""
"Skipping remove_export. No iscsi_target is presently exported for volume:"
" %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:181 cinder/volume/drivers/lvm.py:326
#, python-format
msgid "Skipping ensure_export. No iscsi_target provision for volume: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:198 cinder/volume/drivers/lvm.py:347
#, python-format
msgid "Skipping ensure_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:270 cinder/volume/drivers/lvm.py:181
#, python-format
msgid "Performing secure delete on volume: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:283 cinder/volume/drivers/lvm.py:196
#, python-format
msgid "Error unrecognized volume_clear option: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:305 cinder/volume/drivers/lvm.py:248
#: cinder/volume/drivers/lvm.py:881
#, python-format
msgid "Creating clone of volume: %s"
msgstr ""

#: cinder/volume/drivers/block_device.py:372
msgid "No free disk"
msgstr ""

#: cinder/volume/drivers/block_device.py:385
msgid "No big enough free disk"
msgstr ""

#: cinder/volume/drivers/coraid.py:88
msgid "Running with CoraidDriver for ESM EtherCLoud"
msgstr ""

#: cinder/volume/drivers/coraid.py:99
#, python-format
msgid "Update session cookie %(session)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:105 cinder/volume/drivers/coraid.py:191
#, python-format
msgid "Message : %(message)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:122
#, python-format
msgid "Error while trying to set group: %(message)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:125
#, python-format
msgid "Unable to find group: %(group)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:158
msgid "ESM urlOpen error"
msgstr ""

#: cinder/volume/drivers/coraid.py:163
msgid "JSON Error"
msgstr ""

#: cinder/volume/drivers/coraid.py:167
msgid "Request without URL"
msgstr ""

#: cinder/volume/drivers/coraid.py:183
#, python-format
msgid "Configure data : %s"
msgstr ""

#: cinder/volume/drivers/coraid.py:185
#, python-format
msgid "Configure response : %s"
msgstr ""

#: cinder/volume/drivers/coraid.py:207
#, python-format
msgid "Unable to retrive volume infos for volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:317
msgid "Cannot login on Coraid ESM"
msgstr ""

#: cinder/volume/drivers/coraid.py:336
#, python-format
msgid "Fail to create volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:349
#, python-format
msgid "Failed to delete volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:363
#, python-format
msgid "Failed to Create Snapshot %(snapname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:375
#, python-format
msgid "Failed to Delete Snapshot %(snapname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:393
#, python-format
msgid "Failed to Create Volume from Snapshot %(snapname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:403 cinder/volume/drivers/rbd.py:608
#: cinder/volume/drivers/sheepdog.py:192
#, python-format
msgid "Failed to Extend Volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:424
#, python-format
msgid ""
"Failed to Initialize Connection. Volume Name: %(volname)s Shelf: "
"%(shelf)s, Lun: %(lun)s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:70
#, python-format
msgid "There's no Gluster config file configured (%s)"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:75
#, python-format
msgid "Gluster config file at %(config)s doesn't exist"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:87
msgid "mount.glusterfs is not installed"
msgstr ""

#: cinder/volume/drivers/gpfs.py:91
#, python-format
msgid "GPFS is not active.  Detailed output: %s"
msgstr ""

#: cinder/volume/drivers/gpfs.py:92
#, python-format
msgid "GPFS is not running - state: %s"
msgstr ""

#: cinder/volume/drivers/gpfs.py:135
msgid "Option gpfs_mount_point_base is not set correctly."
msgstr ""

#: cinder/volume/drivers/gpfs.py:142
msgid "Option gpfs_images_share_mode is not set correctly."
msgstr ""

#: cinder/volume/drivers/gpfs.py:148
msgid "Option gpfs_images_dir is not set correctly."
msgstr ""

#: cinder/volume/drivers/gpfs.py:155
#, python-format
msgid ""
"gpfs_images_share_mode is set to copy_on_write, but %(vol)s and %(img)s "
"belong to different file systems"
msgstr ""

#: cinder/volume/drivers/gpfs.py:164
#, python-format
msgid ""
"Downlevel GPFS Cluster Detected.  GPFS Clone feature not enabled in "
"cluster daemon level %(cur)s - must be at least at level %(min)s."
msgstr ""

#: cinder/volume/drivers/gpfs.py:178
#, python-format
msgid "%s must be an absolute path."
msgstr ""

#: cinder/volume/drivers/gpfs.py:183
#, python-format
msgid "%s is not a directory."
msgstr ""

#: cinder/volume/drivers/gpfs.py:191
#, python-format
msgid "%s is not on GPFS. Perhaps GPFS not mounted."
msgstr ""

#: cinder/volume/drivers/gpfs.py:198
#, python-format
msgid ""
"The GPFS filesystem %(fs)s is not at the required release level.  Current"
" level is %(cur)s, must be at least %(min)s."
msgstr ""

#: cinder/volume/drivers/gpfs.py:449
#, python-format
msgid "mkfs failed on volume %(vol)s, error message was: %(err)s"
msgstr ""

#: cinder/volume/drivers/gpfs.py:503
#, python-format
msgid "fmt = %(fmt)s backed by: %(backing_file)s"
msgstr ""

#: cinder/volume/drivers/gpfs.py:525
#, python-format
msgid "Expected image to be in raw format, but is %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:76
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: cinder/volume/drivers/lvm.py:176
#, python-format
msgid "Size for volume: %s not found, skipping secure delete."
msgstr ""

#: cinder/volume/drivers/lvm.py:216
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:361 cinder/volume/drivers/lvm.py:675
msgid "Detected inconsistency in provider_location id"
msgstr ""

#: cinder/volume/drivers/lvm.py:413
#, python-format
msgid "Symbolic link %s not found"
msgstr ""

#: cinder/volume/drivers/lvm.py:610
#, python-format
msgid "Error retrieving volume stats: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:661
#, python-format
msgid "Skipping ensure_export. No iser_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:752
#, python-format
msgid "Skipping remove_export. No iser_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:768
#, python-format
msgid ""
"Skipping remove_export. No iser_target is presently exported for volume: "
"%s"
msgstr ""

#: cinder/volume/drivers/lvm.py:800
#, python-format
msgid "Error retrieving volume status: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:97
#, python-format
msgid "casted to %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:134
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:147
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/nfs.py:234
#, python-format
msgid "Expected volume size was %d"
msgstr ""

#: cinder/volume/drivers/nfs.py:235
#, python-format
msgid " but size is now %d"
msgstr ""

#: cinder/volume/drivers/nfs.py:327
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/nfs.py:361
#, python-format
msgid "There's no NFS config file configured (%s)"
msgstr ""

#: cinder/volume/drivers/nfs.py:366
#, python-format
msgid "NFS config file at %(config)s doesn't exist"
msgstr ""

#: cinder/volume/drivers/nfs.py:371
#, python-format
msgid "NFS config 'nfs_oversub_ratio' invalid.  Must be > 0: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:379
#, python-format
msgid "NFS config 'nfs_used_ratio' invalid.  Must be > 0 and <= 1.0: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:438
#, python-format
msgid "%s is above nfs_used_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:441
#, python-format
msgid "%s is above nfs_oversub_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:444
#, python-format
msgid "%s reserved space is above nfs_oversub_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:460
#, python-format
msgid "Selected %s as target nfs share."
msgstr ""

#: cinder/volume/drivers/rbd.py:170
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:205
#, python-format
msgid "error opening rbd image %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:254
msgid "rados and rbd python libraries not found"
msgstr ""

#: cinder/volume/drivers/rbd.py:260
msgid "error connecting to ceph cluster"
msgstr ""

#: cinder/volume/drivers/rbd.py:335 cinder/volume/drivers/sheepdog.py:175
msgid "error refreshing volume stats"
msgstr ""

#: cinder/volume/drivers/rbd.py:376
#, python-format
msgid "flattening %(pool)s/%(img)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:382
#, python-format
msgid "cloning %(pool)s/%(img)s@%(snap)s to %(dst)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:474
#, python-format
msgid "connection data: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:483
msgid "Not stored in rbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:487
msgid "Blank components"
msgstr ""

#: cinder/volume/drivers/rbd.py:490
msgid "Not an rbd snapshot"
msgstr ""

#: cinder/volume/drivers/rbd.py:502
#, python-format
msgid "not cloneable: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:506
#, python-format
msgid "%s is in a different ceph cluster"
msgstr ""

#: cinder/volume/drivers/rbd.py:518
#, python-format
msgid "Unable to open image %(loc)s: %(err)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:613 cinder/volume/drivers/sheepdog.py:197
msgid "Extend volume from %(old_size) to %(new_size)"
msgstr ""

#: cinder/volume/drivers/scality.py:64
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: cinder/volume/drivers/scality.py:75
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: cinder/volume/drivers/scality.py:81
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: cinder/volume/drivers/scality.py:102
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

#: cinder/volume/drivers/scality.py:136
#, python-format
msgid "Cannot find volume dir for Scality SOFS at '%s'"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:56
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:61
msgid "Sheepdog is not working"
msgstr ""

#: cinder/volume/drivers/solidfire.py:137
#, python-format
msgid "Payload for SolidFire API call: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:144
#, python-format
msgid ""
"Failed to make httplib connection SolidFire Cluster: %s (verify san_ip "
"settings)"
msgstr ""

#: cinder/volume/drivers/solidfire.py:147
#, python-format
msgid "Failed to make httplib connection: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:154
#, python-format
msgid ""
"Request to SolidFire cluster returned bad status: %(status)s / %(reason)s"
" (check san_login/san_password settings)"
msgstr ""

#: cinder/volume/drivers/solidfire.py:159
#, python-format
msgid "HTTP request failed, with status: %(status)s and reason: %(reason)s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:170
#, python-format
msgid "Call to json.loads() raised an exception: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:176
#, python-format
msgid "Results of SolidFire API call: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:180
#, python-format
msgid "Clone operation encountered: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:182
#, python-format
msgid "Waiting for outstanding operation before retrying snapshot: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:188
#, python-format
msgid "Detected xDBVersionMismatch, retry %s of 5"
msgstr ""

#: cinder/volume/drivers/solidfire.py:195
#: cinder/volume/drivers/solidfire.py:262
#: cinder/volume/drivers/solidfire.py:351
#, python-format
msgid "API response: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:215
#, python-format
msgid "Found solidfire account: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:244
#, python-format
msgid "solidfire account: %s does not exist, create it..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:306
#, python-format
msgid "Failed to retrieve volume SolidFire-ID: %s in get_by_account!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:383
msgid "Failed to get model update from clone"
msgstr ""

#: cinder/volume/drivers/solidfire.py:395
#, python-format
msgid "Failed volume create: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:410
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:435
#, python-format
msgid "Failed to get SolidFire Volume: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:444
#, python-format
msgid "Mapped SolidFire volumeID %(sfid)s to cinder ID %(uuid)s."
msgstr ""

#: cinder/volume/drivers/solidfire.py:453
#, python-format
msgid "Volume %s, not found on SF Cluster."
msgstr ""

#: cinder/volume/drivers/solidfire.py:456
#, python-format
msgid "Found %(count)s volumes mapped to id: %(uuid)s."
msgstr ""

#: cinder/volume/drivers/solidfire.py:525
msgid "Enter SolidFire delete_volume..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:529
#, python-format
msgid "Account for Volume ID %s was not found on the SolidFire Cluster!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:531
msgid "This usually means the volume was never succesfully created."
msgstr ""

#: cinder/volume/drivers/solidfire.py:544
#, python-format
msgid "Failed to delete SolidFire Volume: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:547
#: cinder/volume/drivers/solidfire.py:618
#: cinder/volume/drivers/solidfire.py:681
#: cinder/volume/drivers/solidfire.py:706
#, python-format
msgid "Volume ID %s was not found on the SolidFire Cluster!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:550
msgid "Leaving SolidFire delete_volume"
msgstr ""

#: cinder/volume/drivers/solidfire.py:554
msgid "Executing SolidFire ensure_export..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:559
msgid "Executing SolidFire create_export..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:610
msgid "Entering SolidFire extend_volume..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:632
msgid "Leaving SolidFire extend_volume"
msgstr ""

#: cinder/volume/drivers/solidfire.py:637
msgid "Updating cluster status info"
msgstr ""

#: cinder/volume/drivers/solidfire.py:645
msgid "Failed to get updated stats"
msgstr ""

#: cinder/volume/drivers/solidfire.py:675
#: cinder/volume/drivers/solidfire.py:700
msgid "Entering SolidFire attach_volume..."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:177
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:183
msgid "enter: do_setup"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:194
#, python-format
msgid "pool %s doesn't exist"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:210
msgid "Failed to get license information."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:269
msgid "do_setup: No configured nodes"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:271
msgid "leave: do_setup"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:293
msgid "enter: check_for_setup_error"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:299
#: cinder/volume/drivers/netapp/iscsi.py:123
#: cinder/volume/drivers/netapp/nfs.py:221
#: cinder/volume/drivers/san/hp/hp_3par_common.py:143
#, python-format
msgid "%s is not set"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:305
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:313
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:321
msgid "leave: check_for_setup_error"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:335
#, python-format
msgid "ensure_export: Volume %s not found on storage"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:359
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:395
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:418
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:486
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:514
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:526
#, python-format
msgid "enter: _create_host: host %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:541
msgid "_create_host: No connector ports"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:557
#, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:580
#, python-format
msgid "enter: _map_vol_to_host: volume %(volume_name)s to host %(host_name)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:610
msgid ""
"storwize_svc_multihostmap_enabled is set to False, Not allow multi host "
"mapping"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:623
#, python-format
msgid "volume %s mapping to multi host"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:629
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, volume %(volume_name)s, host"
" %(host_name)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:639
#, python-format
msgid "enter: _delete_host: host %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:647
#, python-format
msgid "leave: _delete_host: host %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:673
msgid "The connector does not contain the required information."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:692
#, python-format
msgid "enter: initialize_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:708
msgid "_create_host failed to return the host name."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:719
#, python-format
msgid "initialize_connection: Failed to get attributes for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:726
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:728
#, python-format
msgid "initialize_connection: Missing volume attribute for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:745
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for volume "
"%(vol)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:753
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:786
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:791
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:809
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:819
msgid "_get_host_from_connector failed to return the host name for connector"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:834
#, python-format
msgid ""
"terminate_connection: No mapping of volume %(vol_name)s to host "
"%(host_name)s found"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:842
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:899
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:923
#, python-format
msgid "enter: _create_vdisk: vdisk %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:957
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:962
#, python-format
msgid "leave: _create_vdisk: volume %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:972
#: cinder/volume/drivers/storwize_svc.py:986
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:998
#: cinder/volume/drivers/storwize_svc.py:1008
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1022
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1049
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1060
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1065
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1072
#, python-format
msgid "_prepare_fc_map: %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1079
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1090
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1102
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1110
#, python-format
msgid "enter: _create_copy: snapshot %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1117
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1129
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1139
#, python-format
msgid "leave: _create_copy: snapshot %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1144
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1166
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1174
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1176
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vol)s with %(str)s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1209
#, python-format
msgid "Vdisk %(name)s not involved in mapping %(src)s -> %(tgt)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1255
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1260
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1275
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1300
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1314
msgid "create_cloned_volume: Source and destination size differ."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1327
#, python-format
msgid "enter: extend_volume: volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1331
msgid "extend_volume: Extending a volume with snapshots is not supported."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1342
#, python-format
msgid "leave: extend_volume: volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1379
msgid "_update_volume_stats: Could not get system name"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1391
msgid "Could not get pool data from the storage"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1392
msgid "_update_volume_stats: Could not get storage pool data"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1430
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1436
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1443
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1450
msgid "System does not support compression"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1455
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1461
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1470
msgid ""
"Multipath is currently only supported for FC connections and not iSCSI.  "
"(This is a Nova limitation.)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1482
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1489
#, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1506
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1525
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1533
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1547
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1555
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr ""

#: cinder/volume/drivers/windows.py:141
#, python-format
msgid "Creating folder %s "
msgstr ""

#: cinder/volume/drivers/windows.py:206
#: cinder/volume/drivers/nexenta/volume.py:221
#, python-format
msgid "Ignored target creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/windows.py:212
#, python-format
msgid "Disk not found: %s"
msgstr ""

#: cinder/volume/drivers/zadara.py:218
#, python-format
msgid "Sending %(method)s to %(url)s. Body \"%(body)s\""
msgstr ""

#: cinder/volume/drivers/zadara.py:240
#, python-format
msgid "Operation completed. %(data)s"
msgstr ""

#: cinder/volume/drivers/zadara.py:350
#, python-format
msgid "Volume %(name)s could not be found. It might be already deleted"
msgstr ""

#: cinder/volume/drivers/zadara.py:447
#, python-format
msgid "Attach properties: %(properties)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:41
msgid ""
"Module PyWBEM not installed.  Install PyWBEM using the python-pywbem "
"package."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:77
msgid "Entering create_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:81
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:89
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:96
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s  Storage System: "
"%(storage_system)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:105
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:113
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: 5  Size: %(size)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:128
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:135
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:142
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:150
msgid "Entering create_volume_from_snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:155
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:165
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Snapshot Instance: %(snapshotinstance)s  Storage "
"System: %(storage_system)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:175
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Create Volume from Snapshot is NOT supported on VMAX."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:186
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Cannot find Replication Service to create volume from "
"snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:195
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Method: CreateElementReplica  ReplicationService: "
"%(service)s  ElementName: %(elementname)s  SyncType: 8  SourceElement: "
"%(sourceelement)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:216
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  "
"Snapshot:%(snapshotname)s.  Return code: %(rc)lu.Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:228
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Successfully clone volume from snapshot.  Finding the "
"clone relationship."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:239
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Remove the clone relationship. Method: "
"ModifyReplicaSynchronization ReplicationService: %(service)s  Operation: "
"8  Synchronization: %(sync_name)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:255
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:264
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Return code: %(rc)lu.  Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:276
#, python-format
msgid ""
"Leaving create_volume_from_snapshot: Volume: %(volumename)s Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:285
msgid "Entering create_cloned_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:290
#, python-format
msgid ""
"Create a Clone from Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:300
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Source Instance: %(src_instance)s  Storage System: %(storage_system)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:310
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s. Cannot find Replication Service to create cloned volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:319
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Method: CreateElementReplica  ReplicationService: %(service)s  "
"ElementName: %(elementname)s  SyncType: 8  SourceElement: "
"%(sourceelement)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:340
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source "
"Volume:%(srcname)s.  Return code: %(rc)lu.Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:352
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s."
"  Successfully cloned volume from source volume.  Finding the clone "
"relationship."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:363
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s."
"  Remove the clone relationship. Method: ModifyReplicaSynchronization "
"ReplicationService: %(service)s  Operation: 8  Synchronization: "
"%(sync_name)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:379
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:388
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s.  Return code: %(rc)lu.  Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:400
#, python-format
msgid ""
"Leaving create_cloned_volume: Volume: %(volumename)s Source Volume: "
"%(srcname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:409
msgid "Entering delete_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:411
#, python-format
msgid "Delete Volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:418
#, python-format
msgid "Volume %(name)s not found on the array. No volume to delete."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:428
#, python-format
msgid ""
"Error Delete Volume: %(volumename)s. Storage Configuration Service not "
"found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:436
#, python-format
msgid "Delete Volume: %(name)s  DeviceID: %(deviceid)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:440
#, python-format
msgid ""
"Delete Volume: %(name)s  Method: EMCReturnToStoragePool ConfigServic: "
"%(service)s  TheElement: %(vol_instance)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:454
#, python-format
msgid ""
"Error Delete Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:463
#, python-format
msgid "Leaving delete_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:470
msgid "Entering create_snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:474
#, python-format
msgid "Create snapshot: %(snapshot)s: volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:486
#, python-format
msgid "Device ID: %(deviceid)s: Storage System: %(storagesystem)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:493
#: cinder/volume/drivers/emc/emc_smis_common.py:495
#: cinder/volume/drivers/emc/emc_smis_common.py:565
#, python-format
msgid "Cannot find Replication Service to create snapshot for volume %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:500
#, python-format
msgid ""
"Create Snapshot:  Method: CreateElementReplica: Target: %(snapshot)s  "
"Source: %(volume)s  Replication Service: %(service)s  ElementName: "
"%(elementname)s  Sync Type: 7  SourceElement: %(sourceelement)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:516
#, python-format
msgid ""
"Create Snapshot: Volume: %(volumename)s  Snapshot: %(snapshotname)s  "
"Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:525
#, python-format
msgid ""
"Error Create Snapshot: %(snapshot)s Volume: %(volume)s Error: "
"%(errordesc)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:533
#, python-format
msgid ""
"Leaving create_snapshot: Snapshot: %(snapshot)s Volume: %(volume)s  "
"Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:539
msgid "Entering delete_snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:543
#, python-format
msgid "Delete Snapshot: %(snapshot)s: volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:549
#, python-format
msgid ""
"Delete Snapshot: %(snapshot)s: volume: %(volume)s. Finding "
"StorageSychronization_SV_SV."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:557
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s not found on the array. No "
"snapshot to delete."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:572
#, python-format
msgid ""
"Delete Snapshot: Target: %(snapshot)s  Source: %(volume)s.  Method: "
"ModifyReplicaSynchronization:  Replication Service: %(service)s  "
"Operation: 19  Synchronization: %(sync_name)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:588
#, python-format
msgid ""
"Delete Snapshot: Volume: %(volumename)s  Snapshot: %(snapshotname)s  "
"Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:597
#, python-format
msgid ""
"Error Delete Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Return code: %(rc)lu. Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:609
#, python-format
msgid ""
"Leaving delete_snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:619
#, python-format
msgid "Create export: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:624
#, python-format
msgid "create_export: Volume: %(volume)s  Device ID: %(device_id)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:646
#, python-format
msgid ""
"ExposePaths: %(vol)s  ConfigServicie: %(service)s  LUNames: %(lun_name)s"
"  InitiatorPortIDs: %(initiator)s  DeviceAccesses: 2"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:661
#, python-format
msgid "ExposePaths parameter LunMaskingSCSIProtocolController: %(lunmasking)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:672
#, python-format
msgid "Error mapping volume %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:676
#, python-format
msgid "ExposePaths for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:692
#, python-format
msgid ""
"HidePaths: %(vol)s  ConfigServicie: %(service)s  LUNames: %(device_id)s  "
"LunMaskingSCSIProtocolController: %(lunmasking)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:705
#, python-format
msgid "Error unmapping volume %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:709
#, python-format
msgid "HidePaths for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:722
#, python-format
msgid ""
"AddMembers: ConfigServicie: %(service)s  MaskingGroup: %(masking_group)s"
"  Members: %(vol)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:737
#, python-format
msgid "Error mapping volume %(vol)s. %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:742
#, python-format
msgid "AddMembers for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:755
#, python-format
msgid ""
"RemoveMembers: ConfigServicie: %(service)s  MaskingGroup: "
"%(masking_group)s  Members: %(vol)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:768
#, python-format
msgid "Error unmapping volume %(vol)s. %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:773
#, python-format
msgid "RemoveMembers for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:779
#, python-format
msgid "Map volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:788
#: cinder/volume/drivers/emc/emc_smis_common.py:818
#, python-format
msgid "Cannot find Controller Configuration Service for storage system %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:802
#, python-format
msgid "Unmap volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:808
#, python-format
msgid "Volume %s is not mapped. No volume to unmap."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:832
#, python-format
msgid "Initialize connection: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:838
#, python-format
msgid "Volume %s is already mapped."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:850
#, python-format
msgid "Terminate connection: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:882
#, python-format
msgid "Found Storage Type: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:885
msgid "Storage type not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:901
#, python-format
msgid "Found Masking View: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:904
msgid "Masking View not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:926
msgid "Ecom user not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:946
#, python-format
msgid "Ecom IP: %(ecomIp)s Port: %(ecomPort)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:950
msgid "Ecom server not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:957
msgid "Cannot connect to ECOM server"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:969
#, python-format
msgid "Found Replication Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:982
#, python-format
msgid "Found Storage Configuration Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:995
#, python-format
msgid "Found Controller Configuration Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1008
#, python-format
msgid "Found Storage Hardware ID Management Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1052
#, python-format
msgid "Pool %(storage_type)s is not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1058
#, python-format
msgid "Storage system not found for pool %(storage_type)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1064
#, python-format
msgid "Pool: %(pool)s  SystemName: %(systemname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1080
#, python-format
msgid "Pool name: %(poolname)s  System name: %(systemname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1112
#, python-format
msgid "Volume %(volumename)s not found on the array."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1115
#, python-format
msgid "Volume name: %(volumename)s  Volume instance: %(vol_instance)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1128
#, python-format
msgid "Source: %(volumename)s  Target: %(snapshotname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1151
#, python-format
msgid ""
"Source: %(volumename)s  Target: %(snapshotname)s. Storage Synchronized "
"not found. "
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1156
#, python-format
msgid ""
"Storage system: %(storage_system)s  Storage Synchronized instance: "
"%(sync)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1182
#, python-format
msgid "Error finding %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1186
#, python-format
msgid "Found %(name)s: %(initiator)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1246
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage system %(storage_system)s "
"and initiator %(initiator)s is  %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1287
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage volume %(vol)s and initiator"
" %(initiator)s is  %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1300
#, python-format
msgid ""
"Volume %(name)s not found on the array. Cannot determine if there are "
"volumes mapped."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1312
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage system %(storage)s and "
"%(connector)s is %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1324
#, python-format
msgid ""
"Found %(numVolumesMapped)d volumes on storage system %(storage)s mapped "
"to %(initiator)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1359
#, python-format
msgid "Available device number on %(storage)s: %(device)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1402
#, python-format
msgid "Device number not found for volume %(volumename)s %(vol_instance)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1407
#, python-format
msgid "Found device number %(device)d for volume %(volumename)s %(vol_instance)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1417
#, python-format
msgid "Device info: %(data)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1439
#, python-format
msgid "Masking view: %(view)s DeviceMaskingGroup: %(masking)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1461
#, python-format
msgid "Found Storage Processor System: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1489
#, python-format
msgid ""
"iSCSIProtocolEndpoint for storage system %(storage_system)s and SP %(sp)s"
" is  %(endpoint)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1518
msgid "Error finding Storage Hardware ID Service."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1524
#, python-format
msgid ""
"EMCGetTargetEndpoints: Service: %(service)s  Storage HardwareIDs: "
"%(hardwareids)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1536
msgid "Error finding Target WWNs."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1546
#, python-format
msgid "Add target WWN: %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1548
#, python-format
msgid "Target WWNs: %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1564
#, python-format
msgid "Storage Hardware IDs for %(wwpns)s is %(foundInstances)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:152
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:161
#, python-format
msgid "Cannot find device number for volume %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:191
#, python-format
msgid "Found iSCSI endpoint: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:198
#, python-format
msgid "ISCSI endpoint not found for SP %(sp)s on storage system %(storage)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:215
#, python-format
msgid "ISCSI properties: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:58
#, python-format
msgid "Range: start LU: %(start)s, end LU: %(end)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:72
#, python-format
msgid "setting LU uppper (end) limit to %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:80
#, python-format
msgid "%(element)s: %(val)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:91 cinder/volume/drivers/hds/hds.py:93
#, python-format
msgid "XML exception reading parameter: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:164
#, python-format
msgid "portal: %(ip)s:%(ipp)s, CTL: %(ctl)s, port: %(port)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:183
#, python-format
msgid "No configuration found for service: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:236
#, python-format
msgid "HDP not found: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:275
#, python-format
msgid "iSCSI portal not found for service: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:313
#, python-format
msgid "LUN %(lun)s of size %(sz)s MB is created."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:327
#, python-format
msgid "Array Mismatch %(myid)s vs %(arid)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:333
#, python-format
msgid "delete lun %(lun)s on %(name)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:414
#, python-format
msgid "LUN %(lun)s of size %(sz)s MB is created from snapshot."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:437
#, python-format
msgid "LUN %(lun)s of size %(size)s MB is created."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:451
#, python-format
msgid "Array mismatch %(myid)s vs %(arid)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:463
#, python-format
msgid "LUN %s is deleted."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:117
msgid "read timed out"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:142
msgid "do_setup."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:148
msgid "check_for_setup_error."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:153
msgid "check_for_setup_error: Can not get device type."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:157
#, python-format
msgid "check_for_setup_error: Device type is:%(type)s, version is:%(version)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:164
msgid ""
"check_for_setup_error: Product version not right. Please make sure the "
"product version is V1."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:175
msgid "_get_device_type: Storage Pool must be configured."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:184
#, python-format
msgid "create_volume:volume name: %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:198
#, python-format
msgid "delete_volume: volume name: %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:205
#, python-format
msgid "delete_volume:No need to delete volume. Volume %(name)s does not exist."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:214
#, python-format
msgid "create_export: volume name:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:218
#, python-format
msgid "create_export:Volume %(name)s does not exist."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:238
#, python-format
msgid "initialize_connection: volume name: %(volume)s. initiator name: %(ini)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:253
#, python-format
msgid ""
"initialize_connection:Failed to find target ip for "
"initiator:%(initiatorname)s, please check config file."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:263
#, python-format
msgid "initialize_connection:Failed to find target iSCSI iqn. Target IP:%(ip)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:301
#, python-format
msgid ""
"initialize_connection:host name: %(host)s, initiator name: %(ini)s, "
"hostport name: %(port)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:311
#, python-format
msgid ""
"initialize_connection:Failed to find the given volume. volume "
"name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:363
#, python-format
msgid "terminate_connection:volume name: %(volume)s, initiator name: %(ini)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:372
#, python-format
msgid "terminate_connection:Host does not exist. Host name:%(host)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:381
#, python-format
msgid "terminate_connection:volume does not exist. volume name:%(volume)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:400
#, python-format
msgid ""
"terminate_connection:No map between host and volume. Host "
"name:%(hostname)s, volume name:%(volumename)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:418
#, python-format
msgid ""
"terminate_connection:No initiator is added to the host. Host "
"name:%(hostname)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:431
#, python-format
msgid "create_snapshot:snapshot name:%(snapshot)s, volume name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:438
msgid "create_snapshot:Device does not support snapshot."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:444
msgid "create_snapshot:Resource pool needs 1GB valid size at least."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:451
#, python-format
msgid "create_snapshot:Volume does not exist. Volume name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:460
#, python-format
msgid "create_snapshot:Snapshot does not exist. Snapshot name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:472
#, python-format
msgid "delete_snapshot:snapshot name:%(snapshot)s, volume name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:479
msgid "delete_snapshot:Device does not support snapshot."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:488
#, python-format
msgid "delete_snapshot:Snapshot does not exist. snapshot name:%(snap)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:501
#, python-format
msgid ""
"create_volume_from_snapshot:snapshot name:%(snapshot)s, volume "
"name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:509
#, python-format
msgid ""
"create_volume_from_snapshot:Device does not support create volume from "
"snapshot. Volume name:%(volume)s, snapshot name:%(snapshot)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:520
#, python-format
msgid ""
"create_volume_from_snapshot:Snapshot does not exist. Snapshot "
"name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:571
msgid "Config file is wrong. Controler IP, UserName and UserPassword must be set."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:577
#, python-format
msgid "_check_conf_file: %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:588
#, python-format
msgid "_read_xml:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:616
#, python-format
msgid "Write login information to xml error. %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:620
#, python-format
msgid "_get_login_info error. %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:642
#, python-format
msgid ""
"Config file is wrong. LUNType must be \"Thin\"  or \"Thick\". "
"LUNType:%(type)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:669
msgid "_get_lun_set_info:Use default prefetch type. Prefetch type:Intelligent."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:680
msgid ""
"_get_lun_set_info:No available pools! Please check whether storage pool "
"is created."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:690
#, python-format
msgid "_get_lun_set_info:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:740
msgid ""
"_get_maximum_pool:maxpoolid is None. Please check config file and make "
"sure the \"Name\" in \"StoragePool\" is right."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:758
#, python-format
msgid "_get_iscsi_info:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:768
#, python-format
msgid "CLI command:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:835
#, python-format
msgid "_execute_cli:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:842
#, python-format
msgid ""
"_name_translate:Name in cinder: %(old)s, new name in storage system: "
"%(new)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:876
#, python-format
msgid ""
"_create_hostgroup:Failed to Create hostgroup. Hostgroup name: %(name)s. "
"out:%(out)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:905
#, python-format
msgid ""
"_add_host:Failed to add host to hostgroup. host name:%(host)s hostgroup "
"id:%(hostgroup)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:931
#, python-format
msgid ""
"_add_initiator:Failed to add initiator. initiator name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:945
#, python-format
msgid ""
"_delete_initiator:ERROE:Failed to delete initiator. initiator "
"name:%(name)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:995
#, python-format
msgid ""
"_add_hostport:Failed to add hostport. port name:%(port)s port "
"information:%(info)s host id:%(host)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1013
#, python-format
msgid "_delete_hostport:Failed to delete host port. port id:%(portid)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1020
#, python-format
msgid "_get_tgt_iqn:iSCSI IP is %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1053
#, python-format
msgid "_get_tgt_iqn:iSCSI target iqn is:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1090
#, python-format
msgid ""
"_map_lun:Failed to add hostmap. hostid:%(host)s lunid:%(lun)s "
"hostlunid:%(hostlunid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1126
#, python-format
msgid ""
"_delete_map:There are IOs accessing the system. Retry to delete host map."
" map id:%(mapid)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1132
#, python-format
msgid "_delete_map:Failed to delete host map. mapid:%(mapid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1146
#, python-format
msgid "_delete_host: Failed delete host. host id:%(hostid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1227
#, python-format
msgid ""
"_active_snapshot:Failed to active snapshot. snapshot id:%(name)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1241
#, python-format
msgid ""
"_disable_snapshot:Failed to disable snapshot. snapshot id:%(id)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1255
#, python-format
msgid ""
"_delete_snapshot:Failed to delete snapshot. snapshot id:%(id)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1312
#, python-format
msgid "_create_volume:Failed to Create volume. volume name:%(name)s. out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1325
#, python-format
msgid "_delete_volume:Failed to delete volume. Volume name:%(name)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1342
#, python-format
msgid ""
"_create_luncopy:Failed to Create LUNcopy. LUNcopy name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1356
#, python-format
msgid ""
"_start_luncopy:Failed to start LUNcopy. LUNcopy id:%(luncopyid)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1386
#, python-format
msgid ""
"_wait_for_luncopy:LUNcopy status is not normal. LUNcopy "
"name:%(luncopyname)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1419
#, python-format
msgid ""
"_delete_luncopy:Failed to delete LUNcopy. LUNcopy id:%(luncopyid)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1434
#, python-format
msgid ""
"_create_snapshot:Failed to Create snapshot. Snapshot name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1472
#, python-format
msgid ""
"_change_lun_controller:Failed to change lun owning controller. lun "
"id:%(lunid)s. new controller:%(controller)s. out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1488
msgid "_is_resource_pool_enough:Resource pool for snapshot not be added."
msgstr ""

#: cinder/volume/drivers/netapp/common.py:81
msgid "Required configuration not found"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:109
#, python-format
msgid "Requested unified config: %(storage_family)s and %(storage_protocol)s"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:115
#, python-format
msgid "Storage family %s is not supported"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:122
#, python-format
msgid "No default storage protocol found for storage family %(storage_family)s"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:131
#, python-format
msgid ""
"Protocol %(storage_protocol)s is not supported for storage family "
"%(storage_family)s"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:138
#, python-format
msgid ""
"NetApp driver of family %(storage_family)s and protocol "
"%(storage_protocol)s loaded"
msgstr ""

#: cinder/volume/drivers/netapp/common.py:147
msgid "Only loading netapp drivers supported."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:73
#, python-format
msgid "No metadata property %(prop)s defined for the LUN %(name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:106
#, python-format
msgid "Using NetApp filer: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:149
msgid "Success getting LUN list from server"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:164
#, python-format
msgid "Created LUN with name %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:173
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:182
#, python-format
msgid "Destroyed LUN %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:217
#, python-format
msgid "Mapped LUN %(name)s to the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:222
#, python-format
msgid ""
"Succesfully fetched target details for LUN %(name)s and initiator "
"%(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:228
#, python-format
msgid "Failed to get LUN target details for the LUN %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:239
#, python-format
msgid "Failed to get target portal for the LUN %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:242
#, python-format
msgid "Failed to get target IQN for the LUN %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:279
#, python-format
msgid "Snapshot %s deletion successful"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:290
#: cinder/volume/drivers/netapp/nfs.py:78
#, python-format
msgid ""
"Cannot create volume of size %(vol_size)s from snapshot of size "
"%(snap_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:309
#, python-format
msgid "Unmapped LUN %(name)s from the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:328
#, python-format
msgid "Failed to get vol with required size for volume: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:404
#, python-format
msgid "Error mapping lun. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:424
#, python-format
msgid "Error unmapping lun. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:503
msgid "Object is not a NetApp LUN."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:519
#, python-format
msgid "Could not find attribute for LUN named %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:532
#, python-format
msgid ""
"Cannot clone volume of size %(vol_size)s from src volume of size "
"%(src_vol_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:656
#, python-format
msgid "No iscsi service found for vserver %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:787
#, python-format
msgid "Cloned LUN with new name %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:791
#, python-format
msgid "No clonned lun named %s found on the filer"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:979
#, python-format
msgid "Error finding luns for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1084
#, python-format
msgid "Clone operation with src %(name)s and dest %(new_name)s completed"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1087
#, python-format
msgid "Clone operation with src %(name)s and dest %(new_name)s failed"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:175
#, python-format
msgid ""
"Cannot create clone of size %(vol_size)s from volume of size "
"%(src_vol_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:303
#, python-format
msgid "No interface found on cluster for ip %s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:330
#, python-format
msgid ""
"No volume on cluster with vserver\n"
"                                   %(vserver)s and junction path "
"%(junction)s\n"
"                                   "
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:336
#, python-format
msgid ""
"Cloning with params volume %(volume)s,src %(src_path)s,\n"
"                    dest %(dest_path)s, vserver %(vserver)s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:409
#, python-format
msgid "No storage path found for export path %s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:418
#, python-format
msgid "Cloning with src %(src_path)s, dest %(dest_path)s"
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:106
msgid "ems executed successfully."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:108
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:119
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/nexenta/__init__.py:27
msgid "Nexenta SA returned the error"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:64
#, python-format
msgid "Sending JSON data: %s"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:69
#, python-format
msgid "Auto switching to HTTPS connection to %s"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:75
msgid "No headers in server response"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:76
msgid "Bad response from server"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:79
#, python-format
msgid "Got response: %s"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:103
#, python-format
msgid "Volume %s does not exist in Nexenta SA"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:137
#, python-format
msgid "Extending volume: %(id)s New size: %(size)s GB"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:151
#, python-format
msgid "Volume %s does not exist, it seems it was already deleted"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:229
#, python-format
msgid "Ignored target group creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:238
#, python-format
msgid "Ignored target group member addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:246
#, python-format
msgid "Ignored LU creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:256
#, python-format
msgid "Ignored LUN mapping entry addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:292
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:300
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:74
#, python-format
msgid "CLIQ command returned %s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:80
#, python-format
msgid "Malformed response to CLIQ command %(verb)s %(cliq_args)s. Result=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:88
#, python-format
msgid "Error running CLIQ command %(verb)s %(cliq_args)s.  Result=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:118
#, python-format
msgid ""
"Unexpected number of virtual ips for cluster  %(cluster_name)s. "
"Result=%(_xml)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:171
#, python-format
msgid "Volume info: %(volume_name)s => %(volume_attributes)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:236
msgid "local_path not supported"
msgstr ""

#: cinder/volume/drivers/san/san.py:150
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

#: cinder/volume/drivers/san/san.py:170
msgid "Specify san_password or san_private_key"
msgstr ""

#: cinder/volume/drivers/san/san.py:174
msgid "san_ip must be set"
msgstr ""

#: cinder/volume/drivers/san/solaris.py:79
#, python-format
msgid "Cannot parse list-view output: %s"
msgstr ""

#: cinder/volume/drivers/san/solaris.py:174
#, python-format
msgid "LUID not found for %(zfs_poolname)s. Output=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:136
msgid ""
"hp3par_domain has been deprecated and is no longer used. The domain is "
"automatically looked up based on the CPG."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:156
msgid "Login to 3PAR array invalid"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:181
#: cinder/volume/drivers/san/hp/hp_3par_common.py:571
#, python-format
msgid "CPG (%s) doesn't exist on array"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:197
#, python-format
msgid "Failed to get domain because CPG (%s) doesn't exist on array."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:204
#, python-format
msgid "CPG (%s) must be in a domain"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:220
#, python-format
msgid "Error extending volume %s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:363
#, python-format
msgid "SSH Command failed after '%(total_attempts)r' attempts : '%(command)s'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:369
#, python-format
msgid "Error running ssh command: %s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:689
#, python-format
msgid "Must specify a valid persona %(valid)s, value '%(persona)s' is invalid."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:750
#, python-format
msgid ""
"Must specify a valid provisioning type %(valid)s, value '%(prov)s' is "
"invalid."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:790
#, python-format
msgid "Volume (%s) already exists on array"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:104
#, python-format
msgid "Invalid IP address format '%s'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:137
#, python-format
msgid ""
"Found invalid iSCSI IP address(s) in configuration option(s) "
"hp3par_iscsi_ips or iscsi_ip_address '%s.'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:143
msgid "At least one valid iSCSI IP address must be set."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_iscsi.py:330
msgid "Least busy iSCSI port not found, using first iSCSI port in list."
msgstr ""

#~ msgid "Error retrieving volume status: %s"
#~ msgstr ""

#~ msgid "_update_volume_status: Could not get system name"
#~ msgstr ""

#~ msgid "_update_volume_status: Could not get storage pool data"
#~ msgstr ""

#~ msgid "Cannot find any Fibre Channel HBAs"
#~ msgstr ""

#~ msgid "Volume status must be available or error"
#~ msgstr ""

#~ msgid "No backend config with id %s"
#~ msgstr ""

#~ msgid "No sm_flavor called %s"
#~ msgstr ""

#~ msgid "No sm_volume with id %s"
#~ msgstr ""

#~ msgid "Error: %s"
#~ msgstr ""

#~ msgid "Unexpected state while cloning %s"
#~ msgstr ""

#~ msgid "iSCSI device not found at %s"
#~ msgstr ""

#~ msgid "Fibre Channel device not found."
#~ msgstr ""

#~ msgid "Uncaught exception"
#~ msgstr ""

