# Czech translation for cinder
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the cinder package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version:  cinder\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2013-06-15 18:10+0000\n"
"PO-Revision-Date: 2012-04-04 20:28+0000\n"
"Last-Translator: Zbyněk Schwarz <Unknown>\n"
"Language-Team: Czech <cs@li.org>\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: cinder/context.py:61
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: cinder/context.py:92
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: cinder/exception.py:64
msgid "Unexpected error while running command."
msgstr "Při spuštění příkazu došlo k nečekané chybě."

#: cinder/exception.py:67
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Příkaz: %(cmd)s\n"
"Kód ukončení: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: cinder/exception.py:84
msgid "An unknown exception occurred."
msgstr "Vyskytla se neočekávaná výjimka."

#: cinder/exception.py:105 cinder/openstack/common/rpc/common.py:86
msgid "Exception in string format operation"
msgstr ""

#: cinder/exception.py:118
msgid "Connection to glance failed"
msgstr "Připojení k glance selhalo"

#: cinder/exception.py:122
msgid "Not authorized."
msgstr "Neschváleno."

#: cinder/exception.py:127
msgid "User does not have admin privileges"
msgstr "Uživatel nemá správcovská oprávnění"

#: cinder/exception.py:131
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "Pravidla nedovolují, aby bylo %(action)s provedeno."

#: cinder/exception.py:135
#, fuzzy, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "Kernel nenalezen v obrazu %(image_id)s."

#: cinder/exception.py:139
msgid "Unacceptable parameters."
msgstr "Nepřijatelné parametry."

#: cinder/exception.py:144
msgid "Invalid snapshot"
msgstr "Neplatný snímek"

#: cinder/exception.py:148
#, python-format
msgid "Invalid source volume %(reason)s."
msgstr ""

#: cinder/exception.py:152
#, fuzzy, python-format
msgid "Volume %(volume_id)s is still attached, detach volume first."
msgstr "Svazek %(volume_id)s není k ničemu připojen"

#: cinder/exception.py:156
msgid "Failed to load data into json format"
msgstr "Nelze načíst data do formátu json"

#: cinder/exception.py:160
msgid "The request is invalid."
msgstr "Požadavek je neplatný."

#: cinder/exception.py:164
#, fuzzy
msgid "The results are invalid."
msgstr "Požadavek je neplatný."

#: cinder/exception.py:168
msgid "Invalid input received"
msgstr "Obdržen neplatný vstup"

#: cinder/exception.py:172
msgid "Invalid volume type"
msgstr "Neplatný typ svazku"

#: cinder/exception.py:176
msgid "Invalid volume"
msgstr "Neplatný svazek"

#: cinder/exception.py:180
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "Neplatný typ obsahu %(content_type)s."

#: cinder/exception.py:186
#, python-format
msgid "%(err)s"
msgstr "%(err)s"

#: cinder/exception.py:190
#, fuzzy
msgid "Invalid auth key"
msgstr "Neplatný snímek"

#: cinder/exception.py:194
msgid "Service is unavailable at this time."
msgstr "Služba je v tuto chvíli nedostupná."

#: cinder/exception.py:198
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "Obraz %(image_id)s je nepřijatelný: %(reason)s"

#: cinder/exception.py:202
#, python-format
msgid "The device in the path %(path)s is unavailable: %(reason)s"
msgstr ""

#: cinder/exception.py:206
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: cinder/exception.py:210
msgid "Resource could not be found."
msgstr "Zdroj nemohl být nalezen."

#: cinder/exception.py:216
#, fuzzy, python-format
msgid "Volume %(volume_id)s persistence file could not be found."
msgstr "Svazek %(volume_id)s nemohl být nastaven."

#: cinder/exception.py:220
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "Svazek %(volume_id)s nemohl být nastaven."

#: cinder/exception.py:224
#, fuzzy, python-format
msgid "Unable to locate account %(account_name)s on Solidfire device"
msgstr "Nelze nalézt účet %(account_name) on zařízení Solidfire"

#: cinder/exception.py:229
#, python-format
msgid "Volume not found for instance %(instance_id)s."
msgstr "Svazek není nalezen v instanci %(instance_id)s."

#: cinder/exception.py:233
#, python-format
msgid "Volume %(volume_id)s has no metadata with key %(metadata_key)s."
msgstr "Svazek %(volume_id)s nemá žádná metadata s klíčem %(metadata_key)s."

#: cinder/exception.py:238 cinder/exception.py:251
msgid "Invalid metadata"
msgstr "Neplatná metadata"

#: cinder/exception.py:242 cinder/exception.py:255
#, fuzzy
msgid "Invalid metadata size"
msgstr "Neplatný klíč metadata"

#: cinder/exception.py:246
#, fuzzy, python-format
msgid "Snapshot %(snapshot_id)s has no metadata with key %(metadata_key)s."
msgstr "Instance %(instance_id)s nemá žádná metadata s klíčem %(metadata_key)s."

#: cinder/exception.py:259
#, python-format
msgid "Volume type %(volume_type_id)s could not be found."
msgstr "Typ svazku %(volume_type_id)s nemohl být nalezen."

#: cinder/exception.py:263
#, python-format
msgid "Volume type with name %(volume_type_name)s could not be found."
msgstr "Typ svazku s názvem %(volume_type_name)s nemohl být nalezen."

#: cinder/exception.py:268
#, python-format
msgid ""
"Volume Type %(volume_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""
"Typ svazku %(volume_type_id)s nemá žádné dodatečné parametry s klíčem "
"%(extra_specs_key)s."

#: cinder/exception.py:273
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "Snímek %(snapshot_id)s nemohl být nalezen."

#: cinder/exception.py:277
#, python-format
msgid "deleting volume %(volume_name)s that has snapshot"
msgstr "mazání svazku %(volume_name)s který má snímek"

#: cinder/exception.py:281
#, python-format
msgid "deleting snapshot %(snapshot_name)s that has dependent volumes"
msgstr ""

#: cinder/exception.py:286
#, python-format
msgid "No target id found for volume %(volume_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/exception.py:290
#, fuzzy, python-format
msgid "Failed to create iscsi target for volume %(volume_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/exception.py:294
#, fuzzy, python-format
msgid "Failed to attach iSCSI target for volume %(volume_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/exception.py:298
#, fuzzy, python-format
msgid "Failed to remove iscsi target for volume %(volume_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/exception.py:302
#, python-format
msgid "No disk at %(location)s"
msgstr "Źádný disk ve %(location)s"

#: cinder/exception.py:306
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "Neplatný href %(image_href)s obrazu."

#: cinder/exception.py:310
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "Obraz %(image_id)s nemohl být nalezen."

#: cinder/exception.py:314
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "Služba %(service_id)s nemohla být nalezena."

#: cinder/exception.py:318
#, python-format
msgid "Host %(host)s could not be found."
msgstr "Hostitel %(host)s nemohl být nalezen."

#: cinder/exception.py:322
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr "Filtr hostitelů plácinderče %(filter_name)s nemohl být nalezen."

#: cinder/exception.py:326
#, fuzzy, python-format
msgid "Scheduler Host Weigher %(weigher_name)s could not be found."
msgstr "Filtr hostitelů plácinderče %(filter_name)s nemohl být nalezen."

#: cinder/exception.py:330
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr "Nelze najít binární soubor %(binary)s v hostiteli %(host)s."

#: cinder/exception.py:334
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: cinder/exception.py:338
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: cinder/exception.py:343
msgid "Quota could not be found"
msgstr "Kvóta nemohla být nalezena."

#: cinder/exception.py:347
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: cinder/exception.py:351
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "Kvóta pro projekt %(project_id)s nemohla být nalezena."

#: cinder/exception.py:355
#, fuzzy, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "Třída %(class_name)s nemohla být nalezena: %(exception)s"

#: cinder/exception.py:359
#, fuzzy, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "Kvóta pro projekt %(project_id)s nemohla být nalezena."

#: cinder/exception.py:363
#, fuzzy, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "Uživatel %(user_id)s nemohl být nalezen."

#: cinder/exception.py:367
#, fuzzy, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "Kvóta překročena"

#: cinder/exception.py:371
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr "Přesun %(migration_id)s nemohl být nalezen."

#: cinder/exception.py:375
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr "Přesun nenalezen v instanci %(instance_id)s se stavem %(status)s."

#: cinder/exception.py:380
#, python-format
msgid "File %(file_path)s could not be found."
msgstr "Soubor %(file_path)s nemohl být nalezen."

#: cinder/exception.py:384
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr "Třída %(class_name)s nemohla být nalezena: %(exception)s"

#: cinder/exception.py:388
msgid "Action not allowed."
msgstr "Činnost není povolena."

#: cinder/exception.py:397
#, python-format
msgid "Key pair %(key_name)s already exists."
msgstr "Dvojice klíčů %(key_name)s již existuje."

#: cinder/exception.py:401
#, fuzzy, python-format
msgid "Volume Type %(id)s already exists."
msgstr "Typ svazku %(name)s již existuje."

#: cinder/exception.py:405
msgid "Migration error"
msgstr "Chyba přesunu"

#: cinder/exception.py:409
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "Poškozené tělo zprávy: %(reason)s"

#: cinder/exception.py:413
#, python-format
msgid "Could not find config at %(path)s"
msgstr "Nelze najít nastavení v %(path)s"

#: cinder/exception.py:417
#, fuzzy, python-format
msgid "Could not find parameter %(param)s"
msgstr "Nelze najít nastavení v %(path)s"

#: cinder/exception.py:421
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr "Nelze načíst aplikaci vložení '%(name)s' z %(path)s"

#: cinder/exception.py:425
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr "Nebyl nalezen žádný platný hostitel. %(reason)s"

#: cinder/exception.py:429
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr "Hostitel %(host)s není dostupný nebo neexistuje."

#: cinder/exception.py:433
msgid "Quota exceeded"
msgstr "Kvóta překročena"

#: cinder/exception.py:440
msgid "Requested volume or snapshot exceeds allowed Gigabytes quota"
msgstr ""

#: cinder/exception.py:445
msgid "Maximum volume/snapshot size exceeded"
msgstr ""

#: cinder/exception.py:449
#, python-format
msgid "Maximum number of volumes allowed (%(allowed)d) exceeded"
msgstr ""

#: cinder/exception.py:453
#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded"
msgstr ""

#: cinder/exception.py:457
#, fuzzy, python-format
msgid "Detected more than one volume with name %(vol_name)s"
msgstr "Zjištěn více než jeden svazek s názvem %(vol_name)"

#: cinder/exception.py:461
#, python-format
msgid "3PAR Host already exists: %(err)s.  %(info)s"
msgstr ""

#: cinder/exception.py:465
#, python-format
msgid "Invalid 3PAR Domain: %(err)s"
msgstr ""

#: cinder/exception.py:469
#, python-format
msgid "Cannot create volume_type with name %(name)s and specs %(extra_specs)s"
msgstr ""
"Nelze vytvořit typ_svazku s názvem %(name)s a specifikacemi "
"%(extra_specs)s"

#: cinder/exception.py:474
msgid "Bad response from SolidFire API"
msgstr "Špatná odpověď od SolidFire API"

#: cinder/exception.py:478
#, python-format
msgid "Error in SolidFire API response: data=%(data)s"
msgstr "Chyba v odpovědi SolidFire API: data=%(data)s"

#: cinder/exception.py:482
#, python-format
msgid "Unknown or unsupported command %(cmd)s"
msgstr ""

#: cinder/exception.py:486
#, fuzzy, python-format
msgid "Malformed response to command %(cmd)s: %(reason)s"
msgstr "Poškozené tělo zprávy: %(reason)s"

#: cinder/exception.py:490
#, fuzzy, python-format
msgid "Bad HTTP response status %(status)s"
msgstr "Neplatný stav serveru: %(status)s"

#: cinder/exception.py:494
#, python-format
msgid "Operation failed with status=%(status)s. Full dump: %(data)s"
msgstr ""

#: cinder/exception.py:498
#, python-format
msgid "Unable to create server object for initiator %(name)s"
msgstr ""

#: cinder/exception.py:502
#, python-format
msgid "Unable to find server object for initiator %(name)s"
msgstr ""

#: cinder/exception.py:506
msgid "Unable to find any active VPSA controller"
msgstr ""

#: cinder/exception.py:510
#, python-format
msgid "Failed to retrieve attachments for volume %(name)s"
msgstr ""

#: cinder/exception.py:514
#, python-format
msgid "Invalid attachment info for volume %(name)s: %(reason)s"
msgstr ""

#: cinder/exception.py:518
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr "Instance %(instance_id)s nemohla být nastavena."

#: cinder/exception.py:522
#, python-format
msgid "Bad or unexpected response from the storage volume backend API: %(data)s"
msgstr ""

#: cinder/exception.py:527
#, fuzzy
msgid "Unknown NFS exception"
msgstr "Vyskytla se neočekávaná výjimka."

#: cinder/exception.py:531
msgid "No mounted NFS shares found"
msgstr ""

#: cinder/exception.py:535 cinder/exception.py:547
#, python-format
msgid "There is no share which can host %(volume_size)sG"
msgstr ""

#: cinder/exception.py:539
#, fuzzy
msgid "Unknown Gluster exception"
msgstr "Vyskytla se neočekávaná výjimka."

#: cinder/exception.py:543
msgid "No mounted Gluster shares found"
msgstr ""

#: cinder/exception.py:551
#, python-format
msgid ""
"Glance metadata cannot be updated, key %(key)s exists for volume id "
"%(volume_id)s"
msgstr ""

#: cinder/exception.py:556
#, fuzzy, python-format
msgid "Failed to copy image to volume: %(reason)s"
msgstr "Poškozené tělo zprávy: %(reason)s"

#: cinder/exception.py:560
#, fuzzy, python-format
msgid "Backup %(backup_id)s could not be found."
msgstr "Skupina LDAP %(group_id)s nemohla být nalezena."

#: cinder/exception.py:564
#, fuzzy, python-format
msgid "Invalid backup: %(reason)s"
msgstr "Neplatná podpůrná vrstva: %s"

#: cinder/exception.py:568
#, fuzzy
msgid "Connection to swift failed"
msgstr "Připojení k glance selhalo"

#: cinder/exception.py:572
#, fuzzy, python-format
msgid "Transfer %(transfer_id)s could not be found."
msgstr "Obraz %(image_id)s nemohl být nalezen."

#: cinder/flags.py:144
msgid "Deploy v1 of the Cinder API. "
msgstr ""

#: cinder/flags.py:147
msgid "Deploy v2 of the Cinder API. "
msgstr ""

#: cinder/manager.py:135
msgid "Notifying Schedulers of capabilities ..."
msgstr "Oznamování schopností plácinderčům ..."

#: cinder/policy.py:31
msgid "JSON file representing policy"
msgstr "Soubor JSON představující zásady"

#: cinder/policy.py:34
msgid "Rule checked when requested rule is not found"
msgstr "Kontrolované pravidlo, když požadované není nalezeno"

#: cinder/quota.py:705
#, python-format
msgid "Created reservations %(reservations)s"
msgstr ""

#: cinder/quota.py:727
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: cinder/quota.py:748
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: cinder/service.py:125
msgid "SIGTERM received"
msgstr ""

#: cinder/service.py:175 cinder/openstack/common/service.py:165
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: cinder/service.py:214 cinder/openstack/common/service.py:201
msgid "Forking too fast, sleeping"
msgstr ""

#: cinder/service.py:232 cinder/openstack/common/service.py:122
#: cinder/openstack/common/service.py:219
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: cinder/service.py:237 cinder/openstack/common/service.py:224
#, fuzzy
msgid "Unhandled exception"
msgstr "Vnitřní výjimka: %s"

#: cinder/service.py:244 cinder/openstack/common/service.py:231
#, python-format
msgid "Started child %d"
msgstr ""

#: cinder/service.py:254 cinder/openstack/common/service.py:241
#, python-format
msgid "Starting %d workers"
msgstr ""

#: cinder/service.py:273 cinder/openstack/common/service.py:258
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: cinder/service.py:276
#, python-format
msgid "Child %(pid)d exited with status %(code)d"
msgstr ""

#: cinder/service.py:279 cinder/openstack/common/service.py:266
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: cinder/service.py:287
#, python-format
msgid "_wait_child %d"
msgstr ""

#: cinder/service.py:303
#, fuzzy, python-format
msgid "wait wrap.failed %s"
msgstr "Vyvoláno Nenalezeno: %s"

#: cinder/service.py:311 cinder/openstack/common/service.py:294
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: cinder/service.py:322 cinder/openstack/common/service.py:305
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: cinder/service.py:354
#, fuzzy, python-format
msgid "Starting %(topic)s node (version %(version_string)s)"
msgstr "Začínající uzel %(topic)s (verze %(vcs_string)s)"

#: cinder/service.py:368 cinder/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr "Vytváření připojení zákazníka pro službu %s"

#: cinder/service.py:459
msgid "Service killed that has no database entry"
msgstr "Ukončena služba bez záznamu v databázi"

#: cinder/service.py:496
msgid "The service database object disappeared, Recreating it."
msgstr "Objekt databáze služby zmizel, je znovu vytvářen."

#: cinder/service.py:511
msgid "Recovered model server connection!"
msgstr "Obnoveno připojení modelového serveru!"

#: cinder/service.py:517
msgid "model server went away"
msgstr "modelový server je nedostupný"

#: cinder/service.py:609 cinder/openstack/common/service.py:113
#: cinder/openstack/common/service.py:276
#, fuzzy
msgid "Full set of CONF:"
msgstr "Úplná sada PŘÍZNAKŮ:"

#: cinder/service.py:616
#, python-format
msgid "%(flag)s : FLAG SET "
msgstr "%(flag)s : SADA PŽÍZNAKŮ "

#: cinder/utils.py:93
#, python-format
msgid "Fetching %s"
msgstr "Získávání %s"

#: cinder/utils.py:144 cinder/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "Získány neznámé argumenty klíčového slova pro utils.execute: %r"

#: cinder/utils.py:150
msgid ""
"The root_helper option (which lets you specify a root wrapper different "
"from cinder-rootwrap, and defaults to using sudo) is now deprecated. You "
"should use the rootwrap_config option instead."
msgstr ""

#: cinder/utils.py:166 cinder/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Spouštění příkazu (podproces): %s"

#: cinder/utils.py:183 cinder/utils.py:264
#: cinder/openstack/common/processutils.py:167
#: cinder/openstack/common/processutils.py:239
#: cinder/volume/drivers/san/hp/hp_3par_common.py:279
#, python-format
msgid "Result was %s"
msgstr "Výsledek byl %s"

#: cinder/utils.py:196 cinder/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr "%r selhalo. Opakování."

#: cinder/utils.py:238 cinder/openstack/common/processutils.py:218
#: cinder/volume/drivers/san/hp/hp_3par_common.py:252
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "Spouštění příkazu (SSH): %s"

#: cinder/utils.py:240 cinder/openstack/common/processutils.py:220
msgid "Environment not supported over SSH"
msgstr "Prostředí není podporováno přes SSH"

#: cinder/utils.py:244 cinder/openstack/common/processutils.py:224
msgid "process_input not supported over SSH"
msgstr "process_input není podporován přes SSH"

#: cinder/utils.py:313 cinder/volume/drivers/huawei/huawei_iscsi.py:95
msgid "Specify a password or private_key"
msgstr ""

#: cinder/utils.py:329 cinder/volume/drivers/huawei/huawei_iscsi.py:103
#, python-format
msgid "Error connecting via ssh: %s"
msgstr ""

#: cinder/utils.py:370
#, python-format
msgid "debug in callback: %s"
msgstr "ladění ve zpětném volání: %s"

#: cinder/utils.py:529
#, python-format
msgid "Link Local address is not found.:%s"
msgstr "Adresa místního spojení nenalezena.: %s"

#: cinder/utils.py:532
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr "Nelze získat IP místního spojení %(interface)s :%(ex)s"

#: cinder/utils.py:566
#, python-format
msgid "Invalid backend: %s"
msgstr "Neplatná podpůrná vrstva: %s"

#: cinder/utils.py:577
#, python-format
msgid "backend %s"
msgstr "podpůrná vrstva: %s"

#: cinder/utils.py:627
msgid "in looping call"
msgstr "v opakujícím volání"

#: cinder/utils.py:798
#, python-format
msgid "Expected object of type: %s"
msgstr "Očekáván objekt typu: %s"

#: cinder/utils.py:888
#, python-format
msgid "timefunc: '%(name)s' took %(total_time).2f secs"
msgstr "timefunc: '%(name)s' trvalo %(total_time).2f sek"

#: cinder/utils.py:1066
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: cinder/wsgi.py:121
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: cinder/wsgi.py:124
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: cinder/wsgi.py:127
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: cinder/wsgi.py:130
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: cinder/wsgi.py:163
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: cinder/wsgi.py:207
#, fuzzy, python-format
msgid "Started %(name)s on %(_host)s:%(_port)s"
msgstr "%(name)s spuštěno v %(host)s:%(port)s"

#: cinder/wsgi.py:226
msgid "Stopping WSGI server."
msgstr "Zastavování serveru WSGI."

#: cinder/wsgi.py:240
msgid "WSGI server has stopped."
msgstr "Server WSGI byl zastaven."

#: cinder/wsgi.py:309
msgid "You must implement __call__"
msgstr "Musíte zavést __call__"

#: cinder/api/auth.py:26
msgid ""
"cinder.api.auth:CinderKeystoneContext is deprecated. Please use "
"cinder.api.middleware.auth:CinderKeystoneContext instead."
msgstr ""

#: cinder/api/auth.py:34
msgid ""
"cinder.api.auth:pipeline_factory is deprecated. Please use "
"cinder.api.middleware.auth:pipeline_factory instead."
msgstr ""

#: cinder/api/common.py:64 cinder/api/common.py:98 cinder/volume/api.py:392
msgid "limit param must be an integer"
msgstr "parametr limit musí být celé číslo"

#: cinder/api/common.py:67 cinder/api/common.py:102 cinder/volume/api.py:389
msgid "limit param must be positive"
msgstr "parametr limit musí být kladný"

#: cinder/api/common.py:92
msgid "offset param must be an integer"
msgstr "parametr offset musí být celé číslo"

#: cinder/api/common.py:106
msgid "offset param must be positive"
msgstr "parametr offset musí být kladný"

#: cinder/api/common.py:134
#, python-format
msgid "marker [%s] not found"
msgstr "značka [%s] nenalezena"

#: cinder/api/common.py:161
#, python-format
msgid "href %s does not contain version"
msgstr "href %s neobsahuje verzi"

#: cinder/api/extensions.py:185
msgid "Initializing extension manager."
msgstr "Zavádění správce rozšíření."

#: cinder/api/extensions.py:200
#, python-format
msgid "Loaded extension: %s"
msgstr "Načteno rozšíření: %s"

#: cinder/api/extensions.py:238
#, python-format
msgid "Ext name: %s"
msgstr "Název roz: %s"

#: cinder/api/extensions.py:239
#, python-format
msgid "Ext alias: %s"
msgstr "Přezdívká roz: %s"

#: cinder/api/extensions.py:240
#, python-format
msgid "Ext description: %s"
msgstr "Popis roz: %s"

#: cinder/api/extensions.py:242
#, python-format
msgid "Ext namespace: %s"
msgstr "Jmenný prostor roz: %s"

#: cinder/api/extensions.py:243
#, python-format
msgid "Ext updated: %s"
msgstr "Roz aktualizováno: %s"

#: cinder/api/extensions.py:245
#, python-format
msgid "Exception loading extension: %s"
msgstr "Výjimka při načítání rozšíření: %s"

#: cinder/api/extensions.py:259
#, python-format
msgid "Loading extension %s"
msgstr "Načítání rozšíření %s"

#: cinder/api/extensions.py:265
#, python-format
msgid "Calling extension factory %s"
msgstr "Volání továrny rozšíření %s"

#: cinder/api/extensions.py:279
#, python-format
msgid "osapi_volume_extension is set to deprecated path: %s"
msgstr ""

#: cinder/api/extensions.py:281
#, python-format
msgid ""
"Please set your flag or cinder.conf settings for osapi_volume_extension "
"to: %s"
msgstr ""

#: cinder/api/extensions.py:290
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr "Nelze načít rozšížení %(ext_factory)s: %(exc)s"

#: cinder/api/extensions.py:359
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr "Nelze načíst rozšíření %(classpath)s: %(exc)s"

#: cinder/api/extensions.py:384
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr "Nelze načíst rozšíření %(ext_name)s: %(exc)s"

#: cinder/api/sizelimit.py:25
msgid ""
"cinder.api.sizelimit:RequestBodySizeLimiter is deprecated. Please use "
"cinder.api.middleware.sizelimit:RequestBodySizeLimiter instead"
msgstr ""

#: cinder/api/xmlutil.py:268
msgid "element is not a child"
msgstr "prvek není podřazený"

#: cinder/api/xmlutil.py:417
msgid "root element selecting a list"
msgstr "kořenový prvek volí seznam"

#: cinder/api/xmlutil.py:740
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""
"Neshoda stromu šablony; přidávání sluhy %(slavetag)s k pánovi "
"%(mastertag)s"

#: cinder/api/xmlutil.py:861
msgid "subclasses must implement construct()!"
msgstr "podtřídy musí zavádět construct()!"

#: cinder/api/contrib/admin_actions.py:80
#, python-format
msgid "Updating %(resource)s '%(id)s' with '%(update)r'"
msgstr ""

#: cinder/api/contrib/backups.py:128
#, python-format
msgid "show called for member %s"
msgstr ""

#: cinder/api/contrib/backups.py:140
#, python-format
msgid "delete called for member %s"
msgstr ""

#: cinder/api/contrib/backups.py:143
#, python-format
msgid "Delete backup with id: %s"
msgstr ""

#: cinder/api/contrib/backups.py:185
#, python-format
msgid "Creating new backup %s"
msgstr ""

#: cinder/api/contrib/backups.py:195 cinder/api/contrib/backups.py:232
#: cinder/api/contrib/volume_transfer.py:159
#: cinder/api/contrib/volume_transfer.py:195
msgid "Incorrect request body format"
msgstr "Nsprávný formát těla požadavku"

#: cinder/api/contrib/backups.py:201
#, python-format
msgid "Creating backup of volume %(volume_id)s in container %(container)s"
msgstr ""

#: cinder/api/contrib/backups.py:222
#, python-format
msgid "Restoring backup %(backup_id)s (%(body)s)"
msgstr ""

#: cinder/api/contrib/backups.py:236
#, python-format
msgid "Restoring backup %(backup_id)s to volume %(volume_id)s"
msgstr ""

#: cinder/api/contrib/extended_snapshot_attributes.py:60
#, fuzzy
msgid "Snapshot not found."
msgstr "Server nenalezen."

#: cinder/api/contrib/hosts.py:86 cinder/api/openstack/wsgi.py:158
msgid "cannot understand XML"
msgstr "XML nelze porozumět"

#: cinder/api/contrib/hosts.py:136
#, fuzzy, python-format
msgid "Host '%s' could not be found."
msgstr "Hostitel %(host)s nemohl být nalezen."

#: cinder/api/contrib/hosts.py:165
#, python-format
msgid "Invalid status: '%s'"
msgstr "Neplatný stav: '%s'"

#: cinder/api/contrib/hosts.py:168
#, python-format
msgid "Invalid update setting: '%s'"
msgstr "Neplatné nastavení aktualizace: '%s'"

#: cinder/api/contrib/hosts.py:180
#, python-format
msgid "Setting host %(host)s to %(state)s."
msgstr "Nastavování hostitele %(host)s na %(state)s."

#: cinder/api/contrib/hosts.py:206
msgid "Describe-resource is admin only functionality"
msgstr "Describe-resource je funkce pouze pro správce"

#: cinder/api/contrib/hosts.py:214
msgid "Host not found"
msgstr ""

#: cinder/api/contrib/quotas.py:63
msgid "Quota limit must be -1 or greater."
msgstr ""

#: cinder/api/contrib/scheduler_hints.py:38
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: cinder/api/contrib/types_extra_specs.py:102
#, fuzzy
msgid "Request body empty"
msgstr "Nsprávný formát těla požadavku"

#: cinder/api/contrib/types_extra_specs.py:106
#: cinder/api/v1/snapshot_metadata.py:77 cinder/api/v1/volume_metadata.py:77
#: cinder/api/v2/snapshot_metadata.py:77
msgid "Request body and URI mismatch"
msgstr "Neshoda s tělem požadavku a URI"

#: cinder/api/contrib/types_extra_specs.py:109
#: cinder/api/v1/snapshot_metadata.py:81 cinder/api/v1/volume_metadata.py:81
#: cinder/api/v2/snapshot_metadata.py:81
msgid "Request body contains too many items"
msgstr "Tělo požadavku obsahuje příliš mnoho položek"

#: cinder/api/contrib/volume_actions.py:157
msgid "Invalid request body"
msgstr "Neplatné tělo požadavku"

#: cinder/api/contrib/volume_actions.py:161
msgid "No image_name was specified in request."
msgstr ""

#: cinder/api/contrib/volume_transfer.py:133
msgid "Listing volume transfers"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:149
#, fuzzy, python-format
msgid "Creating new volume transfer %s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/api/contrib/volume_transfer.py:164
#, fuzzy, python-format
msgid "Creating transfer of volume %s"
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/api/contrib/volume_transfer.py:185
#, python-format
msgid "Accepting volume transfer %s"
msgstr ""

#: cinder/api/contrib/volume_transfer.py:198
#, fuzzy, python-format
msgid "Accepting transfer %s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/api/contrib/volume_transfer.py:219
#, python-format
msgid "Delete transfer with id: %s"
msgstr ""

#: cinder/api/middleware/fault.py:45
#, python-format
msgid "Caught error: %s"
msgstr "Zachycena chyba: %s"

#: cinder/api/middleware/fault.py:54 cinder/api/openstack/wsgi.py:896
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr "%(url)s vrácena s HTTP %(status)d"

#: cinder/api/middleware/sizelimit.py:56 cinder/api/middleware/sizelimit.py:65
#: cinder/api/middleware/sizelimit.py:79
msgid "Request is too large."
msgstr ""

#: cinder/api/openstack/__init__.py:73
msgid "Must specify an ExtensionManager class"
msgstr "Musí být určena třída ExtensionManager"

#: cinder/api/openstack/__init__.py:84
#, python-format
msgid "Extended resource: %s"
msgstr "Rozšířený zdroj: %s"

#: cinder/api/openstack/__init__.py:108
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr "Rozšíření %(ext_name)s: nelze rozšířit %(collection)s: Žádný takový zdroj"

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid "Extension %(ext_name)s extending resource: %(collection)s"
msgstr "Rozšíření %(ext_name)s: rozšiřování zdroje %(collection)s"

#: cinder/api/openstack/__init__.py:130
msgid ""
"cinder.api.openstack:FaultWrapper is deprecated. Please use "
"cinder.api.middleware.fault:FaultWrapper instead."
msgstr ""

#: cinder/api/openstack/urlmap.py:25
msgid ""
"cinder.api.openstack.urlmap:urlmap_factory is deprecated. Please use "
"cinder.api.urlmap:urlmap_factory instead."
msgstr ""

#: cinder/api/openstack/wsgi.py:134 cinder/api/openstack/wsgi.py:547
msgid "cannot understand JSON"
msgstr "JSON nelze porozumět"

#: cinder/api/openstack/wsgi.py:552
msgid "too many body keys"
msgstr "příliš mnoho klíčů těla"

#: cinder/api/openstack/wsgi.py:591
#, fuzzy, python-format
msgid "Exception handling resource: %s"
msgstr "Rozšířený zdroj: %s"

#: cinder/api/openstack/wsgi.py:596
#, python-format
msgid "Fault thrown: %s"
msgstr "Vyvolána chyba: %s"

#: cinder/api/openstack/wsgi.py:599
#, python-format
msgid "HTTP exception thrown: %s"
msgstr "Vyvolána výjimka HTTP: %s"

#: cinder/api/openstack/wsgi.py:707
msgid "Unrecognized Content-Type provided in request"
msgstr "V požadavku zadán nerozpoznaný Content-Type"

#: cinder/api/openstack/wsgi.py:711
msgid "No Content-Type provided in request"
msgstr "V požadavku nezadán Content-Type"

#: cinder/api/openstack/wsgi.py:715
msgid "Empty body provided in request"
msgstr "V požadavku zadáno prázdné tělo"

#: cinder/api/openstack/wsgi.py:826
#, python-format
msgid "There is no such action: %s"
msgstr "Žádná taková činnost: %s"

#: cinder/api/openstack/wsgi.py:829 cinder/api/openstack/wsgi.py:842
#: cinder/api/v1/snapshot_metadata.py:55 cinder/api/v1/snapshot_metadata.py:73
#: cinder/api/v1/snapshot_metadata.py:98 cinder/api/v1/snapshot_metadata.py:123
#: cinder/api/v1/volume_metadata.py:55 cinder/api/v1/volume_metadata.py:73
#: cinder/api/v1/volume_metadata.py:98 cinder/api/v1/volume_metadata.py:123
#: cinder/api/v2/snapshot_metadata.py:55 cinder/api/v2/snapshot_metadata.py:73
#: cinder/api/v2/snapshot_metadata.py:98 cinder/api/v2/snapshot_metadata.py:123
msgid "Malformed request body"
msgstr "Poškozené tělo požadavku"

#: cinder/api/openstack/wsgi.py:839
msgid "Unsupported Content-Type"
msgstr "Nepodporovaný Content-Type"

#: cinder/api/openstack/wsgi.py:851
msgid "Malformed request url"
msgstr "Poškozená url požadavku"

#: cinder/api/openstack/wsgi.py:899
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr "%(url)s vrátilo chybu: %(e)s"

#: cinder/api/openstack/volume/__init__.py:25
msgid ""
"cinder.api.openstack.volume:APIRouter is deprecated. Please use "
"cinder.api.v1.router:APIRouter instead."
msgstr ""

#: cinder/api/openstack/volume/versions.py:26
msgid ""
"cinder.api.openstack.volume.versions.Versions is deprecated. Please use "
"cinder.api.versions.Versions instead."
msgstr ""

#: cinder/api/v1/limits.py:144 cinder/api/v2/limits.py:144
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""
"Pouze %(value)s požadavky %(verb)s mohou být provedeny pro %(uri)s "
"každých %(unit_string)s."

#: cinder/api/v1/limits.py:270 cinder/api/v2/limits.py:270
msgid "This request was rate-limited."
msgstr "Tento požadavek má omezen množství."

#: cinder/api/v1/snapshot_metadata.py:39 cinder/api/v1/snapshot_metadata.py:119
#: cinder/api/v1/snapshot_metadata.py:158 cinder/api/v2/snapshot_metadata.py:39
#: cinder/api/v2/snapshot_metadata.py:119
#: cinder/api/v2/snapshot_metadata.py:158
#, fuzzy
msgid "snapshot does not exist"
msgstr "Instance neexistuje"

#: cinder/api/v1/snapshot_metadata.py:141
#: cinder/api/v1/snapshot_metadata.py:151 cinder/api/v1/volume_metadata.py:141
#: cinder/api/v1/volume_metadata.py:151 cinder/api/v2/snapshot_metadata.py:141
#: cinder/api/v2/snapshot_metadata.py:151
msgid "Metadata item was not found"
msgstr "Položka metadat nenalezena"

#: cinder/api/v1/snapshots.py:119 cinder/api/v2/snapshots.py:119
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: cinder/api/v1/snapshots.py:169 cinder/api/v2/snapshots.py:175
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: cinder/api/v1/snapshots.py:173 cinder/api/v2/snapshots.py:184
#, python-format
msgid "Invalid value '%s' for force. "
msgstr ""

#: cinder/api/v1/volume_metadata.py:39 cinder/api/v1/volume_metadata.py:119
#: cinder/api/v1/volume_metadata.py:158
#, fuzzy
msgid "volume does not exist"
msgstr "Server neexistuje"

#: cinder/api/v1/volumes.py:102
#, python-format
msgid "vol=%s"
msgstr ""

#: cinder/api/v1/volumes.py:233 cinder/api/v2/volumes.py:173
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: cinder/api/v1/volumes.py:275 cinder/api/v1/volumes.py:279
#: cinder/api/v2/volumes.py:232 cinder/api/v2/volumes.py:236
msgid "Invalid imageRef provided."
msgstr "Zadáno neplatné imageRef."

#: cinder/api/v1/volumes.py:337 cinder/api/v2/volumes.py:296
#, python-format
msgid "Create volume of %s GB"
msgstr "Vytvořit svazek o %s GB"

#: cinder/api/v1/volumes.py:416
#, fuzzy, python-format
msgid "Removing options '%(bad_options)s' from query"
msgstr "Odstraňování voleb '%(unk_opt_str)s' z fronty"

#: cinder/api/v2/volumes.py:384
#, fuzzy, python-format
msgid "Removing options '%s' from query"
msgstr "Odstraňování voleb '%(unk_opt_str)s' z fronty"

#: cinder/backup/api.py:62
#, fuzzy
msgid "Backup status must be available or error"
msgstr "Obraz musí být dostupný"

#: cinder/backup/api.py:89
#, fuzzy
msgid "Volume to be backed up must be available"
msgstr "Obraz musí být dostupný"

#: cinder/backup/api.py:124
#, fuzzy
msgid "Backup status must be available"
msgstr "Obraz musí být dostupný"

#: cinder/backup/api.py:129
msgid "Backup to be restored has invalid size"
msgstr ""

#: cinder/backup/api.py:138
#, python-format
msgid "Creating volume of %(size)s GB for restore of backup %(backup_id)s"
msgstr ""

#: cinder/backup/api.py:152
#, python-format
msgid ""
"volume size %(volume_size)d is too small to restore backup of size "
"%(size)d."
msgstr ""

#: cinder/backup/api.py:157
#, fuzzy
msgid "Volume to be restored to must be available"
msgstr "Obraz musí být dostupný"

#: cinder/backup/api.py:163
msgid "Volume to be restored to is smaller than the backup to be restored"
msgstr ""

#: cinder/backup/api.py:167
#, python-format
msgid "Overwriting volume %(volume_id)s with restore of backup %(backup_id)s"
msgstr ""

#: cinder/backup/manager.py:80
msgid "Cleaning up incomplete backup operations"
msgstr ""

#: cinder/backup/manager.py:84
#, python-format
msgid "Resetting volume %s to available (was backing-up)"
msgstr ""

#: cinder/backup/manager.py:88
#, python-format
msgid "Resetting volume %s to error_restoring (was restoring-backup)"
msgstr ""

#: cinder/backup/manager.py:99
#, python-format
msgid "Resetting backup %s to error (was creating)"
msgstr ""

#: cinder/backup/manager.py:105
#, python-format
msgid "Resetting backup %s to available (was restoring)"
msgstr ""

#: cinder/backup/manager.py:110
#, python-format
msgid "Resuming delete on backup: %s"
msgstr ""

#: cinder/backup/manager.py:120
#, python-format
msgid "create_backup started, backup: %(backup_id)s for volume: %(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:129
#, python-format
msgid ""
"create_backup aborted, expected volume status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:138
#, python-format
msgid ""
"create_backup aborted, expected backup status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:161
#, python-format
msgid "create_backup finished. backup: %s"
msgstr ""

#: cinder/backup/manager.py:167
#, python-format
msgid ""
"restore_backup started, restoring backup: %(backup_id)s to volume: "
"%(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:176
#, python-format
msgid ""
"restore_backup aborted, expected volume status %(expected_status)s but "
"got %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:184
#, python-format
msgid ""
"restore_backup aborted, expected backup status %(expected_status)s but "
"got %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:200
#, python-format
msgid ""
"restore_backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to "
"create this backup [%(backup_service)s]"
msgstr ""

#: cinder/backup/manager.py:221
#, python-format
msgid ""
"restore_backup finished, backup: %(backup_id)s restored to volume: "
"%(volume_id)s"
msgstr ""

#: cinder/backup/manager.py:229
#, python-format
msgid "delete_backup started, backup: %s"
msgstr ""

#: cinder/backup/manager.py:235
#, python-format
msgid ""
"delete_backup aborted, expected backup status %(expected_status)s but got"
" %(actual_status)s"
msgstr ""

#: cinder/backup/manager.py:245
#, python-format
msgid ""
"delete_backup aborted, the backup service currently configured "
"[%(configured_service)s] is not the backup service that was used to "
"create this backup [%(backup_service)s]"
msgstr ""

#: cinder/backup/manager.py:265
#, python-format
msgid "delete_backup finished, backup %s deleted"
msgstr ""

#: cinder/backup/services/swift.py:96
#, python-format
msgid "unsupported compression algorithm: %s"
msgstr ""

#: cinder/backup/services/swift.py:117
#, python-format
msgid "_check_container_exists: container: %s"
msgstr ""

#: cinder/backup/services/swift.py:122
#, fuzzy, python-format
msgid "container %s does not exist"
msgstr "Instance neexistuje"

#: cinder/backup/services/swift.py:127
#, fuzzy, python-format
msgid "container %s exists"
msgstr "Instance neexistuje"

#: cinder/backup/services/swift.py:133
#, python-format
msgid "_create_container started, container: %(container)s,backup: %(backup_id)s"
msgstr ""

#: cinder/backup/services/swift.py:148
#, python-format
msgid "_generate_swift_object_name_prefix: %s"
msgstr ""

#: cinder/backup/services/swift.py:159
#, fuzzy, python-format
msgid "generated object list: %s"
msgstr "Očekáván objekt typu: %s"

#: cinder/backup/services/swift.py:169
#, python-format
msgid ""
"_write_metadata started, container name: %(container)s, metadata "
"filename: %(filename)s"
msgstr ""

#: cinder/backup/services/swift.py:184
#, python-format
msgid ""
"error writing metadata file to swift, MD5 of metadata file in swift "
"[%(etag)s] is not the same as MD5 of metadata file sent to swift "
"[%(md5)s]"
msgstr ""

#: cinder/backup/services/swift.py:188
msgid "_write_metadata finished"
msgstr ""

#: cinder/backup/services/swift.py:193
#, python-format
msgid ""
"_read_metadata started, container name: %(container)s, metadata filename:"
" %(filename)s"
msgstr ""

#: cinder/backup/services/swift.py:197
#, python-format
msgid "_read_metadata finished (%s)"
msgstr ""

#: cinder/backup/services/swift.py:207
#, fuzzy, python-format
msgid "volume size %d is invalid."
msgstr "Požadavek je neplatný."

#: cinder/backup/services/swift.py:221
#, python-format
msgid ""
"starting backup of volume: %(volume_id)s to swift, volume size: "
"%(volume_size_bytes)d, swift object names prefix %(object_prefix)s, "
"availability zone: %(availability_zone)s"
msgstr ""

#: cinder/backup/services/swift.py:237
msgid "reading chunk of data from volume"
msgstr ""

#: cinder/backup/services/swift.py:244
#, python-format
msgid ""
"compressed %(data_size_bytes)d bytes of data to %(comp_size_bytes)d bytes"
" using %(algorithm)s"
msgstr ""

#: cinder/backup/services/swift.py:248
msgid "not compressing data"
msgstr ""

#: cinder/backup/services/swift.py:252
msgid "About to put_object"
msgstr ""

#: cinder/backup/services/swift.py:257
#, python-format
msgid "swift MD5 for %(object_name)s: %(etag)s"
msgstr ""

#: cinder/backup/services/swift.py:260
#, python-format
msgid "backup MD5 for %(object_name)s: %(md5)s"
msgstr ""

#: cinder/backup/services/swift.py:262
#, python-format
msgid ""
"error writing object to swift, MD5 of object in swift %(etag)s is not the"
" same as MD5 of object sent to swift %(md5)s"
msgstr ""

#: cinder/backup/services/swift.py:268
msgid "Calling eventlet.sleep(0)"
msgstr ""

#: cinder/backup/services/swift.py:276
#, python-format
msgid "backup %s finished."
msgstr ""

#: cinder/backup/services/swift.py:281
#, python-format
msgid "v1 swift volume backup restore of %s started"
msgstr ""

#: cinder/backup/services/swift.py:287
#, python-format
msgid "metadata_object_names = %s"
msgstr ""

#: cinder/backup/services/swift.py:293
msgid ""
"restore_backup aborted, actual swift object list in swift does not match "
"object list stored in metadata"
msgstr ""

#: cinder/backup/services/swift.py:299
#, python-format
msgid ""
"restoring object from swift. backup: %(backup_id)s, container: "
"%(container)s, swift object name: %(object_name)s, volume: %(volume_id)s"
msgstr ""

#: cinder/backup/services/swift.py:309
#, python-format
msgid "decompressing data using %s algorithm"
msgstr ""

#: cinder/backup/services/swift.py:323
#, python-format
msgid "v1 swift volume backup restore of %s finished"
msgstr ""

#: cinder/backup/services/swift.py:331
#, python-format
msgid ""
"starting restore of backup %(object_prefix)s from swift container: "
"%(container)s, to volume %(volume_id)s, backup: %(backup_id)s"
msgstr ""

#: cinder/backup/services/swift.py:339
#, python-format
msgid "Restoring swift backup version %s"
msgstr ""

#: cinder/backup/services/swift.py:344
#, python-format
msgid "No support to restore swift backup version %s"
msgstr ""

#: cinder/backup/services/swift.py:348
#, python-format
msgid "restore %(backup_id)s to %(volume_id)s finished."
msgstr ""

#: cinder/backup/services/swift.py:362
msgid "swift error while listing objects, continuing with delete"
msgstr ""

#: cinder/backup/services/swift.py:371
#, python-format
msgid "swift error while deleting object %s, continuing with delete"
msgstr ""

#: cinder/backup/services/swift.py:374
#, python-format
msgid "deleted swift object: %(swift_object_name)s in container: %(container)s"
msgstr ""

#: cinder/backup/services/swift.py:380
#, python-format
msgid "delete %s finished"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:155
#, python-format
msgid "Creating iscsi_target for: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:174 cinder/brick/iscsi/iscsi.py:269
#, fuzzy, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/brick/iscsi/iscsi.py:185
#, python-format
msgid ""
"Failed to create iscsi target for volume id:%(vol_id)s. Please ensure "
"your tgtd config file contains 'include %(volumes_dir)s/*'"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:196
#, python-format
msgid "Removing iscsi_target for: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:213
#, fuzzy, python-format
msgid "Failed to remove iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/brick/iscsi/iscsi.py:223 cinder/brick/iscsi/iscsi.py:440
msgid "valid iqn needed for show_target"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:276
#, python-format
msgid "Removing iscsi_target for volume: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:362
msgid "rtstool is not installed correctly"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:382
#, python-format
msgid "Creating iscsi_target for volume: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:406 cinder/brick/iscsi/iscsi.py:415
#, fuzzy, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/brick/iscsi/iscsi.py:422
#, python-format
msgid "Removing iscsi_target: %s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:432
#, fuzzy, python-format
msgid "Failed to remove iscsi target for volume id:%(vol_id)s."
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/brick/iscsi/iscsi.py:461
#, python-format
msgid "Failed to add initiator iqn %s to target"
msgstr ""

#: cinder/brick/local_dev/lvm.py:35
#, python-format
msgid "Unable to find Volume Group: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:41
#, fuzzy, python-format
msgid "Failed to create Volume Group: %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/brick/local_dev/lvm.py:75
msgid "Error creating Volume Group"
msgstr ""

#: cinder/brick/local_dev/lvm.py:76
#, python-format
msgid "Cmd     :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:77
#, python-format
msgid "StdOut  :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:78
#, python-format
msgid "StdErr  :%s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:82
#, python-format
msgid "Unable to locate Volume Group %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:265
#, python-format
msgid "Unable to find VG: %s"
msgstr ""

#: cinder/brick/local_dev/lvm.py:284
msgid ""
"Requested to setup thin provisioning, however current LVM version does "
"not support it."
msgstr ""

#: cinder/brick/local_dev/lvm.py:337
#, fuzzy, python-format
msgid "Unable to find LV: %s"
msgstr "Nelze použít globální roli %(role_id)s"

#: cinder/common/sqlalchemyutils.py:68
#: cinder/openstack/common/db/sqlalchemy/utils.py:72
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/common/sqlalchemyutils.py:116
#: cinder/openstack/common/db/sqlalchemy/utils.py:120
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: cinder/db/sqlalchemy/api.py:65
msgid "Use of empty request context is deprecated"
msgstr ""

#: cinder/db/sqlalchemy/api.py:192
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: cinder/db/sqlalchemy/api.py:800
#, python-format
msgid "Change will make usage less than 0 for the following resources: %(unders)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:1819 cinder/db/sqlalchemy/api.py:1845
#, python-format
msgid "No backend config with id %(sm_backend_id)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:1902
#, python-format
msgid "No sm_flavor called %(sm_flavor)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:1946
#, python-format
msgid "No sm_volume with id %(volume_id)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2009
#, python-format
msgid "No backup with id %(backup_id)s"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2092
#, fuzzy
msgid "Volume must be available"
msgstr "Obraz musí být dostupný"

#: cinder/db/sqlalchemy/api.py:2116
#, python-format
msgid "Volume in unexpected state %s, expected awaiting-transfer"
msgstr ""

#: cinder/db/sqlalchemy/api.py:2139
#, python-format
msgid ""
"Transfer %(transfer_id)s: Volume id %(volume_id)s in unexpected state "
"%(status)s, expected awaiting-transfer"
msgstr ""

#: cinder/db/sqlalchemy/migration.py:72
msgid "version should be an integer"
msgstr ""

#: cinder/db/sqlalchemy/migration.py:99
msgid "Upgrade DB using Essex release first."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/001_cinder_init.py:242
msgid "Exception while creating table."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/001_cinder_init.py:271
msgid "Downgrade from initial Cinder install is unsupported."
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:56
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:85
#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:123
#: cinder/db/sqlalchemy/migrate_repo/versions/008_add_backup.py:82
#: cinder/db/sqlalchemy/migrate_repo/versions/009_add_snapshot_metadata_table.py:47
#: cinder/db/sqlalchemy/migrate_repo/versions/010_add_transfers_table.py:58
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:135
msgid "quota_classes table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:142
msgid "quota_usages table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/002_quota_class.py:149
msgid "reservations table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/003_glance_metadata.py:62
msgid "Exception while creating table 'volume_glance_metadata'"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/003_glance_metadata.py:77
msgid "volume_glance_metadata table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/008_add_backup.py:94
msgid "backups table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/009_add_snapshot_metadata_table.py:60
msgid "snapshot_metadata table not dropped"
msgstr ""

#: cinder/db/sqlalchemy/migrate_repo/versions/010_add_transfers_table.py:71
msgid "transfers table not dropped"
msgstr ""

#: cinder/image/glance.py:153
#, python-format
msgid "Error contacting glance server '%(netloc)s' for '%(method)s', %(extra)s."
msgstr ""

#: cinder/image/image_utils.py:119
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: cinder/image/image_utils.py:233
msgid "'qemu-img info' parsing failed."
msgstr ""

#: cinder/image/image_utils.py:240
#, python-format
msgid "fmt=%(fmt)s backed by:%(backing_file)s"
msgstr ""

#: cinder/image/image_utils.py:257
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: cinder/image/image_utils.py:287
#, python-format
msgid "Converted to %(f1)s, but format is now %(f2)s"
msgstr ""

#: cinder/openstack/common/exception.py:104
msgid "Uncaught exception"
msgstr ""

#: cinder/openstack/common/excutils.py:48
#, fuzzy, python-format
msgid "Original exception being dropped: %s"
msgstr "Původní výjimka je zahozena"

#: cinder/openstack/common/fileutils.py:64
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: cinder/openstack/common/lockutils.py:102
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: cinder/openstack/common/lockutils.py:189
#, fuzzy, python-format
msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
msgstr "Získán semafor \"%(lock)s\" pro zámek metody \"%(method)s\""

#: cinder/openstack/common/lockutils.py:200
#, fuzzy, python-format
msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
msgstr "Pokus o získání zámku souboru \"%(lock)s\" pro zámek metody \"%(method)s\""

#: cinder/openstack/common/lockutils.py:227
#, fuzzy, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr "Získán zámek souboru \"%(lock)s\" pro zámek metody \"%(method)s\""

#: cinder/openstack/common/lockutils.py:235
#, fuzzy, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
msgstr "Získán zámek souboru \"%(lock)s\" pro zámek metody \"%(method)s\""

#: cinder/openstack/common/log.py:244
#, fuzzy, python-format
msgid "Deprecated: %s"
msgstr "obdrženo: %s"

#: cinder/openstack/common/log.py:336
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: cinder/openstack/common/log.py:386
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "zařízení záznamu systému musí být jedno z: %s"

#: cinder/openstack/common/log.py:556
#, fuzzy, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Třída %(fullname)s je zastaralá: %(msg)s"

#: cinder/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: cinder/openstack/common/loopingcall.py:91
#, fuzzy
msgid "in fixed duration looping call"
msgstr "v opakujícím volání"

#: cinder/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: cinder/openstack/common/loopingcall.py:138
#, fuzzy
msgid "in dynamic looping call"
msgstr "v opakujícím volání"

#: cinder/openstack/common/periodic_task.py:42
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: cinder/openstack/common/periodic_task.py:133
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr ""

#: cinder/openstack/common/periodic_task.py:138
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr ""

#: cinder/openstack/common/periodic_task.py:176
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr "Spuštění pravidelné úlohy %(full_task_name)s"

#: cinder/openstack/common/periodic_task.py:184
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "Chyba při %(full_task_name)s: %(e)s"

#: cinder/openstack/common/policy.py:149
#, python-format
msgid ""
"Inheritance-based rules are deprecated; use the default brain instead of "
"%s."
msgstr ""

#: cinder/openstack/common/policy.py:163
#, python-format
msgid "Failed to understand rule %(match)r"
msgstr ""

#: cinder/openstack/common/policy.py:173
#, python-format
msgid "Inheritance-based rules are deprecated; update _check_%s"
msgstr ""

#: cinder/openstack/common/policy.py:180
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: cinder/openstack/common/service.py:262
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: cinder/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: cinder/openstack/common/strutils.py:182
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: cinder/openstack/common/strutils.py:189
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: cinder/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/session.py:487
msgid "DB exception wrapped."
msgstr "Vyjímka DB zabalena."

#: cinder/openstack/common/db/sqlalchemy/session.py:538
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/session.py:610
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: cinder/openstack/common/db/sqlalchemy/utils.py:33
msgid "Sort key supplied was not valid."
msgstr ""

#: cinder/openstack/common/notifier/api.py:125
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: cinder/openstack/common/notifier/api.py:141
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: cinder/openstack/common/notifier/api.py:171
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: cinder/openstack/common/notifier/rabbit_notifier.py:27
msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
msgstr ""

#: cinder/openstack/common/notifier/rpc_notifier.py:45
#: cinder/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: cinder/openstack/common/rpc/__init__.py:106
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:200
#, python-format
msgid "no calling threads waiting for msg_id : %s, message : %s"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:208
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:291
#, python-format
msgid "unpacked context: %s"
msgstr "rozbalený kontext: %s"

#: cinder/openstack/common/rpc/amqp.py:337
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:406
#, python-format
msgid "received %s"
msgstr "obdrženo: %s"

#: cinder/openstack/common/rpc/amqp.py:414
#, python-format
msgid "no method for message: %s"
msgstr "pro zprávu není metoda: %s"

#: cinder/openstack/common/rpc/amqp.py:415
#, python-format
msgid "No method for message: %s"
msgstr "Pro zprávu není metoda: %s"

#: cinder/openstack/common/rpc/amqp.py:443
#: cinder/openstack/common/rpc/impl_zmq.py:286
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:451
#: cinder/openstack/common/rpc/impl_zmq.py:292
msgid "Exception during message handling"
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:586
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:589
#, python-format
msgid "MSG_ID is %s"
msgstr "MSG_ID je %s"

#: cinder/openstack/common/rpc/amqp.py:623
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:632
msgid "Making asynchronous fanout cast..."
msgstr ""

#: cinder/openstack/common/rpc/amqp.py:660
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: cinder/openstack/common/rpc/common.py:74
#, fuzzy
msgid "An unknown RPC related exception occurred."
msgstr "Vyskytla se neočekávaná výjimka."

#: cinder/openstack/common/rpc/common.py:104
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: cinder/openstack/common/rpc/common.py:121
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: cinder/openstack/common/rpc/common.py:137
#: cinder/openstack/common/rpc/common.py:138
#: cinder/openstack/common/rpc/common.py:139
msgid "<unknown>"
msgstr ""

#: cinder/openstack/common/rpc/common.py:143
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: cinder/openstack/common/rpc/common.py:147
msgid "Invalid reuse of an RPC connection."
msgstr "Neplatné znovu použití připojení RPC."

#: cinder/openstack/common/rpc/common.py:151
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: cinder/openstack/common/rpc/common.py:156
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: cinder/openstack/common/rpc/common.py:280
#, python-format
msgid "Failed to sanitize %(item)s. Key error %(err)s"
msgstr ""

#: cinder/openstack/common/rpc/common.py:302
#, python-format
msgid "Returning exception %s to caller"
msgstr "Volajícímu je vrácena výjimka: %s"

#: cinder/openstack/common/rpc/impl_kombu.py:169
#: cinder/openstack/common/rpc/impl_qpid.py:133
msgid "Failed to process message... skipping it."
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:480
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:502
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:539
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:555
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:609
#: cinder/openstack/common/rpc/impl_qpid.py:403
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:627
#: cinder/openstack/common/rpc/impl_qpid.py:418
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:631
#: cinder/openstack/common/rpc/impl_qpid.py:422
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_kombu.py:670
#: cinder/openstack/common/rpc/impl_qpid.py:457
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:351
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:357
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:370
msgid "Re-established AMQP queues"
msgstr ""

#: cinder/openstack/common/rpc/impl_qpid.py:430
msgid "Error processing message.  Skipping it."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:97
msgid "JSON serialization failed."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:104
#, fuzzy, python-format
msgid "Deserializing: %s"
msgstr "Popis roz: %s"

#: cinder/openstack/common/rpc/impl_zmq.py:140
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:141
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:142
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:150
msgid "Could not open socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:162
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:204
msgid "You cannot recv on this socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:209
msgid "You cannot send on this socket."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:273
#, fuzzy, python-format
msgid "Running func with context: %s"
msgstr "rozbalený kontext: %s"

#: cinder/openstack/common/rpc/impl_zmq.py:311
msgid "Sending reply"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:345
msgid "RPC message did not include method."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:380
#, fuzzy
msgid "Registering reactor"
msgstr "Zrušení registrace obrazu %s"

#: cinder/openstack/common/rpc/impl_zmq.py:392
msgid "In reactor registered"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:407
msgid "Out reactor registered"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:411
msgid "Consuming socket"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:453
#, python-format
msgid "CONSUMER GOT %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:465
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:471
msgid "Topic contained dangerous characters."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:496
#, python-format
msgid "ROUTER RELAY-OUT SUCCEEDED %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:505
msgid "Topic socket file creation failed."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:510
#, python-format
msgid "ROUTER RELAY-OUT QUEUED %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:513
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:532
#, python-format
msgid "Could not create IPC directory %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:542
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:576
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:578
#, python-format
msgid "ROUTER RELAY-OUT %(data)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:600
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:628
msgid "Skipping topic registration. Already registered."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:635
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:687
msgid "Creating payload"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:700
msgid "Creating queue socket for reply waiter"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:713
msgid "Sending cast"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:716
msgid "Cast sent; Waiting reply"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:719
#, fuzzy, python-format
msgid "Received message: %s"
msgstr "obdrženo: %s"

#: cinder/openstack/common/rpc/impl_zmq.py:720
msgid "Unpacking response"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:729
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:736
#, fuzzy
msgid "RPC Message Invalid."
msgstr "Požadavek je neplatný."

#: cinder/openstack/common/rpc/impl_zmq.py:760
#, python-format
msgid "%(msg)s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:763
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:767
msgid "No matchmaker results. Not casting."
msgstr ""

#: cinder/openstack/common/rpc/impl_zmq.py:770
msgid "No match from matchmaker."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:53
msgid "Match not found by MatchMaker."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:89
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:239
#, python-format
msgid "Matchmaker unregistered: %s, %s"
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:250
msgid "Register before starting heartbeat."
msgstr ""

#: cinder/openstack/common/rpc/matchmaker.py:343
#: cinder/openstack/common/rpc/matchmaker.py:361
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: cinder/scheduler/chance.py:52 cinder/scheduler/simple.py:90
msgid "Is the appropriate service running?"
msgstr ""

#: cinder/scheduler/chance.py:57
#, fuzzy
msgid "Could not find another host"
msgstr "Nelze najít %s v požadavku."

#: cinder/scheduler/driver.py:89
msgid "Must implement a fallback schedule"
msgstr ""

#: cinder/scheduler/driver.py:93
msgid "Must implement schedule_create_volume"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:110
msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:128
#, python-format
msgid ""
"Error scheduling %(volume_id)s from last vol-service: %(last_host)s : "
"%(exc)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:157
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for volume %(volume_id)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:205
#, python-format
msgid "Filtered %(hosts)s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:211
#, python-format
msgid "Choosing %(best_host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:240
#, python-format
msgid "Ignoring %(service_name)s service update from %(host)s"
msgstr ""

#: cinder/scheduler/host_manager.py:244
#, python-format
msgid "Received %(service_name)s service update from %(host)s."
msgstr ""

#: cinder/scheduler/host_manager.py:267
#, python-format
msgid "volume service is down or disabled. (host: %s)"
msgstr ""

#: cinder/scheduler/manager.py:119
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: cinder/scheduler/scheduler_options.py:70
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: cinder/scheduler/scheduler_options.py:79
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: cinder/scheduler/simple.py:79
msgid "Not enough allocatable volume gigabytes remaining"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:37
msgid "Free capacity not set: volume node info collection broken."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:51
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail): "
"%(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/retry_filter.py:41
#, python-format
msgid "Host %(host)s %(pass_msg)s.  Previously tried hosts: %(hosts)s"
msgstr ""

#: cinder/tests/fake_driver.py:45 cinder/volume/driver.py:566
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: cinder/tests/fake_driver.py:93 cinder/tests/fake_driver.py:98
#, python-format
msgid "LoggingVolumeDriver: %s"
msgstr ""

#: cinder/tests/fake_utils.py:72
#, python-format
msgid "Faking execution of cmd (subprocess): %s"
msgstr ""

#: cinder/tests/fake_utils.py:80
#, python-format
msgid "Faked command matched %s"
msgstr ""

#: cinder/tests/fake_utils.py:96
#, python-format
msgid "Faked command raised an exception %s"
msgstr ""

#: cinder/tests/fake_utils.py:101
#, python-format
msgid "Reply to faked command is stdout='%(stdout)s' stderr='%(stderr)s'"
msgstr ""

#: cinder/tests/test_misc.py:59
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:242
#, python-format
msgid "unrecognized argument %s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1216
#, python-format
msgid "Run CLI command: %s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1219
#, python-format
msgid ""
"CLI output:\n"
" stdout: %(stdout)s\n"
" stderr: %(stderr)s"
msgstr ""

#: cinder/tests/test_storwize_svc.py:1224
#, python-format
msgid ""
"CLI Exception output:\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/tests/test_volume_types.py:59
#, python-format
msgid "Given data: %s"
msgstr ""

#: cinder/tests/test_volume_types.py:60
#, python-format
msgid "Result data: %s"
msgstr ""

#: cinder/tests/api/contrib/test_backups.py:638
#, fuzzy
msgid "Invalid input"
msgstr "Neplatný snímek"

#: cinder/tests/integrated/test_login.py:31
#, fuzzy, python-format
msgid "volume: %s"
msgstr "Odpojit svazek %s"

#: cinder/tests/integrated/api/client.py:37
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:46
msgid "Authentication error"
msgstr ""

#: cinder/tests/integrated/api/client.py:54
msgid "Authorization error"
msgstr ""

#: cinder/tests/integrated/api/client.py:62
msgid "Item not found"
msgstr ""

#: cinder/tests/integrated/api/client.py:104
#, python-format
msgid "Doing %(method)s on %(relative_url)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:106
#, python-format
msgid "Body: %s"
msgstr ""

#: cinder/tests/integrated/api/client.py:124
#, python-format
msgid "%(auth_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:150
#, python-format
msgid "%(relative_uri)s => code %(http_status)s"
msgstr ""

#: cinder/tests/integrated/api/client.py:160
msgid "Unexpected status code"
msgstr ""

#: cinder/tests/integrated/api/client.py:167
#, python-format
msgid "Decoding JSON: %s"
msgstr ""

#: cinder/transfer/api.py:69
msgid "Volume in unexpected state"
msgstr ""

#: cinder/transfer/api.py:103 cinder/volume/api.py:108 cinder/volume/api.py:482
#: cinder/volume/manager.py:567
msgid "status must be available"
msgstr ""

#: cinder/transfer/api.py:120
#, fuzzy, python-format
msgid "Failed to create transfer record for %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/transfer/api.py:137
#, python-format
msgid "Attempt to transfer %s with invalid auth key."
msgstr ""

#: cinder/transfer/api.py:157 cinder/volume/api.py:173
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/transfer/api.py:166 cinder/volume/api.py:182
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/transfer/api.py:180
#, python-format
msgid "Failed to update quota donating volumetransfer id %s"
msgstr ""

#: cinder/transfer/api.py:194
#, python-format
msgid "Volume %s has been transferred."
msgstr ""

#: cinder/volume/api.py:101
msgid "May specify only one of snapshot, imageRef or source volume"
msgstr ""

#: cinder/volume/api.py:113
msgid "Volume size cannot be lesser than the Snapshot size"
msgstr ""

#: cinder/volume/api.py:122
msgid "Unable to clone volumes that are in an error state"
msgstr ""

#: cinder/volume/api.py:128
msgid "Clones currently must be >= original volume size."
msgstr ""

#: cinder/volume/api.py:145
#, python-format
msgid "Volume size '%s' must be an integer and greater than 0"
msgstr ""

#: cinder/volume/api.py:155
msgid "Size of specified image is larger than volume size."
msgstr ""

#: cinder/volume/api.py:159
msgid "Image minDisk size is larger than the volume size."
msgstr ""

#: cinder/volume/api.py:315
msgid "Availability zone is invalid"
msgstr ""

#: cinder/volume/api.py:337
msgid "Failed to update quota for deleting volume"
msgstr ""

#: cinder/volume/api.py:345
#, fuzzy
msgid "Volume status must be available or error"
msgstr "Obraz musí být dostupný"

#: cinder/volume/api.py:354
#, python-format
msgid "Volume still has %d dependent snapshots"
msgstr ""

#: cinder/volume/api.py:407 cinder/volume/api.py:465
#: cinder/volume/volume_types.py:69
#, python-format
msgid "Searching by: %s"
msgstr ""

#: cinder/volume/api.py:485
msgid "already attached"
msgstr ""

#: cinder/volume/api.py:492
msgid "already detached"
msgstr ""

#: cinder/volume/api.py:503
#, fuzzy
msgid "Volume status must be available to reserve"
msgstr "Obraz musí být dostupný"

#: cinder/volume/api.py:557
msgid "must be available"
msgstr ""

#: cinder/volume/api.py:575
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:584
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)"
msgstr ""

#: cinder/volume/api.py:633
msgid "Volume Snapshot status must be available or error"
msgstr ""

#: cinder/volume/api.py:661
msgid "Metadata property key blank"
msgstr ""

#: cinder/volume/api.py:665
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: cinder/volume/api.py:669
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: cinder/volume/api.py:754
#, fuzzy
msgid "Volume status must be available/in-use."
msgstr "Obraz musí být dostupný"

#: cinder/volume/api.py:757
msgid "Volume status is in-use."
msgstr ""

#: cinder/volume/driver.py:94 cinder/volume/drivers/netapp/nfs.py:257
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: cinder/volume/driver.py:221 cinder/volume/drivers/emc/emc_smis_iscsi.py:113
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/driver.py:269
#, fuzzy, python-format
msgid "Could not find iSCSI export for volume %s"
msgstr "Nelze najít obslužnou rutinu pro svazek %(driver_type)s."

#: cinder/volume/driver.py:273 cinder/volume/drivers/emc/emc_smis_iscsi.py:156
#, python-format
msgid "ISCSI Discovery: Found %s"
msgstr ""

#: cinder/volume/driver.py:367
#, python-format
msgid "Failed to access the device on the path %(path)s: %(error)s."
msgstr ""

#: cinder/volume/driver.py:387
#, python-format
msgid "copy_image_to_volume %s."
msgstr ""

#: cinder/volume/driver.py:404
#, python-format
msgid "copy_volume_to_image %s."
msgstr ""

#: cinder/volume/driver.py:483
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: cinder/volume/driver.py:487
#, python-format
msgid ""
"ISCSI volume not yet found at: %(host_device)s. Will rescan & retry.  Try"
" number: %(tries)s."
msgstr ""

#: cinder/volume/driver.py:500
#, python-format
msgid "Found iSCSI node %(host_device)s (after %(tries)s rescans)."
msgstr ""

#: cinder/volume/driver.py:507
#, python-format
msgid "Unable to access the backend storage via the path %(path)s."
msgstr ""

#: cinder/volume/driver.py:526 cinder/volume/manager.py:719
#: cinder/volume/drivers/lvm.py:562 cinder/volume/drivers/lvm.py:686
#: cinder/volume/drivers/storwize_svc.py:1348
#: cinder/volume/drivers/emc/emc_smis_common.py:857
#: cinder/volume/drivers/emc/emc_smis_iscsi.py:235
#: cinder/volume/drivers/huawei/huawei_iscsi.py:1507
#: cinder/volume/drivers/netapp/iscsi.py:1118
#: cinder/volume/drivers/netapp/iscsi.py:1488
#: cinder/volume/drivers/netapp/iscsi.py:2240
#: cinder/volume/drivers/netapp/iscsi.py:2519
#: cinder/volume/drivers/nexenta/volume.py:317
msgid "Updating volume status"
msgstr ""

#: cinder/volume/driver.py:604
msgid "Driver must implement initialize_connection"
msgstr ""

#: cinder/volume/manager.py:123
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:145
#, python-format
msgid "Re-exporting %s volumes"
msgstr ""

#: cinder/volume/manager.py:150
#, python-format
msgid "volume %s stuck in a downloading state"
msgstr ""

#: cinder/volume/manager.py:155
#, python-format
msgid "volume %s: skipping export"
msgstr ""

#: cinder/volume/manager.py:157
msgid "Resuming any in progress delete operations"
msgstr ""

#: cinder/volume/manager.py:160
#, python-format
msgid "Resuming delete on volume: %s"
msgstr ""

#: cinder/volume/manager.py:219
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr ""

#: cinder/volume/manager.py:228
#, fuzzy, python-format
msgid "volume %s: creating from snapshot"
msgstr "Vytvořit svazek ze snímku %s"

#: cinder/volume/manager.py:232
#, python-format
msgid "volume %s: creating from existing volume"
msgstr ""

#: cinder/volume/manager.py:236
#, python-format
msgid "volume %s: creating from image"
msgstr ""

#: cinder/volume/manager.py:245
#, python-format
msgid "volume %s: creating"
msgstr ""

#: cinder/volume/manager.py:256
#, python-format
msgid "Setting volume: %s status to error after failed image copy."
msgstr ""

#: cinder/volume/manager.py:284
#, python-format
msgid "volume %s: creating export"
msgstr ""

#: cinder/volume/manager.py:294
#, python-format
msgid "volume %s: create failed"
msgstr ""

#: cinder/volume/manager.py:327
#, python-format
msgid "volume %s: created successfully"
msgstr ""

#: cinder/volume/manager.py:335
#, fuzzy, python-format
msgid "Error: %s"
msgstr "Zachycena chyba: %s"

#: cinder/volume/manager.py:361
#, python-format
msgid "volume %s: Error trying to reschedule create"
msgstr ""

#: cinder/volume/manager.py:379
msgid "Retry info not present, will not reschedule"
msgstr ""

#: cinder/volume/manager.py:383
msgid "No request spec, will not reschedule"
msgstr ""

#: cinder/volume/manager.py:388
#, python-format
msgid "volume %(volume_id)s: re-scheduling %(method)s attempt %(num)d"
msgstr ""

#: cinder/volume/manager.py:417 cinder/volume/manager.py:430
#, python-format
msgid "volume %s: deleting"
msgstr ""

#: cinder/volume/manager.py:423
msgid "volume is not local to this node"
msgstr ""

#: cinder/volume/manager.py:428
#, python-format
msgid "volume %s: removing export"
msgstr ""

#: cinder/volume/manager.py:433
#, python-format
msgid "Cannot delete volume %s: volume is busy"
msgstr ""

#: cinder/volume/manager.py:453
msgid "Failed to update usages deleting volume"
msgstr ""

#: cinder/volume/manager.py:457
#, python-format
msgid "volume %s: deleted successfully"
msgstr ""

#: cinder/volume/manager.py:472
#, python-format
msgid "snapshot %s: creating"
msgstr ""

#: cinder/volume/manager.py:478
#, python-format
msgid "snapshot %(snap_name)s: creating"
msgstr ""

#: cinder/volume/manager.py:496
#, python-format
msgid "snapshot %s: created successfully"
msgstr ""

#: cinder/volume/manager.py:504 cinder/volume/manager.py:514
#, python-format
msgid "snapshot %s: deleting"
msgstr ""

#: cinder/volume/manager.py:517
#, python-format
msgid "Cannot delete snapshot %s: snapshot is busy"
msgstr ""

#: cinder/volume/manager.py:543
msgid "Failed to update usages deleting snapshot"
msgstr ""

#: cinder/volume/manager.py:546
#, python-format
msgid "snapshot %s: deleted successfully"
msgstr ""

#: cinder/volume/manager.py:564
msgid "being attached by another instance"
msgstr ""

#: cinder/volume/manager.py:623 cinder/volume/manager.py:628
#, fuzzy, python-format
msgid "Failed to copy image to volume: %(volume_id)s, error: %(error)s"
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/volume/manager.py:633
#, python-format
msgid "Downloaded image %(image_id)s to %(volume_id)s successfully."
msgstr ""

#: cinder/volume/manager.py:652
#, fuzzy, python-format
msgid "Uploaded volume %(volume_id)s to image (%(image_id)s) successfully"
msgstr "Připojit svazek %(volume_id)s k instanci %(instance_id)s na %(device)s"

#: cinder/volume/manager.py:732
msgid "Clear capabilities"
msgstr ""

#: cinder/volume/manager.py:736
#, python-format
msgid "Notification {%s} received"
msgstr ""

#: cinder/volume/volume_types.py:45
#, python-format
msgid "DB error: %s"
msgstr ""

#: cinder/volume/volume_types.py:54 cinder/volume/volume_types.py:101
msgid "id cannot be None"
msgstr ""

#: cinder/volume/volume_types.py:113
msgid "name cannot be None"
msgstr ""

#: cinder/volume/volume_types.py:132
#, python-format
msgid ""
"Default volume type is not found, please check default_volume_type "
"config: %s"
msgstr ""

#: cinder/volume/drivers/coraid.py:88
msgid "Running with CoraidDriver for ESM EtherCLoud"
msgstr ""

#: cinder/volume/drivers/coraid.py:99
#, python-format
msgid "Update session cookie %(session)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:105 cinder/volume/drivers/coraid.py:180
#, fuzzy, python-format
msgid "Message : %(message)s"
msgstr "%(code)s: %(message)s"

#: cinder/volume/drivers/coraid.py:122
#, python-format
msgid "Error while trying to set group: %(message)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:125
#, fuzzy, python-format
msgid "Unable to find group: %(group)s"
msgstr "Nelze použít globální roli %(role_id)s"

#: cinder/volume/drivers/coraid.py:158
msgid "ESM urlOpen error"
msgstr ""

#: cinder/volume/drivers/coraid.py:163
#, fuzzy
msgid "JSON Error"
msgstr "Chyba přesunu"

#: cinder/volume/drivers/coraid.py:167
msgid "Request without URL"
msgstr ""

#: cinder/volume/drivers/coraid.py:172
#, python-format
msgid "Configure data : %s"
msgstr ""

#: cinder/volume/drivers/coraid.py:174
#, fuzzy, python-format
msgid "Configure response : %s"
msgstr "odpověď %s"

#: cinder/volume/drivers/coraid.py:196
#, fuzzy, python-format
msgid "Unable to retrive volume infos for volume %(volname)s"
msgstr "Nenalezeno žádné cílové id ve svazku %(volume_id)s."

#: cinder/volume/drivers/coraid.py:286
msgid "Cannot login on Coraid ESM"
msgstr ""

#: cinder/volume/drivers/coraid.py:305
#, python-format
msgid "Fail to create volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:318
#, python-format
msgid "Failed to delete volume %(volname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:332
#, fuzzy, python-format
msgid "Failed to Create Snapshot %(snapname)s"
msgstr "Nelze restartovat instanci"

#: cinder/volume/drivers/coraid.py:344
#, python-format
msgid "Failed to Delete Snapshot %(snapname)s"
msgstr ""

#: cinder/volume/drivers/coraid.py:359
#, fuzzy, python-format
msgid "Failed to Create Volume from Snapshot %(snapname)s"
msgstr "Vytvořit svazek ze snímku %s"

#: cinder/volume/drivers/coraid.py:380
#, python-format
msgid ""
"Failed to Initialize Connection. Volume Name: %(volname)s Shelf: "
"%(shelf)s, Lun: %(lun)s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:64
#, python-format
msgid "There's no Gluster config file configured (%s)"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:69
#, python-format
msgid "Gluster config file at %(config)s doesn't exist"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:81
msgid "mount.glusterfs is not installed"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:99 cinder/volume/drivers/nfs.py:241
#, python-format
msgid "casted to %s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:109 cinder/volume/drivers/nfs.py:251
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:173 cinder/volume/drivers/nfs.py:314
#, fuzzy, python-format
msgid "Exception during mounting %s"
msgstr "Výjimka při načítání rozšíření: %s"

#: cinder/volume/drivers/glusterfs.py:251 cinder/volume/drivers/nfs.py:428
#, fuzzy, python-format
msgid "%s is already mounted"
msgstr "skupina %s již existuje"

#: cinder/volume/drivers/lvm.py:82
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: cinder/volume/drivers/lvm.py:197
#, python-format
msgid "Size for volume: %s not found, skipping secure delete."
msgstr ""

#: cinder/volume/drivers/lvm.py:204
#, python-format
msgid "Performing secure delete on volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:218
#, python-format
msgid "Error unrecognized volume_clear option: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:238
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:268 cinder/volume/drivers/lvm.py:664
#, fuzzy, python-format
msgid "Creating clone of volume: %s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/lvm.py:345
#, python-format
msgid "Skipping ensure_export. No iscsi_target provision for volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:366
#, python-format
msgid "Skipping ensure_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:380
msgid "Detected inconsistency in provider_location id"
msgstr ""

#: cinder/volume/drivers/lvm.py:432
#, fuzzy, python-format
msgid "Symbolic link %s not found"
msgstr "značka [%s] nenalezena"

#: cinder/volume/drivers/lvm.py:512 cinder/volume/drivers/lvm.py:526
#, python-format
msgid "Skipping remove_export. No iscsi_target provisioned for volume: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:544
#, python-format
msgid ""
"Skipping remove_export. No iscsi_target is presently exported for volume:"
" %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:585
#, python-format
msgid "Error retrieving volume status: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:142
#, python-format
msgid "Expected volume size was %d"
msgstr ""

#: cinder/volume/drivers/nfs.py:143
#, python-format
msgid " but size is now %d"
msgstr ""

#: cinder/volume/drivers/nfs.py:199
#, python-format
msgid "There's no NFS config file configured (%s)"
msgstr ""

#: cinder/volume/drivers/nfs.py:204
#, python-format
msgid "NFS config file at %(config)s doesn't exist"
msgstr ""

#: cinder/volume/drivers/nfs.py:208
#, python-format
msgid "NFS config 'nfs_oversub_ratio' invalid.  Must be > 0: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:216
#, python-format
msgid "NFS config 'nfs_used_ratio' invalid.  Must be > 0 and <= 1.0: %s"
msgstr ""

#: cinder/volume/drivers/nfs.py:362
#, python-format
msgid "%s is above nfs_used_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:365
#, python-format
msgid "%s is above nfs_oversub_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:368
#, python-format
msgid "%s reserved space is above nfs_oversub_ratio"
msgstr ""

#: cinder/volume/drivers/nfs.py:384
#, python-format
msgid "Selected %s as target nfs share."
msgstr ""

#: cinder/volume/drivers/rbd.py:101
#, fuzzy, python-format
msgid "error opening rbd image %s"
msgstr "Chyba v přesunu %s"

#: cinder/volume/drivers/rbd.py:152
msgid "rados and rbd python libraries not found"
msgstr ""

#: cinder/volume/drivers/rbd.py:158
msgid "error connecting to ceph cluster"
msgstr ""

#: cinder/volume/drivers/rbd.py:223 cinder/volume/drivers/sheepdog.py:134
msgid "error refreshing volume stats"
msgstr ""

#: cinder/volume/drivers/rbd.py:262
#, python-format
msgid "flattening %(pool)s/%(img)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:268
#, python-format
msgid "cloning %(pool)s/%(img)s@%(snap)s to %(dst)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:347
#, python-format
msgid "connection data: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:356
msgid "Not stored in rbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:360
msgid "Blank components"
msgstr ""

#: cinder/volume/drivers/rbd.py:363
#, fuzzy
msgid "Not an rbd snapshot"
msgstr "Neplatný snímek"

#: cinder/volume/drivers/rbd.py:375
#, fuzzy, python-format
msgid "not cloneable: %s"
msgstr "Název roz: %s"

#: cinder/volume/drivers/rbd.py:379
#, python-format
msgid "%s is in a different ceph cluster"
msgstr ""

#: cinder/volume/drivers/rbd.py:391
#, fuzzy, python-format
msgid "Unable to open image %(loc)s: %(err)s"
msgstr "Poškozené tělo zprávy: %(reason)s"

#: cinder/volume/drivers/scality.py:62
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: cinder/volume/drivers/scality.py:73
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: cinder/volume/drivers/scality.py:79
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: cinder/volume/drivers/scality.py:100
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

#: cinder/volume/drivers/scality.py:134
#, python-format
msgid "Cannot find volume dir for Scality SOFS at '%s'"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:47
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:52
msgid "Sheepdog is not working"
msgstr ""

#: cinder/volume/drivers/solidfire.py:133
#, python-format
msgid "Payload for SolidFire API call: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:150
#, python-format
msgid "Call to json.loads() raised an exception: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:156
#, python-format
msgid "Results of SolidFire API call: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:160
#, python-format
msgid "Clone operation encountered: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:162
#, python-format
msgid "Waiting for outstanding operation before retrying snapshot: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:168
#, python-format
msgid "Detected xDBVersionMismatch, retry %s of 5"
msgstr ""

#: cinder/volume/drivers/solidfire.py:175
#, fuzzy, python-format
msgid "API response: %s"
msgstr "odpověď %s"

#: cinder/volume/drivers/solidfire.py:195
#, python-format
msgid "Found solidfire account: %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:224
#, python-format
msgid "solidfire account: %s does not exist, create it..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:285
#, python-format
msgid "Failed to retrieve volume SolidFire-ID: %s in get_by_account!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:356
#, fuzzy
msgid "Failed to get model update from clone"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/solidfire.py:382
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:415
#, python-format
msgid "Mapped SolidFire volumeID %(sfid)s to cinder ID %(uuid)s."
msgstr ""

#: cinder/volume/drivers/solidfire.py:424
#, python-format
msgid "Volume %s, not found on SF Cluster."
msgstr ""

#: cinder/volume/drivers/solidfire.py:427
#, python-format
msgid "Found %(count)s volumes mapped to id: %(uuid)s."
msgstr ""

#: cinder/volume/drivers/solidfire.py:494
msgid "Enter SolidFire delete_volume..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:498
#, python-format
msgid "Account for Volume ID %s was not found on the SolidFire Cluster!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:500
msgid "This usually means the volume was never succesfully created."
msgstr ""

#: cinder/volume/drivers/solidfire.py:515
#, python-format
msgid "Volume ID %s was not found on the SolidFire Cluster!"
msgstr ""

#: cinder/volume/drivers/solidfire.py:518
msgid "Leaving SolidFire delete_volume"
msgstr ""

#: cinder/volume/drivers/solidfire.py:522
msgid "Executing SolidFire ensure_export..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:527
msgid "Executing SolidFire create_export..."
msgstr ""

#: cinder/volume/drivers/solidfire.py:576
msgid "Updating cluster status info"
msgstr ""

#: cinder/volume/drivers/solidfire.py:584
#, fuzzy
msgid "Failed to get updated stats"
msgstr "Nelze vytvořit typ instance"

#: cinder/volume/drivers/storwize_svc.py:177
#, python-format
msgid "WWPN on node %(node)s: %(wwpn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:183
msgid "enter: do_setup"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:194
#, fuzzy, python-format
msgid "pool %s doesn't exist"
msgstr "Instance neexistuje"

#: cinder/volume/drivers/storwize_svc.py:210
msgid "Failed to get license information."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:269
msgid "do_setup: No configured nodes"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:271
msgid "leave: do_setup"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:293
msgid "enter: check_for_setup_error"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:299
#: cinder/volume/drivers/netapp/iscsi.py:173
#: cinder/volume/drivers/netapp/iscsi.py:1186
#: cinder/volume/drivers/netapp/iscsi.py:1539
#: cinder/volume/drivers/netapp/nfs.py:113
#: cinder/volume/drivers/netapp/nfs.py:332
#: cinder/volume/drivers/netapp/nfs.py:383
#: cinder/volume/drivers/san/hp/hp_3par_common.py:126
#, python-format
msgid "%s is not set"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:305
msgid ""
"Password or SSH private key is required for authentication: set either "
"san_password or san_private_key option"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:313
#, python-format
msgid ""
"Illegal value %d specified for storwize_svc_flashcopy_timeout: valid "
"values are between 0 and 600"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:321
msgid "leave: check_for_setup_error"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:335
#, python-format
msgid "ensure_export: Volume %s not found on storage"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:360
#, python-format
msgid "enter: _get_chap_secret_for_host: host name %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:396
#, python-format
msgid ""
"leave: _get_chap_secret_for_host: host name %(host_name)s with secret "
"%(chap_secret)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:419
msgid "_create_host: Cannot clean host name. Host name is not unicode or string"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:487
#, python-format
msgid "enter: _get_host_from_connector: prefix %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:515
#, python-format
msgid "leave: _get_host_from_connector: host %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:527
#, python-format
msgid "enter: _create_host: host %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:542
msgid "_create_host: No connector ports"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:555
#, fuzzy, python-format
msgid "leave: _create_host: host %(host)s - %(host_name)s"
msgstr "Nastavování hostitele %(host)s na %(state)s."

#: cinder/volume/drivers/storwize_svc.py:578
#, fuzzy, python-format
msgid "enter: _map_vol_to_host: volume %(volume_name)s to host %(host_name)s"
msgstr "mazání svazku %(volume_name)s který má snímek"

#: cinder/volume/drivers/storwize_svc.py:613
msgid ""
"storwize_svc_multihostmap_enabled is set to Flase, Not allow multi host "
"mapping"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:623
#, python-format
msgid "volume %s mapping to multi host"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:629
#, python-format
msgid ""
"leave: _map_vol_to_host: LUN %(result_lun)s, volume %(volume_name)s, host"
" %(host_name)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:639
#, python-format
msgid "enter: _delete_host: host %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:647
#, python-format
msgid "leave: _delete_host: host %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:679
#, python-format
msgid "enter: initialize_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:695
msgid "_create_host failed to return the host name."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:706
#, python-format
msgid "initialize_connection: Failed to get attributes for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:713
#, python-format
msgid "Did not find expected column name in lsvdisk: %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:715
#, python-format
msgid "initialize_connection: Missing volume attribute for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:732
#, python-format
msgid ""
"initialize_connection: No node found in I/O group %(gid)s for volume "
"%(vol)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:740
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:773
#, python-format
msgid ""
"initialize_connection: Failed to collect return properties for volume "
"%(vol)s and connector %(conn)s.\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:778
#, python-format
msgid ""
"leave: initialize_connection:\n"
" volume: %(vol)s\n"
" connector %(conn)s\n"
" properties: %(prop)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:796
#, python-format
msgid "enter: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:806
msgid "_get_host_from_connector failed to return the host name for connector"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:821
#, python-format
msgid ""
"terminate_connection: No mapping of volume %(vol_name)s to host "
"%(host_name)s found"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:829
#, python-format
msgid "leave: terminate_connection: volume %(vol)s with connector %(conn)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:887
msgid "protocol must be specified as '<in> iSCSI' or '<in> FC'"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:911
#, python-format
msgid "enter: _create_vdisk: vdisk %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:949
#, python-format
msgid ""
"_create_vdisk %(name)s - did not find success message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:954
#, python-format
msgid "leave: _create_vdisk: volume %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:966
#: cinder/volume/drivers/storwize_svc.py:980
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find success "
"message in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:992
#: cinder/volume/drivers/storwize_svc.py:1002
#, python-format
msgid ""
"create FC mapping from %(source)s to %(target)s - did not find mapping id"
" in CLI output.\n"
" stdout: %(out)s\n"
" stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1016
#, python-format
msgid ""
"_prepare_fc_map: Failed to prepare FlashCopy from %(source)s to "
"%(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1043
#, python-format
msgid ""
"Unexecpted mapping status %(status)s for mapping %(id)s. Attributes: "
"%(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1054
#, python-format
msgid ""
"Mapping %(id)s prepare failed to complete within the allotted %(to)d "
"seconds timeout. Terminating."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1059
#, python-format
msgid ""
"_prepare_fc_map: Failed to start FlashCopy from %(source)s to %(target)s "
"with exception %(ex)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1066
#, python-format
msgid "_prepare_fc_map: %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1073
#, python-format
msgid ""
"_start_fc_map: Failed to start FlashCopy from %(source)s to %(target)s.\n"
"stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1084
#, python-format
msgid ""
"enter: _run_flashcopy: execute FlashCopy from source %(source)s to target"
" %(target)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1096
#, python-format
msgid "leave: _run_flashcopy: FlashCopy started from %(source)s to %(target)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1104
#, python-format
msgid "enter: _create_copy: snapshot %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1111
#, python-format
msgid "_create_copy: Source vdisk %s does not exist"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1123
#, python-format
msgid ""
"_create_copy: cannot get source vdisk %(src)s capacity from vdisk "
"attributes %(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1133
#, python-format
msgid "leave: _create_copy: snapshot %(tgt_vdisk)s from vdisk %(src_vdisk)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1138
#, python-format
msgid "enter: _get_flashcopy_mapping_attributes: mapping %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1160
#, python-format
msgid ""
"leave: _get_flashcopy_mapping_attributes: mapping %(fc_map_id)s, "
"attributes %(attributes)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1168
#, python-format
msgid "enter: _is_vdisk_defined: vdisk %s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1170
#, python-format
msgid "leave: _is_vdisk_defined: vdisk %(vol)s with %(str)s "
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1198
#, python-format
msgid "enter: _delete_vdisk: vdisk %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1203
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1229
#, python-format
msgid "Vdisk %(name)s not involved in mapping %(src)s -> %(tgt)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1262
#, python-format
msgid "leave: _delete_vdisk: vdisk %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1287
msgid "create_volume_from_snapshot: Source and destination size differ."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1301
msgid "create_cloned_volume: Source and destination size differ."
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1365
msgid "_update_volume_status: Could not get system name"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1377
msgid "Could not get pool data from the storage"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1378
msgid "_update_volume_status: Could not get storage pool data"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1416
msgid ""
"Illegal value specified for storwize_svc_vol_rsize: set to either a "
"percentage (0-100) or -1"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1422
msgid ""
"Illegal value specified for storwize_svc_vol_warning: set to a percentage"
" (0-100)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1429
msgid ""
"Illegal value specified for storwize_svc_vol_grainsize: set to either 32,"
" 64, 128, or 256"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1436
msgid "System does not support compression"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1441
msgid "If compression is set to True, rsize must also be set (not equal to -1)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1447
#, python-format
msgid ""
"Illegal value %(prot)s specified for storwize_svc_connection_protocol: "
"valid values are %(enabled)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1456
msgid ""
"Multipath is currently only supported for FC connections and not iSCSI.  "
"(This is a Nova limitation.)"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1468
#, python-format
msgid "enter: _execute_command_and_parse_attributes:  command %s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1475
#, fuzzy, python-format
msgid ""
"CLI Exception output:\n"
" command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""
"%(description)s\n"
"Příkaz: %(cmd)s\n"
"Kód ukončení: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: cinder/volume/drivers/storwize_svc.py:1492
#, python-format
msgid ""
"leave: _execute_command_and_parse_attributes:\n"
"command: %(cmd)s\n"
"attributes: %(attr)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1511
#, python-format
msgid ""
"_get_hdr_dic: attribute headers and values do not match.\n"
" Headers: %(header)s\n"
" Values: %(row)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1521
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
"stdout: %(out)s\n"
"stderr: %(err)s\n"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1535
#, python-format
msgid ""
"%(fun)s: Failed with unexpected CLI output.\n"
" Command: %(cmd)s\n"
" stdout: %(out)s\n"
" stderr: %(err)s"
msgstr ""

#: cinder/volume/drivers/storwize_svc.py:1543
#, python-format
msgid "Did not find expected column in %(fun)s: %(hdr)s"
msgstr ""

#: cinder/volume/drivers/windows.py:141
#, python-format
msgid "Creating folder %s "
msgstr ""

#: cinder/volume/drivers/windows.py:206
#: cinder/volume/drivers/nexenta/volume.py:203
#, python-format
msgid "Ignored target creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/windows.py:212
#, fuzzy, python-format
msgid "Disk not found: %s"
msgstr "Instance nenalezena"

#: cinder/volume/drivers/zadara.py:218
#, python-format
msgid "Sending %(method)s to %(url)s. Body \"%(body)s\""
msgstr ""

#: cinder/volume/drivers/zadara.py:240
#, python-format
msgid "Operation completed. %(data)s"
msgstr ""

#: cinder/volume/drivers/zadara.py:350
#, fuzzy, python-format
msgid "Volume %(name)s could not be found. It might be already deleted"
msgstr "Svazek %(volume_id)s nemohl být nastaven."

#: cinder/volume/drivers/zadara.py:447
#, python-format
msgid "Attach properties: %(properties)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:41
msgid ""
"Module PyWBEM not installed.  Install PyWBEM using the python-pywbem "
"package."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:77
msgid "Entering create_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:81
#, python-format
msgid "Create Volume: %(volume)s  Size: %(size)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:89
#, python-format
msgid "Create Volume: %(volume)s  Storage type: %(storage_type)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:96
#, python-format
msgid ""
"Create Volume: %(volume)s  Pool: %(pool)s  Storage System: "
"%(storage_system)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:105
#, python-format
msgid ""
"Error Create Volume: %(volumename)s. Storage Configuration Service not "
"found for pool %(storage_type)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:113
#, python-format
msgid ""
"Create Volume: %(name)s  Method: CreateOrModifyElementFromStoragePool  "
"ConfigServicie: %(service)s  ElementName: %(name)s  InPool: %(pool)s  "
"ElementType: 5  Size: %(size)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:128
#, python-format
msgid "Create Volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:135
#, python-format
msgid ""
"Error Create Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:142
#, python-format
msgid "Leaving create_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:150
#, fuzzy
msgid "Entering create_volume_from_snapshot."
msgstr "Vytvořit svazek ze snímku %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:155
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:165
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Snapshot Instance: %(snapshotinstance)s  Storage "
"System: %(storage_system)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:175
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Create Volume from Snapshot is NOT supported on VMAX."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:186
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Cannot find Replication Service to create volume from "
"snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:195
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Method: CreateElementReplica  ReplicationService: "
"%(service)s  ElementName: %(elementname)s  SyncType: 8  SourceElement: "
"%(sourceelement)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:216
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  "
"Snapshot:%(snapshotname)s.  Return code: %(rc)lu.Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:228
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Successfully clone volume from snapshot.  Finding the "
"clone relationship."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:239
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Remove the clone relationship. Method: "
"ModifyReplicaSynchronization ReplicationService: %(service)s  Operation: "
"8  Synchronization: %(sync_name)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:255
#, python-format
msgid ""
"Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:264
#, python-format
msgid ""
"Error Create Volume from Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s.  Return code: %(rc)lu.  Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:276
#, python-format
msgid ""
"Leaving create_volume_from_snapshot: Volume: %(volumename)s Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:285
msgid "Entering create_cloned_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:290
#, python-format
msgid ""
"Create a Clone from Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:300
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Source Instance: %(src_instance)s  Storage System: %(storage_system)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:310
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s. Cannot find Replication Service to create cloned volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:319
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Method: CreateElementReplica  ReplicationService: %(service)s  "
"ElementName: %(elementname)s  SyncType: 8  SourceElement: "
"%(sourceelement)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:340
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source "
"Volume:%(srcname)s.  Return code: %(rc)lu.Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:352
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s."
"  Successfully cloned volume from source volume.  Finding the clone "
"relationship."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:363
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s."
"  Remove the clone relationship. Method: ModifyReplicaSynchronization "
"ReplicationService: %(service)s  Operation: 8  Synchronization: "
"%(sync_name)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:379
#, python-format
msgid ""
"Create Cloned Volume: Volume: %(volumename)s  Source Volume: %(srcname)s"
"  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:388
#, python-format
msgid ""
"Error Create Cloned Volume: Volume: %(volumename)s  Source Volume: "
"%(srcname)s.  Return code: %(rc)lu.  Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:400
#, python-format
msgid ""
"Leaving create_cloned_volume: Volume: %(volumename)s Source Volume: "
"%(srcname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:409
msgid "Entering delete_volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:411
#, fuzzy, python-format
msgid "Delete Volume: %(volume)s"
msgstr "mazání svazku %(volume_name)s který má snímek"

#: cinder/volume/drivers/emc/emc_smis_common.py:418
#, python-format
msgid "Volume %(name)s not found on the array. No volume to delete."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:428
#, python-format
msgid ""
"Error Delete Volume: %(volumename)s. Storage Configuration Service not "
"found."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:436
#, python-format
msgid "Delete Volume: %(name)s  DeviceID: %(deviceid)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:440
#, python-format
msgid ""
"Delete Volume: %(name)s  Method: EMCReturnToStoragePool ConfigServic: "
"%(service)s  TheElement: %(vol_instance)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:454
#, python-format
msgid ""
"Error Delete Volume: %(volumename)s.  Return code: %(rc)lu.  Error: "
"%(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:463
#, python-format
msgid "Leaving delete_volume: %(volumename)s  Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:470
msgid "Entering create_snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:474
#, fuzzy, python-format
msgid "Create snapshot: %(snapshot)s: volume: %(volume)s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:486
#, python-format
msgid "Device ID: %(deviceid)s: Storage System: %(storagesystem)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:493
#: cinder/volume/drivers/emc/emc_smis_common.py:495
#: cinder/volume/drivers/emc/emc_smis_common.py:565
#, python-format
msgid "Cannot find Replication Service to create snapshot for volume %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:500
#, python-format
msgid ""
"Create Snapshot:  Method: CreateElementReplica: Target: %(snapshot)s  "
"Source: %(volume)s  Replication Service: %(service)s  ElementName: "
"%(elementname)s  Sync Type: 7  SourceElement: %(sourceelement)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:516
#, python-format
msgid ""
"Create Snapshot: Volume: %(volumename)s  Snapshot: %(snapshotname)s  "
"Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:525
#, fuzzy, python-format
msgid ""
"Error Create Snapshot: %(snapshot)s Volume: %(volume)s Error: "
"%(errordesc)s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:533
#, python-format
msgid ""
"Leaving create_snapshot: Snapshot: %(snapshot)s Volume: %(volume)s  "
"Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:539
msgid "Entering delete_snapshot."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:543
#, fuzzy, python-format
msgid "Delete Snapshot: %(snapshot)s: volume: %(volume)s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:549
#, python-format
msgid ""
"Delete Snapshot: %(snapshot)s: volume: %(volume)s. Finding "
"StorageSychronization_SV_SV."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:557
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s not found on the array. No "
"snapshot to delete."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:572
#, python-format
msgid ""
"Delete Snapshot: Target: %(snapshot)s  Source: %(volume)s.  Method: "
"ModifyReplicaSynchronization:  Replication Service: %(service)s  "
"Operation: 19  Synchronization: %(sync_name)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:588
#, python-format
msgid ""
"Delete Snapshot: Volume: %(volumename)s  Snapshot: %(snapshotname)s  "
"Return code: %(rc)lu"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:597
#, python-format
msgid ""
"Error Delete Snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s. Return code: %(rc)lu. Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:609
#, python-format
msgid ""
"Leaving delete_snapshot: Volume: %(volumename)s  Snapshot: "
"%(snapshotname)s  Return code: %(rc)lu."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:619
#, fuzzy, python-format
msgid "Create export: %(volume)s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:624
#, fuzzy, python-format
msgid "create_export: Volume: %(volume)s  Device ID: %(device_id)s"
msgstr "Připojit svazek %(volume_id)s k instanci %(instance_id)s na %(device)s"

#: cinder/volume/drivers/emc/emc_smis_common.py:646
#, python-format
msgid ""
"ExposePaths: %(vol)s  ConfigServicie: %(service)s  LUNames: %(lun_name)s"
"  InitiatorPortIDs: %(initiator)s  DeviceAccesses: 2"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:661
#, python-format
msgid "ExposePaths parameter LunMaskingSCSIProtocolController: %(lunmasking)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:672
#, fuzzy, python-format
msgid "Error mapping volume %s."
msgstr "Chyba v přesunu %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:676
#, python-format
msgid "ExposePaths for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:692
#, python-format
msgid ""
"HidePaths: %(vol)s  ConfigServicie: %(service)s  LUNames: %(device_id)s  "
"LunMaskingSCSIProtocolController: %(lunmasking)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:705
#, python-format
msgid "Error unmapping volume %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:709
#, python-format
msgid "HidePaths for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:722
#, python-format
msgid ""
"AddMembers: ConfigServicie: %(service)s  MaskingGroup: %(masking_group)s"
"  Members: %(vol)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:737
#, python-format
msgid "Error mapping volume %(vol)s. %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:742
#, python-format
msgid "AddMembers for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:755
#, python-format
msgid ""
"RemoveMembers: ConfigServicie: %(service)s  MaskingGroup: "
"%(masking_group)s  Members: %(vol)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:768
#, python-format
msgid "Error unmapping volume %(vol)s. %(error)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:773
#, python-format
msgid "RemoveMembers for volume %s completed successfully."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:779
#, python-format
msgid "Map volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:788
#: cinder/volume/drivers/emc/emc_smis_common.py:818
#, python-format
msgid "Cannot find Controller Configuration Service for storage system %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:802
#, python-format
msgid "Unmap volume: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:808
#, python-format
msgid "Volume %s is not mapped. No volume to unmap."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:832
#, python-format
msgid "Initialize connection: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:838
#, python-format
msgid "Volume %s is already mapped."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:850
#, python-format
msgid "Terminate connection: %(volume)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:882
#, python-format
msgid "Found Storage Type: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:885
#, fuzzy
msgid "Storage type not found."
msgstr "Obraz nenalezen"

#: cinder/volume/drivers/emc/emc_smis_common.py:901
#, python-format
msgid "Found Masking View: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:904
#, fuzzy
msgid "Masking View not found."
msgstr "Obraz nenalezen"

#: cinder/volume/drivers/emc/emc_smis_common.py:926
#, fuzzy
msgid "Ecom user not found."
msgstr "Server nenalezen."

#: cinder/volume/drivers/emc/emc_smis_common.py:946
#, python-format
msgid "Ecom IP: %(ecomIp)s Port: %(ecomPort)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:949
#, fuzzy
msgid "Ecom server not found."
msgstr "Server nenalezen."

#: cinder/volume/drivers/emc/emc_smis_common.py:956
#, fuzzy
msgid "Cannot connect to ECOM server"
msgstr "Znovu připojeno k frontě"

#: cinder/volume/drivers/emc/emc_smis_common.py:968
#, python-format
msgid "Found Replication Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:981
#, python-format
msgid "Found Storage Configuration Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:994
#, python-format
msgid "Found Controller Configuration Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1007
#, python-format
msgid "Found Storage Hardware ID Management Service: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1051
#, fuzzy, python-format
msgid "Pool %(storage_type)s is not found."
msgstr "Role %(role_id)s nemohla být nalezena."

#: cinder/volume/drivers/emc/emc_smis_common.py:1057
#, python-format
msgid "Storage system not found for pool %(storage_type)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1063
#, python-format
msgid "Pool: %(pool)s  SystemName: %(systemname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1079
#, python-format
msgid "Pool name: %(poolname)s  System name: %(systemname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1111
#, fuzzy, python-format
msgid "Volume %(volumename)s not found on the array."
msgstr "Svazek %(volume_id)s nemohl být nastaven."

#: cinder/volume/drivers/emc/emc_smis_common.py:1114
#, fuzzy, python-format
msgid "Volume name: %(volumename)s  Volume instance: %(vol_instance)s."
msgstr "Svazek není nalezen v instanci %(instance_id)s."

#: cinder/volume/drivers/emc/emc_smis_common.py:1127
#, python-format
msgid "Source: %(volumename)s  Target: %(snapshotname)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1150
#, python-format
msgid ""
"Source: %(volumename)s  Target: %(snapshotname)s. Storage Synchronized "
"not found. "
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1155
#, python-format
msgid ""
"Storage system: %(storage_system)s  Storage Synchronized instance: "
"%(sync)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1181
#, fuzzy, python-format
msgid "Error finding %s."
msgstr "Chyba v přesunu %s"

#: cinder/volume/drivers/emc/emc_smis_common.py:1185
#, python-format
msgid "Found %(name)s: %(initiator)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1245
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage system %(storage_system)s "
"and initiator %(initiator)s is  %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1286
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage volume %(vol)s and initiator"
" %(initiator)s is  %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1299
#, python-format
msgid ""
"Volume %(name)s not found on the array. Cannot determine if there are "
"volumes mapped."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1311
#, python-format
msgid ""
"LunMaskingSCSIProtocolController for storage system %(storage)s and "
"%(connector)s is %(ctrl)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1323
#, python-format
msgid ""
"Found %(numVolumesMapped)d volumes on storage system %(storage)s mapped "
"to %(initiator)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1358
#, python-format
msgid "Available device number on %(storage)s: %(device)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1401
#, python-format
msgid "Device number not found for volume %(volumename)s %(vol_instance)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1406
#, python-format
msgid "Found device number %(device)d for volume %(volumename)s %(vol_instance)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1416
#, python-format
msgid "Device info: %(data)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1438
#, python-format
msgid "Masking view: %(view)s DeviceMaskingGroup: %(masking)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1460
#, python-format
msgid "Found Storage Processor System: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1488
#, python-format
msgid ""
"iSCSIProtocolEndpoint for storage system %(storage_system)s and SP %(sp)s"
" is  %(endpoint)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1517
msgid "Error finding Storage Hardware ID Service."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1523
#, python-format
msgid ""
"EMCGetTargetEndpoints: Service: %(service)s  Storage HardwareIDs: "
"%(hardwareids)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1535
msgid "Error finding Target WWNs."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1545
#, python-format
msgid "Add target WWN: %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1547
#, python-format
msgid "Target WWNs: %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_common.py:1563
#, python-format
msgid "Storage Hardware IDs for %(wwpns)s is %(foundInstances)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:152
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:161
#, python-format
msgid "Cannot find device number for volume %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:191
#, fuzzy, python-format
msgid "Found iSCSI endpoint: %s"
msgstr "Vyvoláno Nenalezeno: %s"

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:198
#, python-format
msgid "ISCSI endpoint not found for SP %(sp)s on storage system %(storage)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_smis_iscsi.py:215
#, python-format
msgid "ISCSI properties: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:57
#, python-format
msgid "Range: start LU: %(start)s, end LU: %(end)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:71
#, python-format
msgid "setting LU uppper (end) limit to %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:79
#, python-format
msgid "%(element)s: %(val)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:89 cinder/volume/drivers/hds/hds.py:92
#, fuzzy, python-format
msgid "XML exception reading parameter: %s"
msgstr "Výjimka při načítání rozšíření: %s"

#: cinder/volume/drivers/hds/hds.py:161
#, python-format
msgid "portal: %(ip)s:%(ipp)s, CTL: %(ctl)s, port: %(port)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:180
#, python-format
msgid "No configuration found for service: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:231
#, fuzzy, python-format
msgid "HDP not found: %s"
msgstr "Instance nenalezena"

#: cinder/volume/drivers/hds/hds.py:264
#, python-format
msgid "iSCSI portal not found for service: %s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:301
#, python-format
msgid "LUN %(lun)s of size %(sz)s MB is created."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:315
#, python-format
msgid "Array Mismatch %(myid)s vs %(arid)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:321
#, fuzzy, python-format
msgid "delete lun %(lun)s on %(name)s"
msgstr "mazání svazku %(volume_name)s který má snímek"

#: cinder/volume/drivers/hds/hds.py:398
#, python-format
msgid "LUN %(lun)s of size %(sz)s MB is created from snapshot."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:420
#, python-format
msgid "LUN %(lun)s of size %(size)s MB is created."
msgstr ""

#: cinder/volume/drivers/hds/hds.py:434
#, python-format
msgid "Array mismatch %(myid)s vs %(arid)s"
msgstr ""

#: cinder/volume/drivers/hds/hds.py:445
#, python-format
msgid "LUN %s is deleted."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:117
msgid "read timed out"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:142
msgid "do_setup."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:148
msgid "check_for_setup_error."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:153
msgid "check_for_setup_error: Can not get device type."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:157
#, python-format
msgid "check_for_setup_error: Device type is:%(type)s, version is:%(version)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:164
msgid ""
"check_for_setup_error: Product version not right. Please make sure the "
"product version is V1."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:175
msgid "_get_device_type: Storage Pool must be configured."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:184
#, python-format
msgid "create_volume:volume name: %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:198
#, python-format
msgid "delete_volume: volume name: %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:205
#, python-format
msgid "delete_volume:No need to delete volume. Volume %(name)s does not exist."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:214
#, fuzzy, python-format
msgid "create_export: volume name:%s"
msgstr "Vytvořit snímek svazku %s"

#: cinder/volume/drivers/huawei/huawei_iscsi.py:218
#, python-format
msgid "create_export:Volume %(name)s does not exist."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:238
#, python-format
msgid "initialize_connection: volume name: %(volume)s. initiator name: %(ini)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:253
#, python-format
msgid ""
"initialize_connection:Failed to find target ip for "
"initiator:%(initiatorname)s, please check config file."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:263
#, python-format
msgid "initialize_connection:Failed to find target iSCSI iqn. Target IP:%(ip)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:301
#, python-format
msgid ""
"initialize_connection:host name: %(host)s, initiator name: %(ini)s, "
"hostport name: %(port)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:311
#, python-format
msgid ""
"initialize_connection:Failed to find the given volume. volume "
"name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:363
#, python-format
msgid "terminate_connection:volume name: %(volume)s, initiator name: %(ini)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:372
#, python-format
msgid "terminate_connection:Host does not exist. Host name:%(host)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:381
#, python-format
msgid "terminate_connection:volume does not exist. volume name:%(volume)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:400
#, python-format
msgid ""
"terminate_connection:No map between host and volume. Host "
"name:%(hostname)s, volume name:%(volumename)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:418
#, python-format
msgid ""
"terminate_connection:No initiator is added to the host. Host "
"name:%(hostname)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:431
#, python-format
msgid "create_snapshot:snapshot name:%(snapshot)s, volume name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:438
msgid "create_snapshot:Device does not support snapshot."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:444
msgid "create_snapshot:Resource pool needs 1GB valid size at least."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:451
#, python-format
msgid "create_snapshot:Volume does not exist. Volume name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:460
#, python-format
msgid "create_snapshot:Snapshot does not exist. Snapshot name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:472
#, python-format
msgid "delete_snapshot:snapshot name:%(snapshot)s, volume name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:479
msgid "delete_snapshot:Device does not support snapshot."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:488
#, python-format
msgid "delete_snapshot:Snapshot does not exist. snapshot name:%(snap)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:501
#, python-format
msgid ""
"create_volume_from_snapshot:snapshot name:%(snapshot)s, volume "
"name:%(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:509
#, python-format
msgid ""
"create_volume_from_snapshot:Device does not support create volume from "
"snapshot. Volume name:%(volume)s, snapshot name:%(snapshot)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:520
#, python-format
msgid ""
"create_volume_from_snapshot:Snapshot does not exist. Snapshot "
"name:%(name)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:571
msgid "Config file is wrong. Controler IP, UserName and UserPassword must be set."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:577
#, python-format
msgid "_check_conf_file: %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:588
#, python-format
msgid "_read_xml:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:616
#, python-format
msgid "Write login information to xml error. %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:620
#, python-format
msgid "_get_login_info error. %s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:642
#, python-format
msgid ""
"Config file is wrong. LUNType must be \"Thin\"  or \"Thick\". "
"LUNType:%(type)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:669
msgid "_get_lun_set_info:Use default prefetch type. Prefetch type:Intelligent."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:680
msgid ""
"_get_lun_set_info:No available pools! Please check whether storage pool "
"is created."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:690
#, python-format
msgid "_get_lun_set_info:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:740
msgid ""
"_get_maximum_pool:maxpoolid is None. Please check config file and make "
"sure the \"Name\" in \"StoragePool\" is right."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:758
#, python-format
msgid "_get_iscsi_info:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:768
#, python-format
msgid "CLI command:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:835
#, python-format
msgid "_execute_cli:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:842
#, python-format
msgid ""
"_name_translate:Name in cinder: %(old)s, new name in storage system: "
"%(new)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:876
#, python-format
msgid ""
"_create_hostgroup:Failed to Create hostgroup. Hostgroup name: %(name)s. "
"out:%(out)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:905
#, python-format
msgid ""
"_add_host:Failed to add host to hostgroup. host name:%(host)s hostgroup "
"id:%(hostgroup)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:931
#, python-format
msgid ""
"_add_initiator:Failed to add initiator. initiator name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:945
#, python-format
msgid ""
"_delete_initiator:ERROE:Failed to delete initiator. initiator "
"name:%(name)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:995
#, python-format
msgid ""
"_add_hostport:Failed to add hostport. port name:%(port)s port "
"information:%(info)s host id:%(host)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1013
#, python-format
msgid "_delete_hostport:Failed to delete host port. port id:%(portid)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1020
#, python-format
msgid "_get_tgt_iqn:iSCSI IP is %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1053
#, python-format
msgid "_get_tgt_iqn:iSCSI target iqn is:%s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1090
#, python-format
msgid ""
"_map_lun:Failed to add hostmap. hostid:%(host)s lunid:%(lun)s "
"hostlunid:%(hostlunid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1126
#, python-format
msgid ""
"_delete_map:There are IOs accessing the system. Retry to delete host map."
" map id:%(mapid)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1132
#, python-format
msgid "_delete_map:Failed to delete host map. mapid:%(mapid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1146
#, python-format
msgid "_delete_host: Failed delete host. host id:%(hostid)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1227
#, python-format
msgid ""
"_active_snapshot:Failed to active snapshot. snapshot id:%(name)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1241
#, python-format
msgid ""
"_disable_snapshot:Failed to disable snapshot. snapshot id:%(id)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1255
#, python-format
msgid ""
"_delete_snapshot:Failed to delete snapshot. snapshot id:%(id)s. "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1312
#, python-format
msgid "_create_volume:Failed to Create volume. volume name:%(name)s. out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1325
#, python-format
msgid "_delete_volume:Failed to delete volume. Volume name:%(name)s out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1342
#, python-format
msgid ""
"_create_luncopy:Failed to Create LUNcopy. LUNcopy name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1356
#, python-format
msgid ""
"_start_luncopy:Failed to start LUNcopy. LUNcopy id:%(luncopyid)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1386
#, python-format
msgid ""
"_wait_for_luncopy:LUNcopy status is not normal. LUNcopy "
"name:%(luncopyname)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1419
#, python-format
msgid ""
"_delete_luncopy:Failed to delete LUNcopy. LUNcopy id:%(luncopyid)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1434
#, python-format
msgid ""
"_create_snapshot:Failed to Create snapshot. Snapshot name:%(name)s "
"out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1472
#, python-format
msgid ""
"_change_lun_controller:Failed to change lun owning controller. lun "
"id:%(lunid)s. new controller:%(controller)s. out:%(out)s"
msgstr ""

#: cinder/volume/drivers/huawei/huawei_iscsi.py:1488
msgid "_is_resource_pool_enough:Resource pool for snapshot not be added."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:127
#, fuzzy, python-format
msgid "API %(name)s failed: %(reason)s"
msgstr "Obraz %(image_id)s je nepřijatelný: %(reason)s"

#: cinder/volume/drivers/netapp/iscsi.py:138
#: cinder/volume/drivers/netapp/iscsi.py:1171
#, python-format
msgid "Using WSDL: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:148
#, python-format
msgid "Using DFM server: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:153
#, python-format
msgid "Using storage service: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:158
#, python-format
msgid "Using storage service prefix: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:164
#, fuzzy, python-format
msgid "Using vfiler: %s"
msgstr "Vyvoláno Nenalezeno: %s"

#: cinder/volume/drivers/netapp/iscsi.py:177
msgid "Either netapp_storage_service or netapp_storage_service_prefix must be set"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:208
#, fuzzy
msgid "Connected to DFM server"
msgstr "Znovu připojeno k frontě"

#: cinder/volume/drivers/netapp/iscsi.py:286
#, python-format
msgid "Discovered %(dataset_count)s datasets and %(lun_count)s LUNs"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:321
#, fuzzy, python-format
msgid "Job failed: %s"
msgstr "Vyvoláno Nenalezeno: %s"

#: cinder/volume/drivers/netapp/iscsi.py:350
msgid ""
"Attempt to use volume_type without specifying "
"netapp_storage_service_prefix flag."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:354
msgid ""
"You must set the netapp_storage_service flag in order to create volumes "
"with no volume_type."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:424
msgid "Failed to provision dataset member"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:439
msgid "No LUN was created by the provision job"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:467
#: cinder/volume/drivers/netapp/iscsi.py:1254
#, python-format
msgid "No entry in LUN table for volume %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:485
msgid "Failed to remove and delete dataset LUN member"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:501
msgid "Failed to remove and delete dataset Qtree member"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:542
#, python-format
msgid "No entry in LUN table for volume %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:562
#, fuzzy, python-format
msgid "Failed to get LUN details for LUN ID %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:579
#, fuzzy, python-format
msgid "Failed to get host details for host ID %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:816
#: cinder/volume/drivers/netapp/iscsi.py:863
#, python-format
msgid "No LUN ID for volume %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:825
#, fuzzy, python-format
msgid "Failed to get target portal for filer: %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:830
#, fuzzy, python-format
msgid "Failed to get target IQN for filer: %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:934
msgid ""
"Failed to get LUN list. Is the DFM host time-synchronized with Cinder "
"host?"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1046
#: cinder/volume/drivers/netapp/iscsi.py:1385
#: cinder/volume/drivers/netapp/iscsi.py:1703
#: cinder/volume/drivers/netapp/nfs.py:78
#, python-format
msgid ""
"Cannot create volume of size %(vol_size)s from snapshot of size "
"%(snap_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1058
#, python-format
msgid ""
"Cannot create volume of type %(new_type)s from snapshot of type "
"%(old_type)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1079
#: cinder/volume/drivers/netapp/nfs.py:277
#, python-format
msgid ""
"Cannot create clone of size %(vol_size)s from volume of size "
"%(src_vol_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1090
#, python-format
msgid "Cannot create clone of type %(new_type)s from volume of type %(old_type)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1147
#, python-format
msgid "No metadata property %(prop)s defined for the LUN %(name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1220
#: cinder/volume/drivers/netapp/iscsi.py:1565
msgid "Success getting LUN list from server"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1242
#: cinder/volume/drivers/netapp/iscsi.py:1580
#, python-format
msgid "Created LUN with name %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1258
#: cinder/volume/drivers/netapp/iscsi.py:1373
#: cinder/volume/drivers/netapp/iscsi.py:1597
#, python-format
msgid "Destroyed LUN %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1295
#, python-format
msgid "Mapped LUN %(handle)s to the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1302
#, python-format
msgid ""
"Succesfully fetched target details for LUN %(handle)s and initiator "
"%(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1307
#: cinder/volume/drivers/netapp/iscsi.py:1641
#, fuzzy, python-format
msgid "Failed to get LUN target details for the LUN %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:1311
#: cinder/volume/drivers/netapp/iscsi.py:1652
#, fuzzy, python-format
msgid "Failed to get target portal for the LUN %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:1315
#: cinder/volume/drivers/netapp/iscsi.py:1655
#, fuzzy, python-format
msgid "Failed to get target IQN for the LUN %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:1348
#, python-format
msgid "Unmapped LUN %(handle)s from the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1369
#, python-format
msgid "No entry in LUN table for snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1413
#: cinder/volume/drivers/netapp/iscsi.py:1911
msgid "Object is not a NetApp LUN."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1423
#: cinder/volume/drivers/netapp/iscsi.py:2192
#, python-format
msgid "Cloned LUN with new name %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1443
#, fuzzy, python-format
msgid "Could not find handle for LUN named %s"
msgstr "Nelze najít obslužnou rutinu pro svazek %(driver_type)s."

#: cinder/volume/drivers/netapp/iscsi.py:1462
#: cinder/volume/drivers/netapp/iscsi.py:1940
#, python-format
msgid ""
"Cannot clone volume of size %(vol_size)s from src volume of size "
"%(src_vol_size)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1522
#, python-format
msgid "Using NetApp filer: %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1589
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1632
#, python-format
msgid "Mapped LUN %(name)s to the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1636
#, python-format
msgid ""
"Succesfully fetched target details for LUN %(name)s and initiator "
"%(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1692
#, python-format
msgid "Snapshot %s deletion successful"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1721
#, python-format
msgid "Unmapped LUN %(name)s from the initiator %(initiator_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1739
#, fuzzy, python-format
msgid "Failed to get vol with required size for volume: %s"
msgstr "Nelze získat metadata pro ip: %s"

#: cinder/volume/drivers/netapp/iscsi.py:1815
#, python-format
msgid "Error mapping lun. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1833
#, python-format
msgid "Error unmapping lun. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:1927
#, python-format
msgid "Could not find attribute for LUN named %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:2061
#, python-format
msgid "No iscsi service found for vserver %s"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:2196
#, python-format
msgid "No clonned lun named %s found on the filer"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:2381
#, python-format
msgid "Error finding luns for volume %(vol)s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:2485
#, python-format
msgid "Clone operation with src %(name)s and dest %(new_name)s completed"
msgstr ""

#: cinder/volume/drivers/netapp/iscsi.py:2488
#, python-format
msgid "Clone operation with src %(name)s and dest %(new_name)s failed"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:316
#, python-format
msgid ""
"Cloning with params ip %(host_ip)s, exp_path\n"
"                    %(export_path)s, vol %(volume_name)s,\n"
"                    clone_name %(clone_name)s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:465
#, python-format
msgid "No interface found on cluster for ip %s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:491
#, python-format
msgid ""
"No volume on cluster with vserver\n"
"                                   %(vserver)s and junction path "
"%(junction)s\n"
"                                   "
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:497
#, python-format
msgid ""
"Cloning with params volume %(volume)s,src %(src_path)s,\n"
"                    dest %(dest_path)s, vserver %(vserver)s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:551
#, python-format
msgid "No storage path found for export path %s"
msgstr ""

#: cinder/volume/drivers/netapp/nfs.py:559
#, python-format
msgid "Cloning with src %(src_path)s, dest %(dest_path)s"
msgstr ""

#: cinder/volume/drivers/nexenta/__init__.py:27
msgid "Nexenta SA returned the error"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:64
#, python-format
msgid "Sending JSON data: %s"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:69
#, python-format
msgid "Auto switching to HTTPS connection to %s"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:75
msgid "No headers in server response"
msgstr ""

#: cinder/volume/drivers/nexenta/jsonrpc.py:76
#, fuzzy
msgid "Bad response from server"
msgstr "Špatná odpověď od SolidFire API"

#: cinder/volume/drivers/nexenta/jsonrpc.py:79
#, fuzzy, python-format
msgid "Got response: %s"
msgstr "odpověď %s"

#: cinder/volume/drivers/nexenta/volume.py:99
#, python-format
msgid "Volume %s does not exist in Nexenta SA"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:211
#, python-format
msgid "Ignored target group creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:220
#, python-format
msgid "Ignored target group member addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:228
#, python-format
msgid "Ignored LU creation error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:238
#, python-format
msgid "Ignored LUN mapping entry addition error \"%s\" while ensuring export"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:274
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/volume.py:282
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:74
#, python-format
msgid "CLIQ command returned %s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:80
#, python-format
msgid "Malformed response to CLIQ command %(verb)s %(cliq_args)s. Result=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:88
#, python-format
msgid "Error running CLIQ command %(verb)s %(cliq_args)s.  Result=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:118
#, python-format
msgid ""
"Unexpected number of virtual ips for cluster  %(cluster_name)s. "
"Result=%(_xml)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:171
#, python-format
msgid "Volume info: %(volume_name)s => %(volume_attributes)s"
msgstr ""

#: cinder/volume/drivers/san/hp_lefthand.py:235
msgid "local_path not supported"
msgstr ""

#: cinder/volume/drivers/san/san.py:147
#, fuzzy, python-format
msgid "Error running SSH command: %s"
msgstr "Při spuštění příkazu došlo k nečekané chybě."

#: cinder/volume/drivers/san/san.py:168
msgid "Specify san_password or san_private_key"
msgstr ""

#: cinder/volume/drivers/san/san.py:172
msgid "san_ip must be set"
msgstr ""

#: cinder/volume/drivers/san/solaris.py:80
#, python-format
msgid "Cannot parse list-view output: %s"
msgstr ""

#: cinder/volume/drivers/san/solaris.py:175
#, python-format
msgid "LUID not found for %(zfs_poolname)s. Output=%(out)s"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:139
msgid "Login to 3PAR array invalid"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:163
#: cinder/volume/drivers/san/hp/hp_3par_common.py:501
#, python-format
msgid "CPG (%s) doesn't exist on array"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:312
#, python-format
msgid "SSH Command failed after '%(total_attempts)r' attempts: '%(command)s'"
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:316
#, fuzzy, python-format
msgid "Error running ssh command: %s"
msgstr "Při spuštění příkazu došlo k nečekané chybě."

#: cinder/volume/drivers/san/hp/hp_3par_common.py:546
#, python-format
msgid "Must specify a valid persona %(valid)s, value '%(persona)s' is invalid."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:602
#, python-format
msgid ""
"Must specify a valid provisioning type %(valid)s, value '%(prov)s' is "
"invalid."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_common.py:630
#, fuzzy, python-format
msgid "Volume (%s) already exists on array"
msgstr "skupina %s již existuje"

#: cinder/volume/drivers/san/hp/hp_3par_common.py:692
#, fuzzy, python-format
msgid "Unexpected state while cloning %s"
msgstr "Při spuštění příkazu došlo k nečekané chybě."

